### ISSUE TITLE
make urls to links and parse html

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#146] opened 2017-03-23 15:05 UTC
**make urls to links and parse html**

from mail:
Would it be possible to hyperlink the references that are actually hyperlinks?  Would make it easier for users to get to the content instead of copypaste it.
 
The description are a bit odd, since they show the html code which is not too user friendly. This might also be something to consider

-----
fbitem-dataset42dc004c-7254-46db-8597-0be94cb75e8c
Reported by: @mortenhofft
System: Chrome 56.0.2924 / Mac OS X 10.11.6
Referer: https://demo.gbif.org/dataset/42dc004c-7254-46db-8597-0be94cb75e8c/taxonomy/127690321
Window size: width 1912 - height 1080
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-23T15:00:45.512Z',mode:absolute,to:'2017-03-23T15:06:45.512Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-23T15:00:45.512Z',mode:absolute,to:'2017-03-23T15:06:45.512Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kbraak** [comment] 2017-03-23 15:48
@MortenHofft - is this related to / duplicate of https://github.com/gbif/portal16/issues/113 ?

**Comment by MortenHofft** [comment] 2017-06-21 16:01
There is still information missing on species pages, but descriptions are parsed and shown as proper html. 

https://demo.gbif.org/species/127690321

![screen shot 2017-06-21 at 17 58 19](https://user-images.githubusercontent.com/6759267/27394120-58ecd518-56ab-11e7-896c-00eda065df0e.png)

**Closed by MortenHofft** 2017-06-21 16:01 UTC
Labels: bug, portal
