### ISSUE TITLE
Order of event listing not intuitive.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#39] opened 2017-01-17 16:12 UTC
**Order of event listing not intuitive.**

Events are currently listed from latest to earliest (with no indication of where &#39;now&#39; is). More logical arrangement would be to start from the present date and go forward, with a separate link to &#39;past events&#39; that could then work backwards from the present.

-----
fbitem-683b60301990d1f82520ab24cf69b12e179b31a7
Reported by: thirsch@gbif.org
System: Chrome 55.0.2883 / Mac OS X 10.12.2
Referer: https://demo.gbif.org/cms/search?type=event
Window size: width 1410 - height 789
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-17T16:07:29.186Z',mode:absolute,to:'2017-01-17T16:13:29.186Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-17T16:07:29.186Z',mode:absolute,to:'2017-01-17T16:13:29.186Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment] 2017-01-18 10:41
Agreed - and @burkeker is already doing progress on that. I'm closing as duplicate of https://github.com/gbif/portal16/issues/180 and will attach you comment. thanks

**Closed by MortenHofft** 2017-01-18 10:41 UTC
Labels: bug, Under review
