### ISSUE TITLE
Bad text on institutional page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3052] opened 2020-10-14 13:26 UTC
**Bad text on institutional page**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/89718e02c6ffeedaa124e6eb8e756202:e0dcaf56100db4bbb6685fe0018b7f66f09b62ebe6fb69c8c18273e0e2ea011fd3066d6568d9cf925fa9bf3dbd78df320bdba30db7c935fff0a39f692af229fe)
System: Firefox 81.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/publisher/search?country=AM
Window size: width 1760 - height 895
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-14T13:21:09.005Z',mode:absolute,to:'2020-10-14T13:27:09.005Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-14T13:21:09.005Z',mode:absolute,to:'2020-10-14T13:27:09.005Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment] 2020-10-15 06:10
duplicate of https://github.com/gbif/portal-feedback/issues/3053

**Closed by ManonGros** 2020-10-15 06:10 UTC
Labels: Under review, data content
