### ISSUE TITLE
dataset not indexed although validator doesn't detect any critical issue

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal-feedback#1628] opened 2018-11-07 12:59 UTC
The dataset concerned is published through symbiota: [C.P. Gillette Museum of Arthropod Diversity](https://www.gbif.org/dataset/323b0e80-5e4b-4cc4-936a-d93fc8cae9bc).

The [validator](https://www.gbif.org/tools/data-validator/1540718763155) doesn't detect any critical issue.

Edit: the dataset does have occurrenceIDs.

**Comment by MattBlissett** [comment] 2018-11-07 15:33
Duplicate of https://github.com/gbif/gbif-data-validator/issues/76 (for the validator not picking this up)

meta.xml: `<field index="6" term="http://rs.tdwg.org/dwc/terms/occurrenceID"/>` (zero based)

So checking that field has unique values:
```
cat occurrences.csv | cut -d, -f7 | sort | uniq -d     (on Mac or Linux)
cat occurrences.csv | cut -d, -f7 | sort | uniq -D     (on Linux)
```

shows the values, e.g. YOHO-00024.
```
grep YOHO-00024 occurrences.csv
```

This relies on there being no quoted commas, which is the case at least for the first few columns which are of interest:
```
(head -n 5 occurrences.csv; grep YOHO-00024 occurrences.csv) | column -n -s , -t | less -S
```

(Or `(head -n 5 occurrences.csv; grep YOHO-00024 occurrences.csv) | csvtool readable - | less -S` for proper support of CSV, but you'd probably need to install csvtool.)

**Closed** 2019-01-02 15:22 UTC
Labels: data content, data validator
