### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4337] opened 2022-10-11 11:31 UTC
**Broken images**

It appears as if most images are broken. they are missing their identifier

https://www.gbif.org/occurrence/gallery?dataset_key=cd6e21c8-9e8a-493a-8a76-fbf7862069e5

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/27b756117b2ee4fa3f131352963a5e21:b06c8d5514202f30f96565acd7a3b2a710aa19e021ebdcee82a249751d85b9c1ee4f4a92efcc993f8a6d153ae51c13c6a64fbe822e36fafe1126dd0a4861b9a9ea6e133a06ef1f20b21b40f8994875aae8dbd85da09c301037b1b354f066012c8c17bcc5aa99c15ffe02842367da4e61de3e4b1cb3a93a6bd69261379e6efc82) - [Send email](https://www.gbif.org/api/feedback/user/mailto/27b756117b2ee4fa3f131352963a5e21:b06c8d5514202f30f96565acd7a3b2a710aa19e021ebdcee82a249751d85b9c1ee4f4a92efcc993f8a6d153ae51c13c6a64fbe822e36fafe1126dd0a4861b9a9ea6e133a06ef1f20b21b40f8994875aae8dbd85da09c301037b1b354f066012c8c17bcc5aa99c15ffe02842367da4e61de3e4b1cb3a93a6bd69261379e6efc82)
System: Chrome 106.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/1451067887
Window size: width 1772 - height 1419
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-11T11:26:26.000Z',to:'2022-10-11T11:32:26.000Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-11T11:26:26.000Z',to:'2022-10-11T11:32:26.000Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: cd6e21c8-9e8a-493a-8a76-fbf7862069e5
publishingOrgKey: 061b4f20-f241-11da-a328-b8a03c50a862
Network keys: 17abcf75-2f1e-46dd-bf75-a5b21dd02655

**Comment by MattBlissett** [comment] 2022-10-11 15:25
Duplicate of #1598, and I hear Kew are working on it.

**Closed as not planned by MattBlissett** 2022-10-11 15:25 UTC
Labels: Under review, data content, GB

**Comment by MortenHofft** [comment] 2022-10-12 03:45
I had a feeling I had mentioned it before. 4 years ago apparently.
