### ISSUE TITLE
ID

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1894] opened 2019-04-16 00:57 UTC
**ID**

S. angustifolium (Oliv.) Engl.

-----

System: Chrome 73.0.3683 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/0074093dcd24e228a219850462dee1d8:42e0f2b7471a0ee9ddc5ae005bb51c6dcfd8feb700f2da56d1bd837b58f51b8798e8dcf7542397cde00163f79393ec322d63c627394eb867e42cfe72f652f309)
Referer: https://www.gbif.org/occurrence/1137488429
Window size: width 1331 - height 531
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-16T00:52:48.754Z',mode:absolute,to:'2019-04-16T00:58:48.754Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-16T00:52:48.754Z',mode:absolute,to:'2019-04-16T00:58:48.754Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment] 2019-07-24 07:57
duplicate of https://github.com/gbif/portal-feedback/issues/1899

**Closed by ManonGros** 2019-07-24 07:57 UTC
Labels: NL, data content
