### ISSUE TITLE
Unable to download occurrence data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#115] opened 2017-03-06 12:17 UTC
**Unable to download occurrence data**

Hi,

The new demo site is still not allowing users to log in with their normal account to download data. 

Is there a problem with the site at the moment?

Best, 

B

-----
fbitem-3fc2452e42c851d70896794fb026acd0f4db0c4f
Reported by: betina.frinault@stx.ox.ac.uk
System: Chrome 56.0.2924 / Windows 7 0.0.0
Referer: https://demo.gbif.org/search?q
Window size: width 1920 - height 1021
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-06T12:12:17.558Z',mode:absolute,to:'2017-03-06T12:18:17.558Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-06T12:12:17.558Z',mode:absolute,to:'2017-03-06T12:18:17.558Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by timrobertson100** [comment] 2017-03-06 12:44
I have just synchronised all accounts and see yours was migrated.  Can you please try again?

**Comment by timrobertson100** [comment] 2017-03-06 12:46
Duplicate of #114

**Closed by timrobertson100** 2017-03-06 12:46 UTC
Labels: GB, question
