### ISSUE TITLE
this messaging system is problematic!

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1553] opened 2018-09-24 17:56 UTC
**this messaging system is problematic!**

This messaging system is problematic; it should be set up as ITS OWN PAGE (one of the few exceptions to the "do not open a page in a different window" UX rule) so normal web navigation can be used (e.g., I need to go "back" from this page to get a URL for you, but I'm fairly sure that if I do so that the text I've put in would disappear).

In fact, the rather detailed content of a message I just composed just disappeared for no apparent reason (an errant mouse-click?); very, very, VERY annoying.

I know you have spam issues, but please fix this problematic system so as not to discourage folks from contacting you. 

Aloha,
Philip Thomas

-----

User provided contact info: pt@philipt.com
System: Chrome 68.0.3440 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/346e5e7b193a6b82d1497458dd3adc0a:547daf9dc573293bdc7c45fdb2bbe9fd69c5bd2f48264cb794831bad1b3e46c52a7b661641b846aa2f759df62ca24469afe66ee3e78744747ca85b3f2296175a)
Referer: https://www.gbif.org/news/2LrgV5t3ZuGeU2WIymSEuk/adding-sequence-based-identifiers-to-backbone-taxonomy-reveals-dark-taxa-fungi
Window size: width 1536 - height 766
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-24T17:51:38.357Z',mode:absolute,to:'2018-09-24T17:57:38.357Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-24T17:51:38.357Z',mode:absolute,to:'2018-09-24T17:57:38.357Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment] 2018-09-24 20:32
> In fact, the rather detailed content of a message I just composed just disappeared for no apparent reason (an errant mouse-click?); very, very, VERY annoying.

I'm unable to reproduce text suddenly disappearing. Even closing the feedback window will retain the information when reopened. Unless the user leaves the page that is.

**Comment by MortenHofft** [comment] 2018-09-24 20:37
> I need to go "back" from this page to get a URL for you, but I'm fairly sure that if I do so that the text I've put in would disappear

When implementing the feedback, we did it "in page" with the idea that you could do it with little interruption and having the info on the page ready at hand. And it allows us to see where users report it from. 

But it is a fair point that if you need to view another page as well for the feedback and don't know how to do that in a new tab (or forget to), then the text you entered is lost. Perhaps we should store it in the session or such, to spare users the frustration of lost feedback.

**Comment by MortenHofft** [comment] 2020-11-09 10:53
Since we haven't heard anyone else having issues with this, then I'm closing it.

**Closed by MortenHofft** 2020-11-09 10:53 UTC
Labels: idea, portal
