### ISSUE TITLE
register

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#170] opened 2017-04-12 17:18 UTC
**register**

I am unable to register in order to download Ochotona data

-----
fbitem-3fc2452e42c851d70896794fb026acd0f4db0c4f

System: Chrome 57.0.2987 / Windows 7 0.0.0
Referer: https://demo.gbif.org/search?q=pika
Window size: width 1111 - height 784
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-12T17:13:59.269Z',mode:absolute,to:'2017-04-12T17:19:59.269Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-12T17:13:59.269Z',mode:absolute,to:'2017-04-12T17:19:59.269Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment] 2017-04-27 16:20
Duplicate of #180.

**Closed by MattBlissett** 2017-04-27 16:20 UTC
Labels: question, Under review, US
