### ISSUE TITLE
Duplicate MG datasets

### ISSUE THREAD

**Issue by kcopas** [gbif/portal-feedback#1316] opened 2018-04-24 08:29 UTC
Noting today that we have two sets of duplicate datasets from Malagasy institutions: see
+ https://www.gbif.org/dataset/search?publishing_org=c0e25223-5b55-4e02-8556-178781709720
+ https://www.gbif.org/dataset/search?publishing_org=7bec6457-78d6-416f-a185-00ae45e1d9a0 (first two items here)

This potentially looks messy, with  different numbers of citations and different licences (one of each under CC0, which is irrevocable). However, the CC0 versions are the ones that resolve to live endpoints on MadBIF's IPT.

**Comment by jlegind** [comment] 2018-05-01 11:45
The 4c1bc8db-584e-4d69-bf8c-9221ff5bbb34 dataset was removed. 'Duplicate of' has been set in the registry.

**Closed by jlegind** 2018-05-01 11:45 UTC
Labels: data content
