### ISSUE TITLE
not all dataset are linked to their publishers

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#252] opened 2017-07-14 12:12 UTC
**not all dataset are linked to their publishers**

Example: National museum of Kenya published https://demo.gbif.org/dataset/63cccd67-894b-4901-aed2-8c05ad4ba390#registration but this dataset is not linked to https://demo.gbif.org/publisher/fd515d3a-b237-42de-bba6-760008580da5. This bug doesn&#39;t appear in GBIF.org. @kcopas can provide more details if needed

-----
fbitem-publisherfd515d3a-b237-42de-bba6-760008580da5
Reported by: mblaursen@gbif.org
System: Firefox 54.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/publisher/fd515d3a-b237-42de-bba6-760008580da5
Window size: width 1920 - height 947
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-14T12:07:51.699Z',mode:absolute,to:'2017-07-14T12:13:51.699Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-14T12:07:51.699Z',mode:absolute,to:'2017-07-14T12:13:51.699Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment] 2017-07-19 09:02
Thanks for reporting.
It is now. Perhaps a caching issue? Seems odd though. 
https://demo.gbif.org/dataset/search?publishing_org=fd515d3a-b237-42de-bba6-760008580da5

Since I cannot reproduce it I'll close it.

**Closed by MortenHofft** 2017-07-19 09:02 UTC
Labels: bug, Under review
