### ISSUE TITLE
Mal funcionamiento en Google Chrome

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3399] opened 2021-04-27 16:29 UTC
**Mal funcionamiento en Google Chrome**

Al realizar consultas de una especie, los resultados obtenidos en google chrome se encuentran limitados; no se obtiene visualización de la clasificación, fotografías, distribución. 
Solo se esta teniendo buena experiencia en Safari o Firefox Mozilla.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c41d55c6fd4cf2096d92de12cbdf1b80:638f7633dd0d78c5364b6272ff2430d56b25310d1494c5607537c9697bd821f15979ff4940d4da456ee581b94db42ebad81ae0299d273f26eec61612423758a5)
System: Chrome 90.0.4430 / Mac OS X 10.15.7
Referer: https://www.gbif.org/es/faq
Window size: width 1440 - height 796
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-27T16:24:25.303Z',to:'2021-04-27T16:30:25.303Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-27T16:24:25.303Z',to:'2021-04-27T16:30:25.303Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment] 2021-04-28 06:03
Google translate
> Malfunction in Google Chrome
> 
> When making queries of a kind, the results obtained in google chrome are limited; you do not get visualization of the classification, photographs, distribution.
You are only having a good experience in Safari or Mozilla Firefox.

**Comment by MortenHofft** [comment] 2021-04-28 06:16
Thank you for reporting it.

I need some more context though. What page are we talking about. Could you provide an example please? Possible with a screenshot? And if you really want to make me happy, then you also look in the developer tools (⌥ ⌘ i (alt+cmd+i)) console and copy any error messages .

Currently my best guess is that the data loading was slow first time when you looked in Chrome and fast afterwards in the other browsers. But hard to say without knowing more.

> user notified by email

**Comment by orojasz** [comment] 2021-04-28 14:16
Good Morning,
On the website of GBIF (www.gbif.org) using google chrome, when I want to do a search about some species, the results were limited to the overview; and it is no available information associated with taxonomic classification, distribution map, occurrences, etc. 
I attach to this message two screenshots to show you the differences, the first showing the results obtained with google chrome, and the second image showing the same search with Safari.

I will attentive to any question or more information

![GBIF-Safari](https://user-images.githubusercontent.com/58661139/116418822-18898a00-a802-11eb-9531-aa4daf5f47d6.png)

![GBIF-Chrome](https://user-images.githubusercontent.com/58661139/116418815-16bfc680-a802-11eb-9abc-f01c41f18ed4.png)

**Comment by MortenHofft** [comment] 2021-05-03 08:19
Thank you for taking the time!

And weird - I have the same operating system and the same browser in the same overall version `Chrome 90.0.4430 / Mac OS X 10.15.7` and I cannot reproduce it. Those kind of bugs are difficult.

I see that you have a lot of browser plugins. Could you try again in an incognito tab (shift-cmd-N) (that will disable your cache and plugins). Thank you for your help.

**Comment by MortenHofft** [comment] 2024-11-08 07:56
I'm unable to reproduce any of this, my best guess is a temporary api outage. I will close the issue since it is years old. Please create new issue if you still experience problems

**Closed as completed by MortenHofft** 2024-11-08 07:56 UTC
Labels: bug, question, portal, CO, Needs clarification
