### ISSUE TITLE
broken image links

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1842] opened 2019-03-16 21:02 UTC
**broken image links**

The majority of the images do not show for Kew

-----

System: Chrome 73.0.3683 / Mac OS X 10.13.6
User: [See in registry](https://www.gbif.org/api/feedback/user/89a9915eed303bd349931925382190f2:f2fccf2ceb1d38ccf49b4d4213f560f23a9f386347a03a556733b2080832381d6f0849d2de7d053a8f5c39af71663b06a3ecfed2048b4a13b5ab865df29a206d)
Referer: https://www.gbif.org/occurrence/gallery?dataset_key=cd6e21c8-9e8a-493a-8a76-fbf7862069e5
Window size: width 1440 - height 796
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-16T20:57:07.812Z',mode:absolute,to:'2019-03-16T21:03:07.812Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-16T20:57:07.812Z',mode:absolute,to:'2019-03-16T21:03:07.812Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MattBlissett** [comment] 2019-03-18 09:00
Duplicate of #1598.

**Closed by MattBlissett** 2019-03-18 09:00 UTC
Labels: Under review, data content
