### ISSUE TITLE
error/ mismatvh in parent of genus 'kiwi'

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2316] opened 2019-11-29 02:08 UTC
**error/ mismatvh in parent of genus &#39;kiwi&#39;**

records (about 260) for species in the genus Kiwi Tersilochinae (Hymenoptera: Ichneumonidae) are currently showing as Apteryx, apterygidae (Aves) ie. as the bird kiwi rather than the wasp in gbif.  the records are published by the collection i am the manager for so i can control the names from my end but they seem to be correct there. is this an issue on gbif? and how can it be fixed.  thank you 

`https://www.gbif.org/species/10252810`

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8949fdd0ca2b578ccaf6a0d44bb5800c:ebc4477bec7d1b2c23107ecc116e395af40c4f9a55669f34c2a4ec8f79570d040b437be0f5d322e1f950e139b43e4489889bd8833270f629693dbad7ee223e41)
System: Chrome 78.0.3904 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1866 - height 953
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-29T02:03:12.952Z',mode:absolute,to:'2019-11-29T02:09:12.952Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-29T02:03:12.952Z',mode:absolute,to:'2019-11-29T02:09:12.952Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment] 2019-12-03 08:15
This species come from a taxonomic treatment.
How are the higher ranks defined in these situation? The title and the body of the text show that the species belong to Hymenoptera: Ichneumonidae. Could we use that to avoid this type of issue?

**Comment by ManonGros** [comment] 2021-09-01 12:01
This issue comes from a PLAZI treatment: https://www.gbif.org/species/157422467
https://www.gbif.org/publisher/7ce8aef0-9e92-11dc-8738-b8a03c50a862

**Comment by ManonGros** [comment] 2021-09-17 12:40
the issue is fixed in the new backbone taxonomy

**Closed by ManonGros** 2021-09-17 12:40 UTC
Labels: data content, backbone, Pending
