### ISSUE TITLE
Identification date

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1420] opened 2018-06-22 05:22 UTC
**Identification date**

This specimen is included in the material examined in Castle & Randall's 1999 revision of the Heterocongrinae which is why the ID date is given as 1999 (i.e. highest ID accuracy)

-----

System: Chrome 67.0.3396 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/b547fa8a8d5ef8cd14886182017bdf69:3a3e6af22654f07eee84f45471bc9566d6ebb03e06f40f8e1ae15002aadf317a4af74eb682116aeecfbff432e93c76804243061e80f09cbbb260d8a07167fbac)
Referer: https://www.gbif.org/occurrence/1100587368
Window size: width 1062 - height 927
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-22T05:17:24.996Z',mode:absolute,to:'2018-06-22T05:23:24.996Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-22T05:17:24.996Z',mode:absolute,to:'2018-06-22T05:23:24.996Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment] 2018-08-22 14:17
Is the date flagged as "unlikely" because it contains the year only?

**Comment by MattBlissett** [comment] 2018-08-24 22:08
Yes, so this is a duplicate of #1488 .

**Closed** 2018-10-23 18:39 UTC
Labels: data content
