### ISSUE TITLE
Cannot contact Helpdesk without login is problematic if problem is with registration

### ISSUE THREAD

**Issue by visead** [gbif/portal-feedback#4055] opened 2022-05-04 10:04 UTC
Whilst trying to register, I became stuck in a loop that provided no useful feedback or contact possibilities other than registering a Github issue. This is suboptimal for the vast majority of users.

Problem (in Chrome):
Registration/login popup closes whilst filling in the form, seemingly randomly (perhaps connected to Windows background processes moving focus?)
Solution:
Switched to edge, created user, logged in again in Chrome

Best wishes,

Phil

**Comment by MortenHofft** [comment] 2022-05-04 10:10
Thanks Phil. That does sound annoying. I cannot reproduce it in chrome though. I just tried and created an account fine. I'm not sure how to proceed without more information.
If possible could you perhaps open the dev tools and see if you get any error messages?

**Comment by MortenHofft** [comment] 2022-05-04 10:12
Did you use signup flow with entering an email and password or did you use one of the auth providers (Github, Facebook, Google)?

**Comment by visead** [comment] 2022-05-04 10:27
Hi Morten - typically, I can't reproduce this either now!
I suspect most of the problem is 'user error'...
The problem was whilst trying to signup with an email. However, before this problem occurred I had unsuccessfully tried to login through ORCID a few times, thinking I already had a gbif account (I should do, but it may be with an old email). The login told me 'no orcid connected to this account', which was probably correct at that time.

I have now logged out and tried to 'Continue with ORCID' but got 'This login isn't associated with any accounts - if you already have an account, then login with username/email and password. Or you can register a new account.' - no error in the console (Chrome). GBIF is authorised on my ORCID profile.
I think this might be an RTFM problem om my side (assuming there are instructions for this..?) - I logged in with a username, connected to orcid whilst logged in to gbif, then logged out and was able to 'Continue with ORCID'.

So everything now works as expected, but it was a wobbly route there. Not sure you can do much with this other than provide an easier route to help for login/registration problems on the website.

**Comment by MortenHofft** [comment] 2022-05-04 10:31
I've updated the text to include the helpdesk email - it will be in production in a few minutes.

And yes - you need to connect to ORCiD for us to have access. Similar when connecting to Github and Google. If you haven't signed up with these services, then you need to explicitly link them through your [profile page](https://www.gbif.org/user/profile).

I will close this issue then. Thank you for reporting it. It makes sense to add the helpdesk email address

**Closed as completed by MortenHofft** 2022-05-04 10:31 UTC
Labels: bug, portal
