### ISSUE TITLE
Question about getting information of filed notes or labels  from plant specimens

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4059] opened 2022-05-05 14:57 UTC
**Question about getting information of filed notes or labels from plant specimens**

Dear GBIF team, 

My name is Sebastián Ayala-Ruano, and I'm a research assistant at the Universidad de las Américas in Ecuador. I'm working on a project about using digitalized filed notes or labels from herbarium plant specimens to predict the phenology of plants from Ecuador for conservation purposes. Today, I discovered the GBIF website, and it seems to be perfect for the data collection for our research. However, I have downloaded the CSV files of some searches and realized that there is no column about field notes or descriptions, which is the most important part of our study. Therefore, I would like to know if there is an option to obtain this data using the GBIF website or its API. 

Thanks in advance for your support and help. 

Kind regards,

Sebastián

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/3da51907c8cd92c20ad9379cbc1b8ab4:6d78070ae27c014a5f4585fb3e2ec9236da2c8d2c73cd3d77c67d073209102b13b03a7623ad4fa7837d64cb45f779277dc71c508a876f2fda89b4756063e0b902bb1cf9943fc5f11f74a303d72d4357793c74f051fc140106687ef6da5c913ff) - [Send email](https://www.gbif.org/api/feedback/user/mailto/3da51907c8cd92c20ad9379cbc1b8ab4:6d78070ae27c014a5f4585fb3e2ec9236da2c8d2c73cd3d77c67d073209102b13b03a7623ad4fa7837d64cb45f779277dc71c508a876f2fda89b4756063e0b902bb1cf9943fc5f11f74a303d72d4357793c74f051fc140106687ef6da5c913ff)
System: Firefox 91.0.0 / Linux 0.0.0
Referer: https://www.gbif.org/developer/summary
Window size: width 1366 - height 623
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-05T14:52:46.806Z',to:'2022-05-05T14:58:46.806Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-05T14:52:46.806Z',to:'2022-05-05T14:58:46.806Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment] 2022-05-09 12:27
duplicate of: https://github.com/gbif/portal-feedback/issues/4060

**Closed as completed by ManonGros** 2022-05-09 12:27 UTC
Labels: idea, Under review
