### ISSUE TITLE
Dataset preview shows the wrong number of records

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1551] opened 2018-09-21 20:57 UTC
**Dataset preview shows the wrong number of records**

This checklist has 980 records, but the preview of the dataset shows 1757 records. See `https://www.gbif.org/dataset/search?publishing_org=0bad0631-0693-41fa-afd5-54df0120c509`

-----

User provided contact info: @camiplata
System: Chrome 69.0.3497 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/0510821f235534e070317c9aaff7b6e9:83907c900d8e49c06475f9452ba39d672cec2b6d01a04ff54fdd0c6d70fd3af1baa7cdec9a74d9ca7af8dcccf8ae444073b2193ce1fa04f1ca8fd25a57036364)
Referer: https://www.gbif.org/dataset/42f4a656-a6be-43da-a61e-642d1dec44f4
Window size: width 1309 - height 754
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-21T20:52:00.255Z',mode:absolute,to:'2018-09-21T20:58:00.255Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-21T20:52:00.255Z',mode:absolute,to:'2018-09-21T20:58:00.255Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment] 2018-09-23 17:08
Thank you for your feedback
closing as duplicate of https://github.com/gbif/portal-feedback/issues/1550 as the explanation is the same for both

**Closed by MortenHofft** 2018-09-23 17:08 UTC
Labels: Under review, bug
