### ISSUE TITLE
French version of news item not showing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#432] opened 2017-09-05 10:09 UTC
**French version of news item not showing**

I've created this news item in English and French in Contentful. Having changed my browser language setting to French in Google Chrome, however, I don't see the French version—only the English one. 

The front page does, however, show the French translation of our tagline 'Free and open access to biodiversity data'.

Sorry if I've jumped the gun in thinking that this was working, but I was under the impression that it did.

-----
fbitem-a725a8bc7c32adc38507e46409752f3df12ecf38
User provided contact info: @kcopas
System: Safari 10.1.2 / Mac OS X 10.12.6
Referer: https://www.gbif.org/news/449m6aJi2A6yum2osq4gaS/central-african-republic-becomes-newest-gbif-voting-participant
Window size: width 1604 - height 950
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-05T10:04:03.333Z',mode:absolute,to:'2017-09-05T10:10:03.333Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-05T10:04:03.333Z',mode:absolute,to:'2017-09-05T10:10:03.333Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kcopas** [comment] 2017-09-05 10:10
![home-fr](https://user-images.githubusercontent.com/12379236/30056466-20e401fa-9233-11e7-85de-fb26c7343959.png)

**Comment by kcopas** [comment] 2017-09-05 10:10
Note tagline en français, news item…not so much :-|

**Comment by niconoe** [comment] 2017-09-06 08:34
I can confirm the issue described by @kcopas with latest Chrome and Firefox 55 on Mac OS.

Same problem with Safari 10.1.1, but in that case the tagline stays in English, too. I can't find the  language settings for Safari, but I guess it follows OS settings, which is FR on my laptop.

**Comment by thomasstjerne** [comment] 2017-09-06 08:37
I think this feature is being prepared, but not yet implemented. Currently, only the tagline on the frontpage is translated.

**Comment by MortenHofft** [comment] 2017-09-14 11:14
To summarise our conversation @kcopas - this is working as expected. But that isn't to say that we couldn't change it. Getting the site translated is one among other tasks that we could decide to go forward with. 

Basically we have added a translated homepage based on browser preferences. But menu, articles etc are not ready to be so. So adding a translated news link on the home page would simply link to the english news article since the site as a whole isn't available in french. If you would like the card to be french we can do so, but it would still link to the english article (please let us know if you believe this would be better).

As such this is a duplicate of https://github.com/gbif/portal16/issues/362n "enable translations site-wide".

**Closed by MortenHofft** 2017-09-14 11:14 UTC
Labels: bug, Under review
