### ISSUE TITLE
Institution code BISON

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1959] opened 2019-05-19 13:43 UTC
**Institution code BISON**

It seems odd to attribute this collection of bee specimens to BISON through the institution code—that can't be the case, is it? More likely to be at SI or possibly PWRC…

-----

User provided contact info: @kcopas
System: Safari 12.1.0 / Mac OS X 10.14.4
User: [See in registry](https://www.gbif.org/api/feedback/user/6d21ac1401e98f1768b53f7875415287:2c8cbde5d0706ccea2d91be57be2b19e224246043b2803aecfed81313a8de4de8372253150530ed4ad3f378cff6ac20ba41ccda8ffd9e097c3271ada005ff152)
Referer: https://www.gbif.org/dataset/f519367d-6b9d-411c-b319-99424741e7de
Window size: width 1431 - height 939
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-19T13:38:19.720Z',mode:absolute,to:'2019-05-19T13:44:19.720Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-19T13:38:19.720Z',mode:absolute,to:'2019-05-19T13:44:19.720Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment] 2021-12-08 15:25
Marking as pending to be handled de-centrally at some point.

**Comment by ManonGros** [comment] 2021-12-08 18:43
I think it is fine to close, I am pretty sure this was intentional. The USGS publishes many records with specific institution codes to query records across datasets.

**Closed by ManonGros** 2021-12-08 18:43 UTC
Labels: data content, US, Pending

**Comment by kcopas** [comment] 2021-12-08 18:48
Just to point out, BISON is an invalid collection code. That’s the issue.

It could plausible be attached to the [PWRC institution](https://www.gbif.org/grscicoll/institution/94ffe3ac-89b0-49de-b6fb-601e6e49b8d8), but [this](https://www.gbif.org/grscicoll/institution/4be1a1c8-f981-472e-b2f5-e18af997f9ce) would likely be a better fit for both institution and collection.

**Comment by ManonGros** [comment] 2021-12-08 19:15
I mean to say that the institution code is used for practical purposes. Maybe it would be best to ask @albenson-usgs. Abby, what do you think? Should the dataset keep using BISON as institution code or would it be better to use the codes of the actual hosting institution?

**Comment by AbbyBenson** [comment] 2021-12-08 19:29
I agree with Kyle's assessment and we have discussed changing how we do this going forward. To the best extent possible I will try to get it updated for this dataset during the next update of the dataset. USGS will probably not go back and update all the previous datasets that have this collection code until an update is needed. I think we can close this ticket because the issue is known to USGS and we are working to resolve it but it may take time for all the necessary updates to take place.
