### ISSUE TITLE
broken link in Cluster / occurrence number stability

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#3933] opened 2022-02-14 15:02 UTC
in this cluster https://www.gbif.org/occurrence/2434328928/cluster , there is a broken link https://www.gbif.org/occurrence/3386740302: 

![image](https://user-images.githubusercontent.com/4609956/153888380-ceb48896-0762-44fd-86d0-acc33c088bc4.png)

Questions: 
* why is it broken?
* how stable are the occurrence numbers used in GBIF? Is there a possibility to keep them stable so they can be used as PID?

**Comment by MortenHofft** [comment] 2022-02-15 10:28
I see the broken record belong to a Plazi dataset
https://www.gbif.org/dataset/01962892-5ab4-4828-a43c-838f01b109b6

I would guess that the dataset was republished with new occurrenceIDs and hence breaking the existing GBIF ID. Essentially the IDs in GBIF are as stable as those published. @muttcg can answer in more details on how we strive to maintain stability and when it fails.

**Comment by muttcg** [comment] 2022-02-15 11:56
@MortenHofft thanks, that is correct answer.

GBIF ID is linked to datasetID + occurrenceID, when user changes occurrenceID GBIF links it to new ID.
Records **3386740302** was reserved for:

- dataset **https://www.gbif.org/dataset/01962892-5ab4-4828-a43c-838f01b109b6** 
- record with occurrenceID equal to **https://data.biodiversitydata.nl/naturalis/specimen/RMNH.ARA.15165**

That dataset doesn't have occurrenceID equal to **https://data.biodiversitydata.nl/naturalis/specimen/RMNH.ARA.15165** anymore:

https://www.gbif.org/occurrence/search?dataset_key=01962892-5ab4-4828-a43c-838f01b109b6&occurrence_id=https:~2F~2Fdata.biodiversitydata.nl~2Fnaturalis~2Fspecimen~2FRMNH.ARA.15165&advanced=1

**Comment by gsautter** [comment] 2022-02-15 14:23
Well, the IDs we assign to occurrences (as well as taxa) are a concatenation of treatment UUID and materialsCitation UUID (the latter only in the occurrences), and both those UUIDs derive directly from annotation boundaries (among other things). That means they are stable (and reproducible), but will change when the boundaries of the underlying source annotation change. This is system inherent, and we better not change it.

However, as GBIF issues new record IDs in reaction to UUID changes on our end, we'll import those changes back as well, so any discrepancy is at most temporary, and will usually go away in well below an hour's time.

**Comment by gsautter** [comment] 2022-02-15 14:26
As to the clusters, maybe there is a way of communicating any previous record keys via the DwC-As so it's easy to replace in the clusters proper?

**Comment by ManonGros** [comment] 2022-02-15 15:01
I think the record deleted was published by Naturalis (they have sometimes in the past changed their occurrenceID).

The issue is that we don't run the clustering function very often so the occurrences clustered might have been deleted (or updated) in the meanwhile.

**Comment by MortenHofft** [comment] 2022-02-15 15:59
@ManonGros the missing/broken/deleted record is a Plazi record that is clustered with the (still existing) Naturalis occurrence
![Screenshot 2022-02-15 at 16 56 28](https://user-images.githubusercontent.com/6759267/154099269-69c2aa68-a806-4d11-90f7-acaec3ceefce.png)

Unless I misunderstand

**Comment by timrobertson100** [comment] 2022-02-16 10:59
I've rerun clustering, which is a batch process, to bring consistency again.

As people have noted, stability in IDs is determined by the data publishers. 
I'll shortly put up some issues in [gbif/pipelines](https://github.com/gbif/pipelines) that outline some proposed steps that GBIF can take to help prevent unwittingly changing IDs by requiring a human confirmation, run an ID migration when IDs at the source, and bringing Bionomia annotations into GBIF. These can be released as a package of improvements with communication material to raise the visibility of why ID changes can cause issues.

**Closed as completed by timrobertson100** 2022-02-16 10:59 UTC
