### ISSUE TITLE
Wrong superior taxonomy

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1319] opened 2018-04-24 16:34 UTC
**Wrong superior taxonomy**

This species is a Bird but the superior taxonomy indicates is a Reptile O.o. Which is very problematic when using the species matching or API tools.

-----

User provided contact info: @camiplata
System: Chrome 65.0.3325 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/38a511c36b4cd385e6e1e027d321998c:309e1c1b746645b210e795fff37a672e4ec425751a576967ab79fb36221721e87aa4be0d91af9fb74664d9d99b69f22aaa7b78615e40d6e428c10d1643c9cfb2)
Referer: https://www.gbif.org/species/2481113
Window size: width 1440 - height 834
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-24T16:29:09.913Z',mode:absolute,to:'2018-04-24T16:35:09.913Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-24T16:29:09.913Z',mode:absolute,to:'2018-04-24T16:35:09.913Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by thomasstjerne** [comment] 2018-04-25 06:32
Closing as duplicate of #1213

**Closed by thomasstjerne** 2018-04-25 06:32 UTC
Labels: Under review, data content
