### ISSUE TITLE
Can't change the custom style in full screen mode

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#320] opened 2017-08-15 13:35 UTC
**Can&#39;t change the custom style in full screen mode**

Hello,

I can’t change the base map or the binning  or the color when I’m in the custom style and in full screen of the map on the main page.

I&#39;m using Chrome (Version 60.0.3112.90) and Mac OS X El Capitan.

Best regards,
Marie-Elise

-----
fbitem-67cbf865735ab20856e1e6649eab1c4073bc341e
Reported by: melecoq@gbif.fr
System: Chrome 60.0.3112 / Mac OS X 10.11.6
Referer: https://www.gbif-uat.org/
Window size: width 1276 - height 622
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T13:30:32.714Z',mode:absolute,to:'2017-08-15T13:36:32.714Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T13:30:32.714Z',mode:absolute,to:'2017-08-15T13:36:32.714Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment] 2017-08-15 13:43
Indeed not. Thank you. 
I know why, but not how to fix it. We will look at it. Thanks.

For developers:
The issue is 'Material design' libraries very low z-indices that conflict with our general site indices.

**Comment by MortenHofft** [comment] 2017-08-15 16:12
Should be fixed and on [UAT](https://www.gbif-uat.org/). 
Thank you for reporting it.

**Closed by MortenHofft** 2017-08-15 16:12 UTC
Labels: bug, portal
