### ISSUE TITLE
How do I download data?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#34] opened 2017-01-12 17:53 UTC
**How do I download data?**

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482

System: Chrome 55.0.2883 / Windows 7 0.0.0
Referer: https://demo.gbif.org/occurrence/search?institution_code=aadc&amp;institution_code=nzf&amp;institution_code=clo&amp;institution_code=inaturalist&amp;institution_code=nhmuk&amp;institution_code=nmr&amp;institution_code=gnm&amp;institution_code=usnm&amp;taxon_key=2440483
Window size: width 1366 - height 638
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-12T17:48:25.915Z',mode:absolute,to:'2017-01-12T17:54:25.915Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-12T17:48:25.915Z',mode:absolute,to:'2017-01-12T17:54:25.915Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment] 2017-01-13 07:55
You cannot at this point. We are still in development. But rest assured you will be able to. For now you need to use the old portal. Thank you for your interest.

This issue is a duplicate of the not implemented issue https://github.com/gbif/portal16/issues/63 

> no contact info present

**Closed by MortenHofft** 2017-01-13 07:55 UTC
Labels: duplicate, portal
