### ISSUE TITLE
ABCD-Element Multimediaobject/Creator not harvested

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#485] opened 2017-09-25 09:47 UTC
**ABCD-Element Multimediaobject/Creator not harvested**

Dear GBIF team,

the provider of the record https://www.gbif.org/occurrence/1563155655  just pointed out that the creator of the image attached to that occurrence does not show up on the portal. Apparently the ABCD element MutlimediaObject/Creator is not being harvested.

Would it be possible to add this element to the harvester, so that the photographer gets attributed properly?

Thanks and best wishes,
Jörg Holetschek

-----
fbitem-occurrence1563155655
User provided contact info: jholetschek
System: Firefox 55.0.0 / Windows 7 0.0.0
Referer: https://www.gbif.org/occurrence/1563155655
Window size: width 1617 - height 940
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-25T09:42:25.903Z',mode:absolute,to:'2017-09-25T09:48:25.903Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-25T09:42:25.903Z',mode:absolute,to:'2017-09-25T09:48:25.903Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: e5774d90-9f01-42bb-a747-32331be82b18
publishingOrgKey: c76cf030-2a95-11da-9cc1-b8a03c50a862

**Comment by MortenHofft** [comment] 2017-09-26 10:48
from verbatim
```
"extensions": {
"http://rs.gbif.org/terms/1.0/Multimedia": [
{
"http://purl.org/dc/terms/identifier": "http://www.westafricanplants.senckenberg.de/images/pictures/brachycorythis_friesiiwamccl_1850_7587_13a4f7.jpg",
"http://purl.org/dc/terms/format": "jpg",
"http://purl.org/dc/terms/license": "All rights reserved",
"http://purl.org/dc/terms/description": null,
"http://purl.org/dc/terms/references": null
}
]
},
```

**Comment by marcoschmidtffm** [comment] 2017-11-09 09:04
Dear @MortenHofft , I better add a few infos, please have a look at this again:

The problem is, that for the whole dataset "African Plants - a photo guide" [https://doi.org/10.15468/r9azth] the photographers are not mentioned on GBIF, although we matched the respective field from our database with the ABCD element "Creator".

See an example on [(http://biocase.senckenberg.de/querytool/raw.cgi?dsa=africanplants&filter=(inst=FR)AND(col=sgn_africanplants)AND(cat=9024)&schema=http://www.tdwg.org/schemas/abcd/2.06&wrapper_url=http://biocase.senckenberg.de//pywrapper.cgi?dsa=africanplants)]

So, why do the photographers not appear on GBIF? Is it a problem in providing our data, is e.g. the "creator" not correctly embedded in the XML or is it a problem of harvesting / interpreting our data on the GBIF side? What do we need to do to improve this?

Best wishes,
Marco

**Comment by mdoering** [comment] 2017-11-09 09:29
It is not transferred from ACBD to DwC, see gbif/portal-feedback#189 for sth similar in geological terms. You can see it in the _raw_ data: https://api.gbif.org/v1/occurrence/1563155655/fragment

which has this multimedia object with a funny license ;)
```
		<MultiMediaObject>
			<FileURI>http://www.westafricanplants.senckenberg.de/images/pictures/brachycorythis_friesiiwamccl_1850_7587_13a4f7.jpg</FileURI>
			<Format>jpg</Format>
			<IPR>
				<Licenses>
					<License language="EN">
						<Text>All rights reserved</Text>
						<Details>TERM OF USE !!!!! NOCH NICHT</Details>
					</License>
				</Licenses>
			</IPR>
			<Creator>Warren McCleland</Creator>
		</MultiMediaObject>

```

**Comment by jlegind** [comment] 2021-10-05 07:15
Seems to have been fixed:
https://www.gbif.org/occurrence/1563155655

Image text:
>Creator: Warren McCleland
Record licence All rights reserved; for terms and conditions see http://www.africanplants.senckenberg.de/root/index.php?page_id=84
Identifier http://www.westaf...0_7587_13a4f7.jpg

One final note on the image text - 'licence' is spelled wrong. It is 'license'.

**Closed by jlegind** 2021-10-05 07:15 UTC
Labels: bug, api

**Comment by marcoschmidtffm** [comment] 2021-10-05 10:39
Thank you! Good to know that it works now. I believe the "licence" comes from the wrapper or GBIF-DE, but it seems to be the correct spelling on this side of the Atlantic.

Best wishes,
Marco

**Comment by MattBlissett** [comment] 2021-10-05 10:50
We (of course!) would accept either spelling, but in our own material we use the noun _licence_ as we follow "UN English" spelling.

https://www.un.org/dgacm/en/content/editorial-manual/spelling#l
