### ISSUE TITLE
I can`t register

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#177] opened 2017-04-25 04:38 UTC
**I can`t register**

The page dosen`t let me register a mew acount

-----
fbitem-8b16037cf12b5f958bf6d374db1c1429764c1b51

System: Chrome 57.0.2987 / Windows 7 0.0.0
Referer: https://demo.gbif.org/occurrence/download
Window size: width 1366 - height 676
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-25T04:33:04.120Z',mode:absolute,to:'2017-04-25T04:39:04.120Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-25T04:33:04.120Z',mode:absolute,to:'2017-04-25T04:39:04.120Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment] 2017-04-27 16:23
Duplicate of #180.

**Closed by MattBlissett** 2017-04-27 16:23 UTC
Labels: bug, Under review
