### ISSUE TITLE
treatments not complete: https://www.gbif.org/species/193383510

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#3982] opened 2022-03-18 15:03 UTC
In this treatment in GBIF, https://www.gbif.org/species/193383510, only part of the treatment is shown (see [source:](https://treatment.plazi.org/id/CA74DB9BD4CCA365FAC9FE2A9F2A4602) that is available in TB and the original publication.

![image](https://user-images.githubusercontent.com/4609956/159028101-f6f24ce8-b34b-42b7-a661-0031d712f164.png)

Could this be because of the types of the subSubSection?

**Comment by thomasstjerne** [comment] 2022-03-21 09:02
Duplicate of https://github.com/gbif/checklistbank/issues/215 (failure to add EOL media extension to the database)

**Closed as completed by thomasstjerne** 2022-03-21 09:02 UTC
