### ISSUE TITLE
no clas

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4512] opened 2023-01-07 18:20 UTC
**no clas**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/f761758f3e108d437d8f9544a07a4cb0:e003258d8e34161e07f36e79ae45a5235016a1e11e68e041ad61b46c23bc5b0c6860d08f101635c13a3c39ce0fa25894dfce735812a8012e9e71be7a282e6fe06bb2b1d91d32b4b26f95cfa84932c3bd02eecdc9dcaae397389bc0c02394b603) - [Send email](https://www.gbif.org/api/feedback/user/mailto/f761758f3e108d437d8f9544a07a4cb0:e003258d8e34161e07f36e79ae45a5235016a1e11e68e041ad61b46c23bc5b0c6860d08f101635c13a3c39ce0fa25894dfce735812a8012e9e71be7a282e6fe06bb2b1d91d32b4b26f95cfa84932c3bd02eecdc9dcaae397389bc0c02394b603)
System: Chrome 108.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/search?has_coordinate=true&has_geospatial_issue=false&taxon_key=2371221&geometry=POLYGON((-65.32922%20-0.50917,-65.01585%20-0.49188,-64.94018%20-0.25428,-65.33018%20-0.26911,-65.32922%20-0.50917))&occurrence_status=present
Window size: width 2560 - height 1329
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-07T18:15:18.289Z',to:'2023-01-07T18:21:18.289Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-07T18:15:18.289Z',to:'2023-01-07T18:21:18.289Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment] 2023-01-09 07:20
duplicate of https://github.com/gbif/portal-feedback/issues/4513

**Closed as completed by ManonGros** 2023-01-09 07:20 UTC
Labels: question, Under review
