### ISSUE TITLE
ES: Spanish unfinished priority 1 translations

### ISSUE THREAD

**Issue by akristensen** [gbif/portal-feedback#1800] opened 2019-02-25 13:20 UTC
- [x] [Contacts](https://www.gbif.org/es/contact-us)

**Comment by akristensen** [comment] 2019-02-26 12:53
Thank you @WUlate

**Comment by akristensen** [comment] 2019-02-28 12:42
related bug https://github.com/gbif/portal-feedback/issues/1802

**Comment by MortenHofft** [comment] 2019-03-05 11:22
closed as duplicate of https://github.com/gbif/portal-feedback/issues/1802

**Closed by MortenHofft** 2019-03-05 11:22 UTC
Labels: Translation, bug, portal

**Comment by akristensen** [comment] 2019-03-05 11:23
Tak @MortenHofft
