### ISSUE TITLE
dates in table list

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1538] opened 2018-09-06 15:31 UTC
**dates in table list**

This record (occurrence id 746bbe1c-8f71-4360-a683-9f9e8d75b03a) was originally provided with a date corresponding only to a year (2015). But when viewing the result of a search, in table view, it shows 'month & year' column as '2015 January'. 'January' is not correct, it should be omitted.

-----

System: Firefox 61.0.0 / Mac OS X 10.13.0
User: [See in registry](https://www.gbif.org/api/feedback/user/334c234b63e4ac1bb71a53071578906f:2665076a506f2ed121963cd7fbf52d19f71a930c1293b457a0baed50b526c93e00d4b15cdacb0158808f63d944ae7c443673f1575ab4d9d64f4a46acdc5ba410)
Referer: https://www.gbif.org/occurrence/1675313098
Window size: width 1440 - height 733
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-06T15:26:27.966Z',mode:absolute,to:'2018-09-06T15:32:27.966Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-06T15:26:27.966Z',mode:absolute,to:'2018-09-06T15:32:27.966Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment] 2018-09-19 08:36
Duplicate of https://github.com/gbif/gbif-api/issues/4

Closing as this adds no additional information.

**Closed by MattBlissett** 2018-09-19 08:36 UTC
Labels: api, bug
