### ISSUE TITLE
Map Leyend

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1445] opened 2018-07-13 11:05 UTC
**Map Leyend**

Hi! 
Where is the map legend when you do a query about a specie? 
What is the meaning of yellow, orange and red colors? 
Thanks

-----

User provided contact info: herbariomgc@uma.es
System: Chrome 67.0.3396 / Windows 8.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/674f120e49a4db86a7b5614607cfb80d:43ab17ec078a8964722f71ec69bcb03ae62abab60054b8f52a5718a4b7220b11112a24381cd56caa0f131e1ff7da962991c4d078b0303b2ef4eed771c3e4fb7b)
Referer: https://www.gbif.org/species/5358460
Window size: width 1184 - height 747
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-13T11:00:20.157Z',mode:absolute,to:'2018-07-13T11:06:20.157Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-13T11:00:20.157Z',mode:absolute,to:'2018-07-13T11:06:20.157Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment] 2018-07-13 11:44
god point. Duplicate of https://github.com/gbif/portal-feedback/issues/563

**Closed by MortenHofft** 2018-07-13 11:44 UTC
Labels: Under review, data content
