### ISSUE TITLE
Problem with GBIF backbone taxonomy data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3617] opened 2021-09-28 15:45 UTC
**Problem with GBIF backbone taxonomy data**

Hello,
I wanted to import GBIF backbone taxonomy from https://hosted-datasets.gbif.org/datasets/backbone/ 
I downloaded “backbone-current-simple.txt.gz” file. I was able to import it, but I didn’t find details about the meaning of each column.
For example, I thought that  column  “u.id” was a unique key for each taxon. And “u.parent_fk”  indicated the “parent” taxon of a taxon. But I detected that not all values of “u.parent_fk”   appear in “u.id”, so some taxons seems to not have parent (for example some genuses).
Where can I find more detailed information in order to  properly understand those data and be able to reconstruct the taxonomic tree?
Thank you very much.
E. Garcia
University of Vigo
Spain

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/3f8ad0a28219d63f4d01b63cb1892a30:a9105d5b94a386c7c810b6b350630fe636b1ae1a8224d323c2ad03caf8c440652cd9b1c7120ac12984f5ccfbe53f8e79b4ae408bed584dbb4cc4754c61b3b7be)
System: Chrome 94.0.4606 / Windows 10.0.0
Referer: https://www.gbif.org/es/user/profile
Window size: width 1280 - height 615
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-28T15:40:23.928Z',to:'2021-09-28T15:46:23.928Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-28T15:40:23.928Z',to:'2021-09-28T15:46:23.928Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment] 2021-10-04 12:43
duplicate of https://github.com/gbif/portal-feedback/issues/3618

**Closed as completed** 2021-11-09 13:07 UTC
Labels: Under review, data content
