### ISSUE TITLE
Missing participant country information: demo site vs old site

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#185] opened 2017-05-09 08:04 UTC
**Missing participant country information: demo site vs old site**

I noticed that it’s starting to get confusing which website to reference for certain information. I was checking on participation info for Niger. No contact information appears on the old site, http://www.gbif.org/country/NE/participation but we can see a limited amount on the demo website since the email and other contact info pop up (email icon) is still not functional -https://demo.gbif.org/country/NE. 
 
Just to contrast, I looked at Nigeria which became a GBIF participant a month before Niger and all participation information including full contact info where available can be seen on the old website -http://www.gbif.org/country/NG/participation
On the demo website, only part of the contact information available on the old website can be seen -https://demo.gbif.org/country/NG#contacts

I checked with Kyle C and he gave me the following reply:
&#39;The back-end migration is complete, but we&#39;ve temporarily lost the network page (expected) and have a bug on country pages (not expected). Argentina works, Russia and Niger do not. Morten is aware of the issue and working to resolve it, I believe.&#39;

I don’t know the timeline for the new website to replace the old one but if that’s not going to be very soon, it will be a good idea to update the info about Niger, etc to also appear on the old website so that the full contact information can be seen.

-----
fbitem-858c3c82d89a251b014dafb4c8096750f6681b30
Reported by: @siro1
System: Chrome 57.0.2987 / Windows 10 0.0.0
Referer: https://demo.gbif.org/country/NE
Window size: width 1348 - height 660
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-05-09T07:59:07.962Z',mode:absolute,to:'2017-05-09T08:05:07.962Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-05-09T07:59:07.962Z',mode:absolute,to:'2017-05-09T08:05:07.962Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment] 2017-05-16 12:20
Hi Siro - I'm not sure I understand all of the above. But as Kyle mentioned there was a bug that is now fixed. But I'm not sure that is the issue you are referring to. I'm closing this as I cannot reproduce what i think you mention, but please reopen if you still see the issue.

**Closed by MortenHofft** 2017-05-16 12:20 UTC
Labels: bug, Under review
