### ISSUE TITLE
I recently searched your platform for Selaginella salazariae Valdespino and found you had it listed as  "nom. illeg., non Cordem. (1890)." This is incorrect. I consulted Drs. W. Werner and N.Thurland, amply known for their knowledge of the ICB and they basically said Selaginella salazariae and S. salarian are not homonym. Below is an extract of what both basically said:

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3581] opened 2021-09-08 15:50 UTC
**I recently searched your platform for Selaginella salazariae Valdespino and found you had it listed as &quot;nom. illeg., non Cordem. (1890).&quot; This is incorrect. I consulted Drs. W. Werner and N.Thurland, amply known for their knowledge of the ICB and they basically said Selaginella salazariae and S. salarian are not homonym. Below is an extract of what both basically said:**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a6da82bc2c85143b2d3e9b2686a05e06:af295e8484b4aad95e9be818912ec859fc6283b148c004329489a5cb8c8f4f3c0171a6b327a0f1a173fa2e0c07c5c72f18871938c071f6bfe82118c72f17ef58)
System: Safari 14.1.2 / Mac OS X 10.15.7
Referer: https://www.gbif.org/user/confirm
Window size: width 1395 - height 739
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-08T15:45:39.730Z',to:'2021-09-08T15:51:39.730Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-08T15:45:39.730Z',to:'2021-09-08T15:51:39.730Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment] 2021-09-23 07:09
Duplicate of https://github.com/gbif/backbone-feedback/issues/372

**Closed as completed by ManonGros** 2021-09-23 07:09 UTC
Labels: Under review, data content
