### ISSUE TITLE
Two large datasets are not correctly interpreted in the portal

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/portal-feedback#4233] opened 2022-09-01 21:12 UTC
Hi, we have a problem with two large datasets. We published them through our IPT without problem, but when they get indexed in GBIF the information jump from one element to the next one and because of that we get a lot of interpretation problems.
![image](https://user-images.githubusercontent.com/63795703/188010325-96678034-0496-4eca-9b65-59284cd4b071.png)

The data gets correctly interpreted in the data validator [EPM-Epifitas](https://www.gbif.org/tools/data-validator/fc5422b1-2ac8-4bb8-928e-4c9a2a006198).

When I download the data from our [IPT](https://doi.org/10.15472/hypxxw) the data looks fine, so I think the problem is in the interpretation.

And we did a test in the GBIF IPT for gbif-uat and there it is correctly interpreted [UAT-Rescate y reubicación de Epífitas](https://www.gbif-uat.org/dataset/f5c8f424-d6dd-4575-80a7-f277131723ad)! It is the same archive, so we do not know why it works here but not in production.

The two datasets are:
- [Rescate y reubicación de Epífitas en el área del vaso del embalse del Proyecto Hidroeléctrico Ituango](https://www.gbif.org/dataset/1fcfeecb-3899-4d59-8c3a-881ffec9d725)
- [Aprovechamiento Forestal en el área de influencia del Proyecto Hidroeléctrico Ituango
](https://www.gbif.org/dataset/f65b3120-1fab-4f2d-abbb-49d072bf1016)

We reach you out because we run out of ideas. Thanks in advance

**Comment by ManonGros** [comment] 2022-09-02 08:00
@EstebanMH-SiB I don't know why this issue occurred but I re-ingested the datasets and now it is consistent with what is on UAT.

**Comment by CecSve** [comment] 2022-09-09 11:15
It seem like the issue is fixed so I will go ahead and close the issue.

**Closed as completed by CecSve** 2022-09-09 11:15 UTC
Labels: question, data validator, interpretation
