### ISSUE TITLE
Authority for new species is incorrect

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3916] opened 2022-02-08 18:54 UTC
**Authority for new species is incorrect**

The authority for this new species was published as:

Neuroterus valhalla Brandão-Dias, Zhang, Weinersmith, Forbes & Egan

..whereas what is expressed here is merely:

Neuroterus valhalla Brandão

-----

Github user: @dshorthouse
User: [See in registry](https://www.gbif.org/api/feedback/user/8fbd3b080527ffb475d771ccd1e7f34d:85c96f9038de82f840d4034353ea0c8b30d350bf5d03b7e8a469b10b08e59eb4db45d6664c06ee90a456c3d4af32647d8d89408387fb44484128023dffaa99da5c52105e66331d97e8cd264c7783a2ca)
System: Chrome 98.0.4758 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/192604755
Window size: width 1624 - height 894
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-08T18:49:12.543Z',to:'2022-02-08T18:55:12.543Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-08T18:49:12.543Z',to:'2022-02-08T18:55:12.543Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment] 2022-02-09 08:16
@thomasstjerne the verbatim scientific name provided by the PLAZI treatment is `Neuroterus valhalla Brandão‐Dias & Zhang & Weinersmith & Forbes & Egan 2022` (https://www.gbif.org/species/192604755/verbatim) but we display only `Neuroterus valhalla Brandão`. Could you take a look?

**Comment by ahahn-gbif** [comment] 2022-04-27 12:43
The [name parser](https://www.gbif.org/tools/name-parser) translates the scientific name that it receives from the [source](https://www.gbif.org/species/192604755/verbatim). The syntax of the author team (using multiple & characters) is unexpected and against common practice. We would expect an author team with multiple contributors to separate entries with commata, and adding a & only between the last two names. Exploring with Plazi (the data mediator) whether this is intentional and/or can be changed.

**Comment by ahahn-gbif** [comment] 2022-05-06 14:40
See my comment in the linked issue plazi/community#150: the parsing error is not caused by the ampersands in the author team, but rather by a dash-impersonating character in the double name at the start (Brandão-Dias). Name parsing breaks off at that point. Replacing the dash leads to the expected parsing result. Should we consider to strip/replace suspected control-characters like this, also in name processing @mdoering, or is this an edge case we prefer to fix at source?

**Comment by ahahn-gbif** [comment] 2022-05-09 06:57
Apparently replacing a Unicode hyphen (0x2010) with an ASCII minus (0x002D) in the source data corrects this issue. Closing.

**Closed as completed by ahahn-gbif** 2022-05-09 06:57 UTC
Labels: backbone
