### ISSUE TITLE
pre-DOI download doesn't show contributing datasets

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1016] opened 2018-02-05 12:50 UTC
**pre-DOI download doesn&#39;t show contributing datasets**

It says 76 datasets and number of records, however, the titles aren't shown

-----
fbitem-805882ba93997bbde6a01139ba5cced287841a9b
User provided contact info: @dnoesgaard
System: Chrome 63.0.3239 / Mac OS X 10.13.2
Referer: https://www.gbif.org/occurrence/download/0006796-141123120432318
Window size: width 1440 - height 666
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-05T12:45:27.562Z',mode:absolute,to:'2018-02-05T12:51:27.562Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-05T12:45:27.562Z',mode:absolute,to:'2018-02-05T12:51:27.562Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment] 2018-02-05 14:22
We looked at this or a similar dataset previously. I cannot find the issue though, so maybe it was never created. No some downloads seem to be broken that way. the API don't return in the same format as other downloads in this case. Labelling as API issue.

**Comment by MattBlissett** [comment] 2018-11-21 14:40
Duplicate of #697

**Closed by MattBlissett** 2018-11-21 14:40 UTC
Labels: api, bug
