### ISSUE TITLE
This sheet is not a cookie sheet

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2083] opened 2019-07-09 23:08 UTC
**This sheet is not a cookie sheet**

A few notes to self in scientificName is tolerable. 410,000+ of them not so much.

-----

User provided contact info: @dshorthouse
System: Chrome 75.0.3770 / Mac OS X 10.14.5
User: [See in registry](https://www.gbif.org/api/feedback/user/b6b98acc1a951fd3afa90d65c84f8c03:3aafe7c92d540abc8b3619a8964b447f9d556c8aa98e3c63718b95dcd6c86542edda186bd56fbc2d466d1c9ad61b0c8ce5204d4c9a7c9b68e3f2506c5140a35bbcc6e6ae2fc489527ea97bcbb793d492)
Referer: https://www.gbif.org/occurrence/search?q=Cette%20Fiche
Window size: width 1428 - height 699
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-09T23:03:00.455Z',mode:absolute,to:'2019-07-09T23:09:00.455Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-09T23:03:00.455Z',mode:absolute,to:'2019-07-09T23:09:00.455Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment] 2019-07-10 08:09
I agree, although it is 21,258 from the dataset "The cryptogamy collection (PC) at the Herbarium of the Muséum national d'Histoire Naturelle (MNHN - Paris)".

The any-word search searches for either *Cette* or *Fiche*, and (as far as I can see) doesn't search the original, verbatim scientific name anyway. The former we know about, the latter seems like a potential oversight.

**Comment by ManonGros** [comment] 2019-07-22 13:51
https://github.com/gbif/portal-feedback/issues/2069

**Comment by ManonGros** [comment] 2019-07-22 14:11
Yes exactly, most of the records are appearing in the search because they contain the words "cette" or "fiche" ([for example](https://www.gbif.org/occurrence/1950174654): `Event remarks: Fiche de LUXNAT`.)

I will contact the MNHN the 20K records in the PC collection.

**Comment by ahahn-gbif** [comment] 2019-08-01 12:36
PC collection (https://www.gbif.org/dataset/fea77396-7b26-44cb-8580-aefadc8db276): received email via hd from Aug 1, 2019; confirmed fixed

**Comment by ahahn-gbif** [comment] 2019-08-01 12:39
This issue appears to be fixed now. Please reopen if this not the case.

**Closed by ahahn-gbif** 2019-08-01 12:39 UTC
Labels: Pending, data content
