### ISSUE TITLE
dead link: Identifiers 10.15468/ksxtyj

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1214] opened 2018-02-28 16:56 UTC
**dead link: Identifiers 10.15468/ksxtyj**

Reported by Donat Agosti.
the DOI links to this dataset page, guess the link is badly generated? the EML just has <alternateIdentifier>10.15468/ksxtyj</alternateIdentifier>

Related to recent DOI API class changes?

-----

System: Chrome 64.0.3282 / Mac OS X 10.13.3
User: [See in registry](https://www.gbif.org/api/feedback/user/1fbf6c5de63814f33126a0cac24063d3:53d1a972673d78e5a8fcda7eebb9942d28571d801f5c7c8cb154256cce381df2748a0203459443e7f64ed0eb2647edf826c23ad87be6f7de777290c98a515eb6)
Referer: https://www.gbif.org/dataset/9103f07a-5514-40f7-8624-b81b7a04510a
Window size: width 1680 - height 892
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-28T16:51:40.561Z',mode:absolute,to:'2018-02-28T16:57:40.561Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-28T16:51:40.561Z',mode:absolute,to:'2018-02-28T16:57:40.561Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment] 2018-02-28 17:36
NB this is the GBIF-assigned DOI, which should be listed, but not emphasized. The dataset has its own, non-GBIF DOI which is shown at the top of the page.

**Comment by MortenHofft** [comment] 2018-02-28 18:08
duplicate of https://github.com/gbif/portal-feedback/issues/735#issuecomment-364484805 . Introduced by https://github.com/gbif/portal16/commit/c3e875314bf1d06299bf19cb18319145ff7ddb9f

**Comment by dnoesgaard** [comment] 2018-03-07 08:55
Regarding consistency of DOIs, note these guidelines from Crossref and Datacite: https://www.crossref.org/display-guidelines/
https://support.datacite.org/docs/datacite-doi-display-guidelines

Being schooled in certain citation styles, I'm myself guilty of writing DOIs like doi:10.15468/xyz, but we should definitely follow the above mentioned URL style:

> DOIs should always be displayed as a complete URL using the form:
> https://doi.org/10.7939/r3qz22k64

**Comment by MattBlissett** [comment] 2018-03-07 09:17
Perhaps it would be best if we had this:

**Endpoints:** ...
**Preferred identifier:** https://doi.org/10.5852/ejt.2018.405
**Alternative identifiers:** https://doi.org/10.15468/ksxtyj

At the moment, it's not clear to someone looking at the bottom of the page that the alternative DOI isn't the one they should use.

**Closed** 2018-03-08 15:18 UTC
Labels: bug, portal
