### ISSUE TITLE
Vulpes vulpes matched to higher taxon

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1025] opened 2018-02-07 18:28 UTC
**Vulpes vulpes matched to higher taxon**

Vulpes vulpes for occurrence https://www.gbif.org/occurrence/1802769642 gets matched to the genus `Vulpes Frisch, 1775` https://www.gbif.org/species/5219234

Why not to the valid species `Vulpes vulpes (Linnaeus, 1758)`
https://www.gbif.org/species/5219243

-----
fbitem-occurrence1802769642
User provided contact info: @peterdesmet
System: Chrome 63.0.3239 / Mac OS X 10.13.3
Referer: https://www.gbif.org/occurrence/1802769642
Window size: width 1298 - height 736
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-07T18:23:41.767Z',mode:absolute,to:'2018-02-07T18:29:41.767Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-07T18:23:41.767Z',mode:absolute,to:'2018-02-07T18:29:41.767Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by mdoering** [comment] 2018-02-07 20:12
duplicate of https://github.com/gbif/checklistbank/issues/42

**Closed by mdoering** 2018-02-07 20:12 UTC
Labels: Under review, data content
