### ISSUE TITLE
The genus Nothocricetulus is listed as Valid in GBIF  https://www.gbif.org/ru/species/141263862

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3807] opened 2021-12-09 19:44 UTC
**The genus Nothocricetulus is listed as Valid in GBIF `https://www.gbif.org/ru/species/141263862`**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d20178cb43eb03225fd8a43fedc8ac3b:b41e580ccdfc02a9098d687a0be1051fe2dc8b05f16f8aef8c9a1a227c7c4fa79a5fd17c17203973a8109b3526d59dd1d1ee31c0096fbaad52842fd6903fcc46)
System: Opera 81.0.4196 / Windows 10.0.0
Referer: https://www.gbif.org/tools/data-validator/1638898791481
Window size: width 1640 - height 909
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-09T19:39:06.036Z',to:'2021-12-09T19:45:06.036Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-09T19:39:06.036Z',to:'2021-12-09T19:45:06.036Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment] 2021-12-10 08:28
Duplicate of: https://github.com/gbif/backbone-feedback/issues/317

**Closed as completed by ManonGros** 2021-12-10 08:28 UTC
Labels: Under review, data content
