### ISSUE TITLE
The dataset of the publisher iNaturalist.org are not in the download included if your filter includes a specific continent.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3620] opened 2021-09-29 09:17 UTC
**The dataset of the publisher iNaturalist.org are not in the download included if your filter includes a specific continent.**

When you first filter for a specific continent then the dataset doesn't contain the data from the publisher iNaturalist.org

Even if you only filter on the website you can see if you filter for the publisher iNaturalist.org that if you add a specific continent you get zero occurences.

Reference: https://www.gbif.org/occurrence/download/0328735-200613084148143

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ecb818918f3f67096af6f49b75f835c4:1908168b52c369144a3c54d3e22212f871334b6b9928d0fbe49c0b5dd7fba1d6c2a8a512c5a4578cda81d54db97e74fae0ded5032908c6060cba331f2e916d40)
System: Firefox 92.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?publishing_org=28eb1a3f-1c15-4a95-931a-4af90ecb574d
Window size: width 1536 - height 739
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-29T09:12:03.981Z',to:'2021-09-29T09:18:03.981Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-29T09:12:03.981Z',to:'2021-09-29T09:18:03.981Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment] 2021-10-04 12:41
duplicate of https://github.com/gbif/portal-feedback/issues/3580

**Comment by MattBlissett** [comment] 2023-01-13 09:18
This is now implemented: https://www.gbif.org/occurrence/search?continent=EUROPE&dataset_key=50c9509d-22c7-4a22-a47d-8c48425ef4a7

**Closed as completed by MattBlissett** 2023-01-13 09:18 UTC
Labels: bug, Under review, interpretation
