### ISSUE TITLE
The media type filter is not visible

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5394] opened 2024-07-22 15:18 UTC
**The media type filter is not visible**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4f32650da4c14e20ca1ea836629cfbbf:c30e045385522396be6c0be2c39778806f9affb44a658e3839a9828847fa72071b7f3819a7c7e179ee5d173d69dd245d378e27a2dff1c5a43e86bf3836b07abbf12fb692d12834735ec83e2c76dfb92450a71949067bfe228b7d9e2963bd58fb) - [Send email](https://www.gbif.org/api/feedback/user/mailto/4f32650da4c14e20ca1ea836629cfbbf:c30e045385522396be6c0be2c39778806f9affb44a658e3839a9828847fa72071b7f3819a7c7e179ee5d173d69dd245d378e27a2dff1c5a43e86bf3836b07abbf12fb692d12834735ec83e2c76dfb92450a71949067bfe228b7d9e2963bd58fb)
System: Chrome 126.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search
Window size: width 1278 - height 1257
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-07-22T15:13:34.194Z',to:'2024-07-22T15:19:34.194Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-07-22T15:13:34.194Z',to:'2024-07-22T15:19:34.194Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment] 2024-07-29 09:44
close as duplicate of https://github.com/gbif/portal-feedback/issues/5395

**Closed as completed by MortenHofft** 2024-07-29 09:44 UTC
Labels: bug, Under review
