### ISSUE TITLE
Misinformation shown for last successful crawl

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#620] opened 2017-10-30 15:38 UTC
**Misinformation shown for last successful crawl**

The dataset page shows the last successful crawl date was 8 September 2017 with crawl response "NOT_MODIFIED".

But this dataset has never been crawled successfully. It has no "NORMAL" crawl response recorded, ever as can be seen here:

https://registry.gbif.org/web/#/dataset/1c714c57-da3e-457e-9752-edd1cd5e0463/crawl

I recognise the root of the error is likely in the crawler, but until the crawler gets fixed perhaps it's worth scanning for at least 1 "NORMAL" crawl before saying it ever crawled successfully?

-----
fbitem-dataset1c714c57-da3e-457e-9752-edd1cd5e0463
User provided contact info: kbraak
System: Firefox 56.0.0 / Mac OS X 10.10.0
Referer: https://www.gbif.org/dataset/1c714c57-da3e-457e-9752-edd1cd5e0463
Window size: width 1248 - height 1184
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-30T15:33:14.586Z',mode:absolute,to:'2017-10-30T15:39:14.586Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-30T15:33:14.586Z',mode:absolute,to:'2017-10-30T15:39:14.586Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment] 2017-10-31 08:11
Thanks @kbraak 
My misunderstanding then. I thought a crawling finished with NOT_MODIFIED was a success. Just that the data hadn't changed. Is this a misunderstanding? Is NOT_MODIFIED a crawling failure?

**Comment by timrobertson100** [comment] 2017-10-31 08:34
This issue is a duplicate of https://github.com/gbif/crawler/issues/8

NOT_MODIFIED means that the crawler has determined through an `HTTP HEAD` request that the file on the target webserver is no newer than the stored version on the file system.

In this case the file has not been modified.  However, the file is invalid (null IDs for all rows) so no records exist.  

For the UI, I'd suggest not showing any crawl history for a dataset with 0 records.

**Comment by MortenHofft** [comment] 2017-10-31 09:28
In that case I don't agree that it is misinformation. It is correct that it is the last successful crawl date. But I agree that it is useful to know when it was last crawled with changes (NORMAL). I have added that information https://github.com/gbif/portal16/commit/52dd42ade34951b1d70798a8032ac7636edd4e93

**Closed by MortenHofft** 2017-10-31 09:28 UTC
Labels: bug, portal
