### ISSUE TITLE
how can I chnage teh email?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2328] opened 2019-12-08 08:25 UTC
**how can I chnage teh email?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7ce3a34ea6d41aabfa4a8e357ad45d99:a3924767b26735f9edabd70290b1ed3614596fb0c85d5bdfba58fb2190f9dbbc10897e32d6e537832bcffdf0dff9b83c127c4a80602b99aec0c80315b1bc1343)
System: Firefox 70.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/faq?q=email%20change
Window size: width 1280 - height 566
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-08T08:20:43.993Z',mode:absolute,to:'2019-12-08T08:26:43.993Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-08T08:20:43.993Z',mode:absolute,to:'2019-12-08T08:26:43.993Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment] 2019-12-09 08:26
duplicate of https://github.com/gbif/portal-feedback/issues/2330

**Closed by ManonGros** 2019-12-09 08:26 UTC
Labels: AT, Under review, question
