### ISSUE TITLE
Wrong superior taxonomy

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1320] opened 2018-04-24 16:35 UTC
**Wrong superior taxonomy**

This species is a Bird but the superior taxonomy indicates is a Reptile. Which is very problematic when using the species matching or API tools.

-----

User provided contact info: @camiplata
System: Chrome 65.0.3325 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/1167e30cb996b6a030ffada05aedd0de:2a8c401a795b6d0e4e1a84b99b5b52da0a3402ec73d4d8b1d2a03ce789d599eaca86c63cea09cd829da85505229111533695508238c9e18f8e13472ed3f6816a)
Referer: https://www.gbif.org/species/9601848
Window size: width 1440 - height 834
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-24T16:30:17.120Z',mode:absolute,to:'2018-04-24T16:36:17.120Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-24T16:30:17.120Z',mode:absolute,to:'2018-04-24T16:36:17.120Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by thomasstjerne** [comment] 2018-04-25 06:31
closing as duplicate of #1213

**Closed by thomasstjerne** 2018-04-25 06:31 UTC
Labels: Under review, data content
