### ISSUE TITLE
identification

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1893] opened 2019-04-16 00:54 UTC
**identification**

Sesamum radiatum Hornemann

have examined this specimen at BR and WAG

-----

System: Chrome 73.0.3683 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/774cb8dfa7e798f673747db72ac8d51d:94ff3d5a0737b5761c7387e566edf3ecca1104ab9ca02db9ca5ab84a047b9c611c8cbbea5fb410268f6b8acd956b20c12e93d1d67977c0cdd47ae514f86be03d)
Referer: https://www.gbif.org/occurrence/1138588494
Window size: width 1331 - height 531
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-16T00:49:09.771Z',mode:absolute,to:'2019-04-16T00:55:09.771Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-16T00:49:09.771Z',mode:absolute,to:'2019-04-16T00:55:09.771Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment] 2019-04-16 12:54
Publishers notified by email.

**Comment by ManonGros** [comment] 2019-07-24 08:36
Occurrence link changed.
The dataset concerned is [Naturalis Biodiversity Center (NL) - Botany](https://www.gbif.org/dataset/15f819bd-6612-4447-854b-14d12ee1022d)
The link to original data is http://data.biodiversitydata.nl/naturalis/specimen/WAG.1901568

**Comment by ManonGros** [comment] 2019-07-24 08:46
Duplicate of https://github.com/gbif/portal-feedback/issues/1900

**Closed by ManonGros** 2019-07-24 08:46 UTC
Labels: NL, Pending, data content
