### ISSUE TITLE
bad navigation om page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#669] opened 2017-11-19 09:08 UTC
**bad navigation om page**

Moving and zooming is not working in map. Navigating downwards in list of datasets is not working. Using android and Firefox.

-----
fbitem-632937989213bf4e43cb42556216fa1047383e29
User provided contact info: anders@natur360.dk
System: Firefox Mobile 56.0.0 / Android 7.0.0
Referer: https://www.gbif.org/occurrence/map?has_coordinate=true&has_geospatial_issue=false&taxon_key=8035075
Window size: width 414 - height 779
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-19T09:02:59.989Z',mode:absolute,to:'2017-11-19T09:08:59.989Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-19T09:02:59.989Z',mode:absolute,to:'2017-11-19T09:08:59.989Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment] 2017-11-20 08:28
map part duplicate of https://github.com/gbif/portal16/issues/486

**Comment by MattBlissett** [comment] 2017-11-20 10:10
I'd guess this is with the new version of Firefox on Android. I can't use the search boxes -- the keyboard doesn't appear.

**Comment by MortenHofft** [comment] 2017-11-20 13:04
Yes that part I'm fairly certain used to work. Thanks Matt

**Comment by thomasstjerne** [comment] 2018-03-20 13:47
Tested and working on firefox 59.0.1 android 7.0.
User contacted by email.

**Closed by thomasstjerne** 2018-03-20 13:47 UTC
Labels: bug, portal
