### ISSUE TITLE
Over ingested dataset and taxonomy error

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2095] opened 2019-07-12 21:20 UTC
I noticed an issue with the amount of records published by Archbold Biological Station Arthropod Collection. Yesterday the total number of records on GBIF matched the 34,720 records on SCAN, but today there seems to be 10,000 more records. I was wondering if there is a way to resolve this because I would like to use the taxon metrics in a report, but the records numbers are not true. It&#39;s primarily within the Formicidae. Also, some taxa have been placed under Mollusca, when in reality Thanks, Stephanie Leon, Assistant Curator at Archbold Biological Station.

-----

User provided contact info: sleon@archbold-station.org
System: Chrome 75.0.3770 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/003c3dc3e754925a22ffd1a22dcf5911:04cdedc5503cf50b89e53a8b696c28451c1982746bdd727d0ebe88f7f01ad5097dc4230ea619720b76f50f7fecdc36c4fb7d1ad73574d05c8f56051fd35bd11a)
Referer: https://www.gbif.org/occurrence/search?offset=0&catalog_number=artharch00047850&taxon_key=1322289
Window size: width 1366 - height 657
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-12T21:15:09.500Z',mode:absolute,to:'2019-07-12T21:21:09.500Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-12T21:15:09.500Z',mode:absolute,to:'2019-07-12T21:21:09.500Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment] 2019-07-15 11:03
The over-crawled records have been deleted but the taxonomy issue remains.

The family of the *Xylophagidae* (https://www.gbif.org/species/6911) are mistakenly classified under the order *Myida*.

**Comment by ManonGros** [comment] 2019-07-15 11:05
same issue also as https://github.com/gbif/portal-feedback/issues/2070

**Comment by mdoering** [comment] 2019-08-07 13:06
dupe of https://github.com/gbif/portal-feedback/issues/1461

**Closed by mdoering** 2019-08-07 13:06 UTC
Labels: backbone, data content
