### ISSUE TITLE
Allow to zoom into an image or open it in full size

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#676] opened 2017-11-22 08:54 UTC
**Allow to zoom into an image or open it in full size**

The label of the specimen shown here is impossible to read in the default image size. Please allow to open the image in its full size or alternatively zoom into the image

-----
fbitem-occurrence1319049951
User provided contact info: mdoering
System: Chrome 62.0.3202 / Mac OS X 10.12.6
Referer: https://www.gbif.org/occurrence/1319049951
Window size: width 1680 - height 885
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-22T08:49:49.240Z',mode:absolute,to:'2017-11-22T08:55:49.240Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-22T08:49:49.240Z',mode:absolute,to:'2017-11-22T08:55:49.240Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: 821cc27a-e3bb-4bc5-ac34-89ada245069d
publishingOrgKey: bc092ff0-02e4-11dc-991f-b8a03c50a862

**Comment by MortenHofft** [comment] 2017-11-22 11:20
I agree. In the meantime you have to go to the original using the link
duplicate of https://github.com/gbif/portal16/issues/592

**Closed by MortenHofft** 2017-11-22 11:20 UTC
Labels: idea, Under review
