### ISSUE TITLE
Incorrect recordId issue count displayed

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#582] opened 2017-10-25 14:20 UTC
**Incorrect recordId issue count displayed**

This [archive being validated](http://ipt-togo.gbif.fr/archive.do?r=reptile&v=1.2) has 88 occurrence records total, none of which have an occurrenceID (record identifier). 

What's the problem? 

The validator displays an issue count of only 87 records without a record identifier.

-----
fbitem-881b5aa5f331f9f02ba11145b2abe98bb5e23c91
User provided contact info: kbraak
System: Chrome 61.0.3163 / Mac OS X 10.10.5
Referer: https://www.gbif.org/tools/data-validator/1508848348037
Window size: width 1396 - height 1104
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-25T14:15:32.212Z',mode:absolute,to:'2017-10-25T14:21:32.212Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-25T14:15:32.212Z',mode:absolute,to:'2017-10-25T14:21:32.212Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by thomasstjerne** [comment] 2017-10-25 14:32
Thanks for reporting.
Actually the issue is "Record not uniquely identified" which is true for all records, except the first one when its blank. Therefore the count is 87.

However, I think you have a point that the special case of having blank identifier fields should be handled different than just reporting them as duplicate id´s.

**Comment by thomasstjerne** [comment] 2017-10-25 14:52
Transferred to https://github.com/gbif/portal16/issues/626

**Closed by thomasstjerne** 2017-10-25 14:52 UTC
Labels: bug, Under review
