### ISSUE TITLE
Add a "maps on a species page" section

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1664] opened 2018-11-26 13:03 UTC
**Add a &quot;maps on a species page&quot; section**

Maps on species pages contain occurrence records from potentially many occurrence datasets. In providing citation guidelines, do we need to distinguish between citing the page as a whole (species page default citation at `https://www.gbif.org/citation-guidelines)` and screenshots of just the map (map layer; occurrence data)?

-----

User provided contact info: @ahahn-gbif
System: Firefox 63.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/57b12ba307d1a661165b5bdaeb0654bd:be6367240b852e29ceaede4010482bb2b8e59d15c12d17f297f3b22d48cda8991fafc956b280b9988ad61ff36df9484e6584130e7513d97d5482caaac2131601)
Referer: https://www.gbif.org/citation-guidelines
Window size: width 1218 - height 795
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-26T12:58:57.261Z',mode:absolute,to:'2018-11-26T13:04:57.261Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-26T12:58:57.261Z',mode:absolute,to:'2018-11-26T13:04:57.261Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment] 2018-11-26 15:54
Probably already requested by https://github.com/gbif/portal-feedback/issues/59

**Comment by dnoesgaard** [comment] 2018-11-28 09:18
Agreed. More or less duplicate of https://github.com/gbif/portal-feedback/issues/59

Let's continue any discussion there...

**Closed by dnoesgaard** 2018-11-28 09:18 UTC
Labels: content
