### ISSUE TITLE
Wrong superior taxonomy

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1322] opened 2018-04-24 16:42 UTC
**Wrong superior taxonomy**

This species is a Bird but the superior taxonomy indicates is a Reptile O.o. Which is very problematic when using the species matching or API tools.

-----

User provided contact info: @camiplata
System: Chrome 65.0.3325 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/a7ae38d121c5d82a5c54c001d09ef787:7c12aa5636b6df0a352d943cc67875ae529c64ef2cb8b3fd885ff0b482d665626146fc15292e8780140ac317effb35e130d2911558e7d7330cf546f8f442d44d)
Referer: https://www.gbif.org/species/5229158
Window size: width 1440 - height 834
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-24T16:37:00.413Z',mode:absolute,to:'2018-04-24T16:43:00.413Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-24T16:37:00.413Z',mode:absolute,to:'2018-04-24T16:43:00.413Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by thomasstjerne** [comment] 2018-04-25 06:31
Closing as duplicate of #1213

**Closed by thomasstjerne** 2018-04-25 06:31 UTC
Labels: Under review, data content
