### ISSUE TITLE
how to submit data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5091] opened 2023-12-12 14:14 UTC
**how to submit data**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/de5f25fb8b663b372024b67db2fd1e7e:c6e7ee7895d43b16e01bea89a84af9a7d615cbb72a7cc0b559b2ae3bc3fed5e07d2a4e0aa8155fbc04be9609da10aafcf7e43a652e61b8e32889a31189653878c0852af94fe0f064793356b8a3717ae0dc4c601b594da6ff690aa7737821b031) - [Send email](https://www.gbif.org/api/feedback/user/mailto/de5f25fb8b663b372024b67db2fd1e7e:c6e7ee7895d43b16e01bea89a84af9a7d615cbb72a7cc0b559b2ae3bc3fed5e07d2a4e0aa8155fbc04be9609da10aafcf7e43a652e61b8e32889a31189653878c0852af94fe0f064793356b8a3717ae0dc4c601b594da6ff690aa7737821b031)
System: Chrome 120.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/derived-dataset/about
Window size: width 1872 - height 1052
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-12T14:09:57.664Z',to:'2023-12-12T14:15:57.664Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-12T14:09:57.664Z',to:'2023-12-12T14:15:57.664Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment] 2023-12-14 14:50
duplicate of https://github.com/gbif/portal-feedback/issues/5096

**Closed as completed by ManonGros** 2023-12-14 14:50 UTC
Labels: question, Under review
