### ISSUE TITLE
species/{int}/media not working for all species

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4036] opened 2022-04-23 20:28 UTC
**species/{int}/media not working for all species**

I am having issues getting all media through the /species api.
it seems as though it is only finding media entries that have a redundant taxonKey key within the media object itself, rather than getting all media entries that are siblings with the taxonKey attribute.

ex. - taxonKey 5230482

when using the /species/{int}/media search as described in the api docs, zero results are given in the response for this taxonKey; concurrently, a search through occurrences (/occurrence/search?mediaType=StillImage&taxonKey=5230482&limit=300&mediaType=Sound&mediaType=MovingImage) shows there are hundreds of media entries for this exact taxonKey/species

-----

Github user: @heresy0-0y
User: [See in registry](https://www.gbif.org/api/feedback/user/80d5bcff77a2ee70b2da59eb9968fecd:14faaaf03f3b44d05efee7903275e7fc9af128213080fc34969e26b55e71b4dca5aa3feedd5f0eb78c7f5101fa521f6518cb42efb67677a02b73c356afd11fc4)
System: Firefox 99.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c
Window size: width 1920 - height 970
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-23T20:23:10.768Z',to:'2022-04-23T20:29:10.768Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-23T20:23:10.768Z',to:'2022-04-23T20:29:10.768Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment] 2022-04-25 07:36
Hi @heresy0-0y

Thank you for your question.
All the entries in the query you mentioned have associated media:
https://api.gbif.org/v1/occurrence/search?media_type=StillImage&media_type=Sound&media_type=MovingImage&taxon_key=5230482&occurrence_status=present&limit=300
For example:
```
"extensions": {
        "http://rs.gbif.org/terms/1.0/Multimedia": [
          {
            "http://purl.org/dc/terms/format": "image/jpeg",
            "http://purl.org/dc/terms/rightsHolder": "hone",
            "http://rs.tdwg.org/dwc/terms/catalogNumber": "174330394",
            "http://purl.org/dc/terms/creator": "hone",
            "http://purl.org/dc/terms/license": "http://creativecommons.org/licenses/by-nc/4.0/",
            "http://purl.org/dc/terms/references": "https://www.inaturalist.org/photos/174330394",
            "http://purl.org/dc/terms/type": "StillImage",
            "http://purl.org/dc/terms/publisher": "iNaturalist",
            "http://purl.org/dc/terms/created": "2022-01-01T08:44:24-08:00",
            "http://purl.org/dc/terms/identifier": "https://inaturalist-open-data.s3.amazonaws.com/photos/174330394/original.jpeg"
          }
        ]
```

Data providers on GBIF don't directly upload images or media on GBIF, instead they share URL to images that they or a third party hosted. If you would like to access the media content, you will ave to use the URLs provided. In the example above, it would the the URL to the image: https://inaturalist-open-data.s3.amazonaws.com/photos/174330394/original.jpeg
You can find more information on how images, sounds and videos are shared on GBIF here: https://data-blog.gbif.org/post/gbif-multimedia/

Keep in mind that media on GBIF might be under a different license than occurrences. Not all images are under open licenses. Depending on the license, you might not be able to use some image, sound and video recordings.

In addition to that, I would advise to use our [download API](https://www.gbif.org/developer/occurrence#download) instead of our occurrence search API. This will allow you to generate one download for all the species of interest. The URL to images/media will be available in the Darwin Core Archive format.
All download generated will be associated with a citable DOI. This will make it easier for you to give credit to the people whose data contributed to your work.
You are very welcome to check this blogpost on how to generate a download for a long list of species: https://data-blog.gbif.org/post/downloading-long-species-lists-on-gbif/

I hope this helps. I will close the issue but don't hesitate to write if you have more question or if I misunderstood your question (I will re-open the issue).

**Closed as completed by ManonGros** 2022-04-25 07:36 UTC
Labels: question, Under review

**Comment by MortenHofft** [comment] 2022-04-25 07:47
Occurrence search returns images of occurrences of a given taxon
https://api.gbif.org/v1/occurrence/search?mediaType=StillImage&taxonKey=5230482
returns 788 records with images

species API search returns images associated with a taxon through a checklist. Not including images of occurrences. So more like: "this is a representative image for this species" - or "this is the holotype for the name".
https://api.gbif.org/v1/species/5230482/media returns zero records with images. 

It works as intended (as far as I can see), but I completely get why it is confusing.

**Comment by heresy0-0y** [comment] 2022-05-02 17:44
I was definitely confused.
Thank you both @MortenHofft  @ManonGros for the clarification !
