### ISSUE TITLE
Registration not available

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#171] opened 2017-04-14 17:39 UTC
**Registration not available**

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482

System: Chrome 57.0.2987 / Windows 7 0.0.0
Referer: https://demo.gbif.org/occurrence/search?q=Micropterus%20salmoides&basis_of_record=OBSERVATION&basis_of_record=LITERATURE&basis_of_record=HUMAN_OBSERVATION&basis_of_record=MACHINE_OBSERVATION&basis_of_record=MATERIAL_SAMPLE
Window size: width 1366 - height 634
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-14T17:34:24.251Z',mode:absolute,to:'2017-04-14T17:40:24.251Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-14T17:34:24.251Z',mode:absolute,to:'2017-04-14T17:40:24.251Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment] 2017-04-27 16:20
Duplicate of #180.

**Closed by MattBlissett** 2017-04-27 16:20 UTC
Labels: bug, Under review
