### ISSUE TITLE
File of data to download deleted itself before it was ready

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#255] opened 2017-07-18 18:50 UTC
**File of data to download deleted itself before it was ready**

I did a search on Bombus terricola with state= Alaska and found records from 3 datasets to download. It began processing my download request but before it was done the file vanished with &quot;This file has been deleted. If you need it restored then please get in touch.&quot; 
citation
    GBIF.org (18 July 2017) GBIF Occurrence Download doi:10.15468/dl.k2qdio

-----
fbitem-1db6806f6142f06805a391920d0a14c9712fab32
Reported by: dssikes@alaska.edu
System: Firefox 54.0.0 / Mac OS X 10.10.0
Referer: https://demo.gbif.org/occurrence/download/0002057-170714134226665
Window size: width 1465 - height 1027
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-18T18:45:11.581Z',mode:absolute,to:'2017-07-18T18:51:11.581Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-18T18:45:11.581Z',mode:absolute,to:'2017-07-18T18:51:11.581Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by cgendreau** [comment] 2017-07-18 18:55
looks like a display issue on the new portal:
http://www.gbif.org/occurrence/download/0002057-170714134226665

**Comment by MortenHofft** [comment] 2017-07-19 14:22
this seem to be a network issue. The demo site does a request for headers and if this is a success it assumes that the file is available for download. It works locally and used to work in prod as well I'm sure. So i suspect it is a network issue. Does that make sense to you @MattBlissett ?

**Comment by MattBlissett** [comment] 2017-07-19 14:42
Has it cached a failed HEAD query? It's fairly likely that a user would look at the page before the download is ready.

It works on the UAT demo site.

**Comment by MattBlissett** [comment] 2017-07-19 14:43
Also, did anyone email dssikes?

**Comment by MortenHofft** [comment] 2017-07-19 14:43
I had accidentally set the cache header to 10 days. That isn't right. 

But it shouldn't show say it has been deleted in the first instance. This issue occurs when the api returns SUCCESS, but the file isn't available. This is seems to be the case and is noticed when updating frequently in eager to get your download. See issue https://github.com/gbif/occurrence/issues/20 for details

**Comment by MortenHofft** [comment] 2017-07-19 14:50
> Also, did anyone email dssikes?

Yes - with a link to the download. And the user should also have received the standard mail with the link to download

**Comment by MortenHofft** [comment] 2017-07-19 15:23
I've added a condition to not show downloads as deleted if they are less than a day old. The issue was two fold

1. there was a 10 day cache header instead of a 10 minute cache header as intended.
2. The API will return SUCCEEDED state and a download link, but when asking for the download it will return with a failure (few seconds after it will be available). If the user happen to refresh in that small interval, the download will display as not available (and be cached as such due to 1).

This should be fixed now: https://github.com/gbif/occurrence/issues/20

**Closed by MortenHofft** 2017-07-19 15:23 UTC
Labels: bug, portal, US
