### ISSUE TITLE
Wrong superior taxonomy

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1321] opened 2018-04-24 16:36 UTC
**Wrong superior taxonomy**

This species is a Bird but the superior taxonomy indicates is a Reptile . Which is very problematic when using the species matching or API tools.

-----

User provided contact info: @camiplata
System: Chrome 65.0.3325 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/cb6233bf82e201acfce58530e0148705:e472ec95c8f01633882cce3e318e166f327652fab90ae1407955ca8ccbb8ec45184ebc3ed2422cf10f863d6ac914c55a7caecd425a1a7334d1c5d22089e13f69)
Referer: https://www.gbif.org/species/2481213
Window size: width 1440 - height 834
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-24T16:31:55.536Z',mode:absolute,to:'2018-04-24T16:37:55.536Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-24T16:31:55.536Z',mode:absolute,to:'2018-04-24T16:37:55.536Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by thomasstjerne** [comment] 2018-04-25 06:31
closing as duplicate of #1213

**Closed by thomasstjerne** 2018-04-25 06:31 UTC
Labels: Under review, data content
