### ISSUE TITLE
Search for DPs endorsed by Participant Node Managers Committe

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#62] opened 2017-02-06 14:37 UTC
**Search for DPs endorsed by Participant Node Managers Committe**

Would be nice to be able to search for data publishers endorsed by the Participant Node Managers Committee from the &quot;Publisher&quot; search

-----
fbitem-22de88f76c9d79b8f048b83b3cfbc3036b234366
Reported by: @siro1
System: Chrome 55.0.2883 / Windows 10 0.0.0
Referer: https://demo.gbif.org/publisher/search?offset=0&amp;q=st%20petersburg
Window size: width 1536 - height 831
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-06T14:32:51.167Z',mode:absolute,to:'2017-02-06T14:38:51.167Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-06T14:32:51.167Z',mode:absolute,to:'2017-02-06T14:38:51.167Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment] 2017-02-07 07:21
Hi Siro. Yes, that would be a nice improvement. The API doesn't support it currently, but sounds reasonable. This is a duplicate of https://github.com/gbif/portal16/issues/250

**Closed by MortenHofft** 2017-02-07 07:21 UTC
Labels: idea, portal
