### ISSUE TITLE
Camirus porosus (Germar, 1839)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3425] opened 2021-05-20 18:29 UTC
**Camirus porosus (Germar, 1839)**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/76f0fee4fcea50569a4dd22d6a7d2332:57e742491ab829ff9cec1b21c8e1740c9008f27fd68b83c1104af6c05d4aa71dfa3bdb7f3d69a9ad3a3f7c6e14ce735168fcdd95f54e9eafe4ba1690ed78bdcf)
System: Chrome 90.0.4430 / Windows 10.0.0
Referer: https://www.gbif.org/species/5160035
Window size: width 1219 - height 673
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-20T18:24:28.343Z',to:'2021-05-20T18:30:28.343Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-20T18:24:28.343Z',to:'2021-05-20T18:30:28.343Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by ManonGros** [comment] 2021-05-21 06:26
seems like a duplicate of https://github.com/gbif/portal-feedback/issues/3426

**Closed as completed by ManonGros** 2021-05-21 06:26 UTC
Labels: Under review, data content
