### ISSUE TITLE
valid name: Microterys bicolor

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4193] opened 2022-08-01 08:31 UTC
**valid name: Microterys bicolor**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/14af85d61a7ad6718228d114c4c925ed:74dd876360bf39df27c23a865abd8be123f49c93aca7b074c041b13b3716cf8b4e4e7db2371622169ac34b6c9d5d6489f88cea4241b96bb7edf3db78482a7809ab87e686a363c87a91433bf7ff227a29f01b7a33d9a8198747794742d19f90649720b5d9082cca52cfbd568ed3cf45e0678a379f3196ac72dc56805b43bf333e489e14dfd276fbbea68b279ce3f308bbf08a1ab664f9097ecaa9e3df44c4ef8c) - [Send email](https://www.gbif.org/api/feedback/user/mailto/14af85d61a7ad6718228d114c4c925ed:74dd876360bf39df27c23a865abd8be123f49c93aca7b074c041b13b3716cf8b4e4e7db2371622169ac34b6c9d5d6489f88cea4241b96bb7edf3db78482a7809ab87e686a363c87a91433bf7ff227a29f01b7a33d9a8198747794742d19f90649720b5d9082cca52cfbd568ed3cf45e0678a379f3196ac72dc56805b43bf333e489e14dfd276fbbea68b279ce3f308bbf08a1ab664f9097ecaa9e3df44c4ef8c)
System: Firefox 91.0.0 / Linux 0.0.0
Referer: https://www.gbif.org/species/1375987
Window size: width 1143 - height 685
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-01T08:26:37.158Z',to:'2022-08-01T08:32:37.158Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-01T08:26:37.158Z',to:'2022-08-01T08:32:37.158Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by bonushenricus** [comment] 2022-08-01 08:33
excuse-me. It is possible ho remove the issue, because there was another issue from me

**Comment by ahahn-gbif** [comment] 2022-08-02 13:29
Duplicate of gbif/backbone-feedback#487 - closing here, but main issue still open

**Closed as completed by ahahn-gbif** 2022-08-02 13:29 UTC
Labels: Under review, data content
