### ISSUE TITLE
Corbis decussata

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3222] opened 2021-01-27 12:07 UTC
**Corbis decussata**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7ca0f087a6c078fbee0d98ee29d5108c:84a9ecf89d9ef8acfd3d560893e5c901edecf1794297616da740ec84d199d558a815355f6385d592a02f1a60369c4afdfbcb09b040e1ae578991332dd2e0e3f4)
System: Firefox 84.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/9263177
Window size: width 1920 - height 966
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-27T12:02:56.922Z',mode:absolute,to:'2021-01-27T12:08:56.922Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-27T12:02:56.922Z',mode:absolute,to:'2021-01-27T12:08:56.922Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment] 2021-02-10 09:23
I contacted the user to ask for some clarifications.

**Comment by ManonGros** [comment] 2021-02-10 09:29
Actually, I believe this is a duplicate of: https://github.com/gbif/backbone-feedback/issues/412

**Closed by ManonGros** 2021-02-10 09:29 UTC
Labels: Needs clarification, Pending, backbone, data content
