### ISSUE TITLE
Cistanthe densiflora (Barnéoud) Hershkovitz

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#709] opened 2017-12-10 15:56 UTC
**Cistanthe densiflora (Barnéoud) Hershkovitz**

Several records of type duplicates indicate -35S. The is wrong. The type is from Coquimbo Province.

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482

System: Chrome Mobile 39.0.2171 / Android 5.0.2
Referer: https://www.gbif.org/occurrence/search?offset=20&taxon_key=4023254
Window size: width 280 - height 398
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-10T15:51:10.053Z',mode:absolute,to:'2017-12-10T15:57:10.053Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-10T15:51:10.053Z',mode:absolute,to:'2017-12-10T15:57:10.053Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by mdoering** [comment] 2017-12-18 09:41
location problem - @MortenHofft should we have a label for that?

**Comment by MortenHofft** [comment] 2017-12-18 10:11
Personally I generally try to label things in a broad sense and let those with more knowledge label them further to their own liking. If team "data product" introduce `location` as an issue, I'll gladly try to remember to add that as well. 

I try to assign `content` to textual/prose issues and let comms take it from there. 
`data content` to data issues and let Andreas team handle it how they like from that point. 
`portal` to website bugs and presentation issues. 
`api` to api related things. 
And since you introduced `backbone` I now try to use that and let you remove it if I'm wrong in assigning it.

So when a new issue comes in, I validate that it isn't spam, removes `needs validation` and label it crudely (≈by team) and let other decide what to do from that point. But I'm not hard set on any approach at all

**Comment by ahahn-gbif** [comment] 2018-05-22 08:44
Checking for georeferenced records for this taxon, there are only four, none of which gives -35S (https://www.gbif.org/occurrence/search?has_coordinate=true&taxon_key=4023254). None of these has a type status. Overall, there is only one type specimen explicitly listed (https://www.gbif.org/occurrence/search?taxon_key=4023254&type_status=TYPE), which does not contain coordinates. It is possible that the issue has meanwhile been fixed at source; closing as unable to reproduce, but please open again if this is a misinterpretation.

**Closed by ahahn-gbif** 2018-05-22 08:44 UTC
Labels: CL, data content
