### ISSUE TITLE
Occurrence result list, Month&Year: display incomplete

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#213] opened 2017-06-13 10:00 UTC
**Occurrence result list, Month&amp;Year: display incomplete**

Longer month names cause the string to be cut short in the display, so that the year is not fully visible. Suggest to make full display of the year a priority, e.g. either by reverting to the old format (month numeric), or by changing the order to &#39;YYYY, mmmmm&#39;

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
Reported by: @ahahn-gbif
System: Firefox 53.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/occurrence/search?taxon_key=2802896
Window size: width 1510 - height 690
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-13T09:55:14.143Z',mode:absolute,to:'2017-06-13T10:01:14.143Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-13T09:55:14.143Z',mode:absolute,to:'2017-06-13T10:01:14.143Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment] 2017-06-14 09:13
duplicate of https://github.com/gbif/portal-feedback/issues/214

**Closed by MortenHofft** 2017-06-14 09:13 UTC
Labels: bug, Under review
