### ISSUE TITLE
Differences in maps  at front page and at occurrence pages

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3728] opened 2021-11-04 16:35 UTC
**Differences in maps at front page and at occurrence pages**

A new datapublisher in The Netherlands showed me that sometimes results on a map at the frontpage of GBIF are different than the results at the occurrence-map page. 

This was the case for the UAT-environment, but it may be that in the production environment this problem does not exist. We discovered this in the dataset https://www.gbif-uat.org/dataset/223d3012-e90d-429a-8c5c-5e12779dbf15 

If you make a selection for a certain year at the frontpage with the slider left below (I never noticed this possibility), the maps look different than at the maps on the occurrence pages:
for 1987: https://www.gbif-uat.org/occurrence/map?dataset_key=223d3012-e90d-429a-8c5c-5e12779dbf15&year=1987,1987
for 1988: https://www.gbif-uat.org/occurrence/map?dataset_key=223d3012-e90d-429a-8c5c-5e12779dbf15&year=1988,1988
If we use the slider at the front page to select 1987 then this is quite similar to the occurrence page. But for 1988 the distributions look very different, there are much fewer data points. This is also true for 1989 and for the years 1999-2008. Other years seems to be fine. I cannot find out what causes these differences between the years.

Jeroen Creuwels, data manager NLBIF

-----

User: [See in registry](https://www.gbif-uat.org/api/feedback/user/24403c7d45712da5088e16877d2d3e31:3a8545187d2ba8b7269b3dbd8f35f5b5d2fc52a1b7f846bb83e48dc2fc024777e5747199aa8e80c2e3f334a9a391d29ef53f5f6849c2064da0cf291cc0175321)
System: Chrome 94.0.4606 / Windows 10.0.0
Referer: https://www.gbif-uat.org/occurrence/3003973767
Window size: width 1920 - height 830
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-04T16:30:06.737Z',to:'2021-11-04T16:36:06.737Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-04T16:30:06.737Z',to:'2021-11-04T16:36:06.737Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: CRITICAL
datasetKey: 223d3012-e90d-429a-8c5c-5e12779dbf15
publishingOrgKey: cace8d10-2646-11d8-a2da-b8a03c50a862

**Comment by MattBlissett** [comment] 2021-11-04 16:59
Thanks @jeroencreuwels, I can see the problem.  It isn't any of the common causes, like records with coordinate issues or the UAT system being out-of-date.

Screenshots: 

![image](https://user-images.githubusercontent.com/583320/140383377-b18bda48-2b1a-4575-a037-939e1ff69f00.png)

![image](https://user-images.githubusercontent.com/583320/140383599-5496089c-9dee-4c8a-a47b-9cc5927db340.png)

https://api.gbif-uat.org/v2/map/occurrence/density/capabilities.json?datasetKey=223d3012-e90d-429a-8c5c-5e12779dbf15 (gives 298262 records, although the search index has 299170 records with no-issue coordinates).

**Comment by timrobertson100** [comment] 2021-11-30 15:14
Closing this as the problem is being tracked in https://github.com/gbif/maps/issues/48

**Closed as completed by timrobertson100** 2021-11-30 15:14 UTC
Labels: bug, NL

**Comment by timrobertson100** [comment] 2021-12-09 15:14
Fixed in production
