### ISSUE TITLE
New duplicate version of dataset published?

### ISSUE THREAD

**Issue by kcopas** [gbif/portal-feedback#1562] opened 2018-10-02 15:15 UTC
There's a dataset that's ostensibly new, but there's an older one that still exists, thanks to the one recorded DOI citation—see them both here: https://www.gbif.org/dataset/search?publishing_org=e2b19af8-fecd-4636-bb66-61e0d430d308

Presume that the dataset was meant to be updated but was instead published a second time.

**Comment by tucotuco** [comment] 2018-10-02 15:58
There is an outstanding issue with the helpdesk about this. The new
resource is the same as the old one, but under a new organisation. The
outstanding problem is being able to connect the old and new versions and
remove the old one.

**Comment by ManonGros** [comment] 2018-10-03 09:11
@tucotuco, it seems that for both dataset the organisation is the [Florida Museum of Natural History, Florida Archaeology](https://www.gbif.org/publisher/e2b19af8-fecd-4636-bb66-61e0d430d308).
We can change the publishing organisation if you wish. Let us know.
In the meanwhile, since the old dataset isn't indexed anyway, I propose to deleted and label it as a duplicate of the new one (the page with the citation will still be there but with a link to the new dataset). How does that sound?

**Comment by tucotuco** [comment] 2018-10-03 13:00
That sounds great Marie. One thing remaining in that case. How can I set
the resource to be in the registered state on the IPT?

**Comment by ManonGros** [comment] 2018-10-03 13:06
I don't know if I understand. What do you mean by "registered state"? This resource is already registered.

**Comment by tucotuco** [comment] 2018-10-03 13:49
I mean that in the IPT, it shows as not registered, with the Register
button enabled.

**Comment by ManonGros** [comment] 2018-10-03 14:19
This resource probably not in GBIF then. It seems like you might have a third version of the dataset.
If you are going to publish it, just make sure that the title and publishing institution are the same as the dataset already published and the alternative identifier in the additional metadata should be "30595b72-0016-42cf-a1b5-afa6a2474cba".
Let me know if I should change the publishing organization of the published dataset before you publish the new one.

Anyway, perhaps your dataset is registered but not public. Could you check that it is both attached to an organization, registered and public?

**Comment by tucotuco** [comment] 2018-10-03 14:34
I logged into the IPT anew just now. Now, on our IPT we have
http://ipt.vertnet.org:8080/ipt/resource?r=flarch_zooarch_parnell_feature1
only. There is no other resource for this data set. It is Published,
Public, and now shows "Registered" as Dataset
ID 30595b72-0016-42cf-a1b5-afa6a2474cba to organisation Florida Museum of
Natural History, Florida Archaeology (
https://www.gbif.org/publisher/e2b19af8-fecd-4636-bb66-61e0d430d308). It
has 3f42d91f-acc2-46e2-a807-f117eab8b762 as an Alternative Identifier. On
GBIF the organisation looks right. The data set looks right too, except
that the citation associated with its previous version is not associated
with this resource - the citation that can be seen on
https://www.gbif.org/dataset/3f42d91f-acc2-46e2-a807-f117eab8b762. Other
than that, all seems well now. Thank you!

**Comment by ManonGros** [comment] 2018-10-03 14:42
Ok great! The issue is fixed then.

Yes, we don't have any citation transfert right now so we have to do with the redirection to the newer dataset page (hopefully this will change in the future).

**Closed by ManonGros** 2018-10-03 14:42 UTC
Labels: data content

**Comment by tucotuco** [comment] 2018-10-17 01:36
I have been thinking this through further, especially in light of all the
rest of the maintenance surrounding the data set. It would be far better if
there was no new data set identifier. It isn't a new data set. I find that
having to deal with the second one is an exception that is breaking a bunch
of statistics tracking we have built with an ultimate burden on the data
publisher as well. So, this is a plea to see if there is a reasonable way
to not have to have this second data set identifier at all.

Thus, I propose to keep 3f42d91f-acc2-46e2-a807-f117eab8b762 and make
30595b72-0016-42cf-a1b5-afa6a2474cba an unfortunate alternative identifier
that should never have happened.
