### ISSUE TITLE
ordering

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2762] opened 2020-05-05 15:37 UTC
**ordering**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/00aaa42caf47ada00ce41ebf5d9b9218:2b06de917d69ac6aa9dabfb1f14ac4acfc6e04e69441da456ac1fe2af8ed28d47b433bda7471efe3496efb781c7fec21a7d634676790b0959fe47e8ca0949719)
System: Chrome 81.0.4044 / Mac OS X 10.15.4
Referer: https://www.gbif.org/species/2994120
Window size: width 2560 - height 1306
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-05T15:32:23.009Z',mode:absolute,to:'2020-05-05T15:38:23.009Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-05T15:32:23.009Z',mode:absolute,to:'2020-05-05T15:38:23.009Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment] 2020-10-02 06:53
Closing as duplicate of https://github.com/gbif/portal-feedback/issues/2763

**Closed by ManonGros** 2020-10-02 06:53 UTC
Labels: CH, Under review, question
