### ISSUE TITLE
IndividualCount mismatch with VertNet

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3547] opened 2021-08-19 14:13 UTC
**IndividualCount mismatch with VertNet**

On 

http://portal.vertnet.org/o/uwbm/bird?id=urn-catalog-uwbm-bird-111793

the value for individualCount is 1 but on GBIF 

https://www.gbif.org/occurrence/730722429

the value 0. 

Also seems that this dicrepancy is general for the registries in Mexico on the dataset 

https://www.gbif.org/dataset/830fd460-f762-11e1-a439-00145eb45e9a

-----

Github user: @jmbarrios
User: [See in registry](https://www.gbif.org/api/feedback/user/b622c8d173a8e98203c7e77005f04cc5:29147c6c5b50450c8486156312106182dc271e43c0e0c171d5f95fec3069a659339b0f64546a51f10fb743a41f4e60e6b09da6697c4869229d9d061d2118a2f8)
System: Firefox 91.0.0 / Linux 0.0.0
Referer: https://www.gbif.org/occurrence/730722429
Window size: width 1920 - height 963
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-19T14:08:16.078Z',to:'2021-08-19T14:14:16.078Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-19T14:08:16.078Z',to:'2021-08-19T14:14:16.078Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 830fd460-f762-11e1-a439-00145eb45e9a
publishingOrgKey: 06fcbbf0-0562-11d8-b851-b8a03c50a862
Network keys: 99d66b6c-9087-452f-a9d4-f15f2c2d0e7e 
Node handles: @albenson-usgs

**Comment by AbbyBenson** [comment] 2021-08-19 15:04
I think something is going wrong with the [data in the IPT](http://ipt.vertnet.org:8080/ipt/resource.do?r=uwbm_birds). The current version 10.12 has 0 records and the version before that [10.11](http://ipt.vertnet.org:8080/ipt/resource?r=uwbm_birds&v=10.11) has zeros for all the individualCount for all occurrences. Thinking VertNet is already aware and attempting to fix but I'll reach out to them to be sure.

**Comment by AbbyBenson** [comment] 2021-08-23 18:26
VertNet is aware of this issue and looking into it. Currently no estimate on when it will be fixed.

**Comment by dbloom** [comment] 2021-08-26 16:54
There is something going on at the local level with this dataset. I have confirmed that other datasets are being auto-published via the VN IPT, including the invert paleo dataset from UWBM. I have send Rob Fawcett an inquiry to find out what might be happening on the Burke side. I have not had a response yet, but it is last minute vacation time before campus comes to life there. I don't know, but I suspect is't a SQL issue on their end. I will follow up with them next week.

If users need it, I can reinstate the previous publication, 10.11, but that will not address the issue with individualCount.

**Comment by jmbarrios** [comment] 2021-08-26 22:12
I don't need the previous publication at this moment. If this changes, I'll let you know.

**Comment by dbloom** [comment] 2021-09-09 19:00
This resource has been republished, as of Sept 1. Looks like the individualCount and organismQuantity counts are back to normal. Please let me know if what is present does not represent expected values.

**Comment by AbbyBenson** [comment] 2021-11-03 14:16
Can we close this ticket?

**Closed as completed** 2021-11-03 14:28 UTC
Labels: data content, US, Pending
