### ISSUE TITLE
photo download

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4972] opened 2023-09-18 07:58 UTC
**photo download**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6175891ec61131e9ade2eaeca1285cbf:f5c47c8ab0c891a6f50771543bcb588a1d3392c0d80a17e00b787c80020eb7df9589981a2ca0d7bbd48a38ccbd0ddae229f5931640e658eed72bbdda23d5046bc97fb82d68ad3e810a7c0943e4e20297567f6c206dab23875df148dabd3b86ab) - [Send email](https://www.gbif.org/api/feedback/user/mailto/6175891ec61131e9ade2eaeca1285cbf:f5c47c8ab0c891a6f50771543bcb588a1d3392c0d80a17e00b787c80020eb7df9589981a2ca0d7bbd48a38ccbd0ddae229f5931640e658eed72bbdda23d5046bc97fb82d68ad3e810a7c0943e4e20297567f6c206dab23875df148dabd3b86ab)
System: Chrome 117.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/4062809323
Window size: width 2560 - height 963
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-18T07:53:26.812Z',to:'2023-09-18T07:59:26.812Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-18T07:53:26.812Z',to:'2023-09-18T07:59:26.812Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 50c9509d-22c7-4a22-a47d-8c48425ef4a7
publishingOrgKey: 28eb1a3f-1c15-4a95-931a-4af90ecb574d

Node handles: @albenson-usgs @sformel-usgs

**Comment by ManonGros** [comment] 2023-09-18 08:34
Duplicate of: https://github.com/gbif/portal-feedback/issues/4973

**Closed as completed by ManonGros** 2023-09-18 08:34 UTC
Labels: question, Under review, US
