### ISSUE TITLE
i cannot register

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#173] opened 2017-04-19 13:44 UTC
**i cannot register**

-----
fbitem-8b16037cf12b5f958bf6d374db1c1429764c1b51
Reported by: cimatti.marta@gmail.com
System: Chrome 57.0.2987 / Windows 10 0.0.0
Referer: https://demo.gbif.org/occurrence/download?taxon_key=2439261&year=1991,1993
Window size: width 1350 - height 541
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-19T13:39:19.481Z',mode:absolute,to:'2017-04-19T13:45:19.481Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-19T13:39:19.481Z',mode:absolute,to:'2017-04-19T13:45:19.481Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment] 2017-04-21 11:17
Did anyone reply to this?

**Comment by MattBlissett** [comment] 2017-04-27 16:23
Duplicate of #180.

User emailed.

**Closed by MattBlissett** 2017-04-27 16:23 UTC
Labels: bug, Under review

**Comment by MortenHofft** [comment] 2017-05-02 08:56
user informed about fix
