### ISSUE TITLE
Data validator doesn't detect missing occurrenceID in checklist with occurrences

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1746] opened 2019-01-23 09:16 UTC
**Data validator doesn&#39;t detect missing occurrenceID in checklist with occurrences**

This checklist (`https://www.gbif.org/dataset/e98db1f8-4115-4259-acbb-4b5cd498d3c8)` couldn't be crawled because it contains occurrences without occurrenceIDs.

However, the data validator didn't report the missing occurrenceIDs.

-----

User provided contact info: @ManonGros
System: Safari 12.0.2 / Mac OS X 10.14.2
User: [See in registry](https://www.gbif.org/api/feedback/user/3d587ffdc9767df855d9eac135986cde:033f8711de35baef57af7506e2ce333d846d159f6d2636bfa61a8103c2b2a751ee0b8cd0b63eabd60b0a38239ab7c50cf517fc0f4a87e3f21fc1749b7a7ceeb3)
Referer: https://www.gbif.org/tools/data-validator/1546511789563
Window size: width 1730 - height 770
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-23T09:11:32.445Z',mode:absolute,to:'2019-01-23T09:17:32.445Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-23T09:11:32.445Z',mode:absolute,to:'2019-01-23T09:17:32.445Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by thomasstjerne** [comment] 2019-02-19 09:24
Maybe a duplicate of https://github.com/gbif/gbif-data-validator/issues/80

**Comment by ManonGros** [comment] 2019-03-28 10:14
Here is the original Darwin Core Archive:
[dwca-acanthaceae-v1.zip](https://github.com/gbif/portal-feedback/files/3017346/dwca-acanthaceae-v1.zip)

**Closed** 2019-03-28 14:12 UTC
Labels: bug, data validator
