### ISSUE TITLE
https://www.gbif.org/species/2646813 Gallery link broken. Important new pictures available

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2332] opened 2019-12-09 09:08 UTC
**`https://www.gbif.org/species/2646813` Gallery link broken. Important new pictures available**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/1f5cd7bf1131f9db18352fb03a64ed09:62235b696a07f4e3509b652402589eacd0598b91d436797dea607001a3e8f3005f3a8ef1a00de7188bf2b06f39bee9a0106cba5a1e0f93a57ace87e38f7cc15f)
System: Chrome 78.0.3904 / Windows 10.0.0
Referer: https://www.gbif.org/health
Window size: width 1920 - height 947
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-09T09:03:55.804Z',mode:absolute,to:'2019-12-09T09:09:55.804Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-09T09:03:55.804Z',mode:absolute,to:'2019-12-09T09:09:55.804Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment] 2019-12-09 10:03
Duplicate of #2331 .

**Closed by MattBlissett** 2019-12-09 10:03 UTC
Labels: Under review, data content
