### ISSUE TITLE
add "not" operator to query options

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#491] opened 2017-09-26 09:56 UTC
**add &quot;not&quot; operator to query options**

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482

System: Chrome 60.0.3112 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/search?dataset_key=d0e9b7eb-29a9-4695-bb13-22585df648a5&dataset_key=17411afb-5543-4d0a-8f36-47cb8322062e&dataset_key=cc7cd3f8-1ff5-4273-ad34-f89351392925&dataset_key=a6e35034-fca7-457f-888b-e6d97030dee5&advanced=1
Window size: width 1536 - height 686
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-26T09:51:06.970Z',mode:absolute,to:'2017-09-26T09:57:06.970Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-26T09:51:06.970Z',mode:absolute,to:'2017-09-26T09:57:06.970Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment] 2017-09-26 10:35
duplicate of https://github.com/gbif/portal-feedback/issues/49

**Closed by MortenHofft** 2017-09-26 10:35 UTC
Labels: idea, Under review
