### ISSUE TITLE
event calendar subscription fails

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1847] opened 2019-03-19 10:50 UTC
**event calendar subscription fails**

Not sure how long this has been broken, but the "Subscribe to calendar" link (`http://api.gbif.org/v1/newsroom/events/calendar/upcoming.ics)` produces this error:

```
{
"code": 500,
"message": "There was an error processing your request. It has been logged (ID 35d016b27a941985)."
}
```

-----

User provided contact info: @dnoesgaard
System: Chrome 72.0.3626 / Mac OS X 10.14.3
User: [See in registry](https://www.gbif.org/api/feedback/user/e09d4e92e80f3951003f9af279b09a5c:a0637cac9b26053575c928a6b7cc98b52bfacca7fb7a176ad97108a8f4e651661db284176d44cd3d77e167f8ab9a7f6d2984c215678b037adce7e580aa269891)
Referer: https://www.gbif.org/resource/search?contentType=event
Window size: width 1727 - height 1156
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-19T10:45:12.478Z',mode:absolute,to:'2019-03-19T10:51:12.478Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-19T10:45:12.478Z',mode:absolute,to:'2019-03-19T10:51:12.478Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MattBlissett** [comment] 2019-07-03 15:01
Duplicate of #1879

**Closed by MattBlissett** 2019-07-03 15:01 UTC
Labels: api, bug
