### ISSUE TITLE
Should use occurrence search service for counts, not metrics

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#152] opened 2017-03-26 08:13 UTC
**Should use occurrence search service for counts, not metrics**

This shows `Occurrences: 8908939` which is the current value in the HBase cube (i.e. a ../metrics/.. API call) and inaccurate.

All occurrence counts must come from `/occurrence/search` calls because we plan to deprecate and remove the metrics service.  This will be slower (i.e. use AJAX) but will be consistent.

Please check for existence of any call in the project making use of HBase cube tables.  There are 3 tables (plus v1 maps) so first need to identify the API calls associated.

This should be considered a blocker for release.

-----
fbitem-species2490384
Reported by: @timrobertson100
System: Chrome 57.0.2987 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/species/2490384
Window size: width 1440 - height 799
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-26T08:08:48.308Z',mode:absolute,to:'2017-03-26T08:14:48.308Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-26T08:08:48.308Z',mode:absolute,to:'2017-03-26T08:14:48.308Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment] 2017-03-26 10:33
closed as duplicate of https://github.com/gbif/portal16/issues/339

**Closed by MortenHofft** 2017-03-26 10:33 UTC
Labels: bug
