### ISSUE TITLE
Consider to present geological context better

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#31] opened 2017-01-11 21:26 UTC
**Consider to present geological context better**

For fossils the geological context is very important. It defines when the organism was alive similar to the eventDate for observations. When the fossil was digged out (the eventDate) is less important.

We might need to interpret the geo context better so we can eventually present it in a little graph. Wikipedia does so for fossil species: https://en.wikipedia.org/wiki/Tyrannosaurus

See https://en.wikipedia.org/wiki/Geologic_time_scale

-----
fbitem-occurrence1316909835

System: Chrome 55.0.2883 / Mac OS X 10.11.6
Referer: https://demo.gbif.org/occurrence/1316909835
Window size: width 1440 - height 706
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-11T21:21:12.083Z',mode:absolute,to:'2017-01-11T21:27:12.083Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-11T21:21:12.083Z',mode:absolute,to:'2017-01-11T21:27:12.083Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: c8681cc2-9d0a-4c5f-b620-5c753abfe2bc
publishingOrgKey: bc092ff0-02e4-11dc-991f-b8a03c50a862

**Comment by MortenHofft** [comment] 2017-01-12 15:20
I fully agree. And thank you for the references.
I'm closing this as a duplicate of https://github.com/gbif/portal16/issues/7

Thank you for your interest and suggestion

**Closed by MortenHofft** 2017-01-12 15:20 UTC
Labels: idea, portal

**Comment by dperriguey** [comment] 2019-08-06 17:49
@gbif-portal 

I am writing this here because it seems like an extension of this issue. I am a collections assistant for University of New Mexico, Earth and Planetary Sciences Department's invertebrate fossil collections. I work through Arctos Database and all our data are then published also in GBIF and iDigBio. We've just mapped our geological context data using the Darwin Core (DWC). We're still working out some bugs, but it looks like an obvious and seemingly easy to fix issue popped up on our published GBIF pages. 

Geological context should be displayed in hierarchical order, just like the Linnaean hierarchy. Earliest period or lowest system should be above Earliest epoch or lowest series, and Group should be above Formation when displayed. I have an example below:

https://www.gbif.org/occurrence/1849035846
![image](https://user-images.githubusercontent.com/32556913/62560908-3eefe080-b83b-11e9-9984-c843d9bd3d62.png)

There is definitely more to this. Chronostratigraphic units have a hierarchy and lithostratigraphic units have a hierarchy. Chronostratigraphy should also be displayed above lithostratigraphy; it is this way currently in GBIF. I've posted links below to hopefully help with the process:

Chronostratigraphy:
http://stratigraphy.org/ICSchart/ChronostratChart2018-08.jpg
High to low from left to right:
![image](https://user-images.githubusercontent.com/32556913/62563317-0acaee80-b840-11e9-9858-cd56fdb8c849.png)

Lithostratigraphy:
https://dwc.tdwg.org/terms/#geologicalcontext
Definitions: http://www.stratigraphy.org/upload/bak/litho.htm
Correct order:
![image](https://user-images.githubusercontent.com/32556913/62563155-a60f9400-b83f-11e9-9b4d-45477a3fb583.png)

**Comment by MortenHofft** [comment] 2019-08-13 08:47
Thank you so much for your help.
I have changed the ordering. It will be in production later today.

**Comment by dperriguey** [comment] 2019-08-13 16:41
Great! You're welcome! Thank you!
