### ISSUE TITLE
Consultation of bird records in eastern Colombia

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1546] opened 2018-09-18 16:51 UTC
**Consultation of bird records in eastern Colombia**

-----

User provided contact info: cgaitan89@hotmail.com
System: Chrome 68.0.3440 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/8765120cb94b9bfdf60421f193690fc4:5be69329200862ccdcaf8d9fe5893be99e819700983b45d6773e6674c17bd9c1d71fea0ec77790a60b070fc720959ec8577c9d2477976edc566391d1be3d2b6b)
Referer: https://www.gbif.org/occurrence/download?basis_of_record=HUMAN_OBSERVATION&basis_of_record=PRESERVED_SPECIMEN&country=CO&dataset_key=4fa7b334-ce0d-4e88-aaae-2e0c138d049e&dataset_key=9850b85a-793f-429d-a437-2d5b46282acf&dataset_key=79684ec1-01e8-46cc-83cb-cd5bdfb469fe&has_coordinate=true&has_geospatial_issue=false&publishing_org=eac88d99-9f6c-4031-8fc4-8088f0e0dfe7&publishing_org=e2e717bf-551a-4917-bdc9-4fa0f342c530&publishing_org=dc282b9d-8f3b-4197-b174-ba5272721a6f&geometry=POLYGON((-69.48853%20-1.03266,-69.54895%20-0.58227,-70.03922%20-0.18402,-70.01587%200.50536,-69.47479%200.71409,-69.24408%200.59325,-69.23721%201.04639,-69.84283%201.0711,-69.82635%201.70263,-68.1839%201.71361,-68.25943%201.85636,-68.19901%202.02655,-67.90718%201.80832,-67.7829%201.99911,-67.57278%202.04028,-67.39529%202.23035,-67.31598%201.91127,-67.1608%201.81519,-67.08939%201.18369,-66.86279%201.18644,-67.11411%202.11988,-67.37778%202.54799,-67.62676%202.79337,-67.8598%202.82783,-67.57828%203.1268,-67.38327%203.25021,-67.42722%203.56002,-67.50412%203.77108,-67.61948%203.77108,-67.69157%203.9355,-67.71286%204.05058,-67.91885%203.90536,-68.30063%203.96838,-68.46542%203.82589,-68.75656%203.72449,-69.67392%203.55728,-70.0296%203.48601,-70.47455%203.23924,-70.61188%203.21182,-70.8316%202.8004,-71.33148%202.86624,-71.74072%202.76748,-72.13348%202.81686,-72.76554%202.57543,-72.79953%202.75925,-72.86407%202.77845,-73.17719%202.88818,-73.22353%202.90121,-73.25821%203.13503,-73.4079%203.29957,-73.4079%203.29957,-73.65921%203.46133,-73.75397%203.5189,-73.79173%203.72723,-73.86246%203.79574,-73.91739%203.793,-73.94485%203.63404,-74.07188%203.55591,-74.13162%203.48326,-73.94691%203.18577,-73.86246%202.96498,-73.72444%202.60972,-73.64204%202.44646,-73.61458%202.42588,-73.51639%202.3806,-73.10341%202.29997,-72.98012%202.05812,-72.87918%201.19193,-72.71851%200.68114,-72.33467%20-0.35019,-72.32094%20-0.54519,-72.25296%20-0.59874,-72.14859%20-0.5548,-72.04422%20-0.75529,-71.8602%20-0.81021,-71.75583%20-0.95851,-71.56769%20-0.96126,-71.57181%20-1.12053,-71.51825%20-1.13701,-71.47842%20-1.15623,-71.32462%20-1.05188,-71.20926%20-1.04364,-71.08566%20-1.11504,-70.98129%20-1.26058,-70.8522%20-1.28255,-70.74646%20-1.42807,-70.66544%20-1.46102,-70.58578%20-1.41984,-70.53085%20-1.48024,-70.40382%20-1.43906,-70.30151%20-1.45004,-70.04333%20-1.59281,-69.95888%20-1.34158,-69.88129%20-1.23037,-69.59976%20-1.31824,-69.42947%20-1.31001,-69.48853%20-1.03266))
Window size: width 1366 - height 662
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-18T16:45:59.769Z',mode:absolute,to:'2018-09-18T16:51:59.769Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-18T16:45:59.769Z',mode:absolute,to:'2018-09-18T16:51:59.769Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment] 2018-09-19 17:33
duplicate of https://github.com/gbif/portal-feedback/issues/1547

**Closed by MortenHofft** 2018-09-19 17:33 UTC
Labels: Under review, data content
