### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4352] opened 2022-10-18 01:39 UTC
**Hello,**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c29a0cd4a6605789cd8055f522682576:91156653fc06f231027f9ce58099842b960c452e0cd579ac215831fb75cf22fc0b36711d9742ef3edb2c8926eea0f523aa81a6607616f027dea3235f2dbecb0daeb62efa6803ee3b0b889ff33218b0f93d99700b372d05158db47f81bd65aad62b0924ed66583460b11ce4e260cac187614c7caab47e5ba244e33bea58eee80e50e121a74cde79a06c888257bed42963) - [Send email](https://www.gbif.org/api/feedback/user/mailto/c29a0cd4a6605789cd8055f522682576:91156653fc06f231027f9ce58099842b960c452e0cd579ac215831fb75cf22fc0b36711d9742ef3edb2c8926eea0f523aa81a6607616f027dea3235f2dbecb0daeb62efa6803ee3b0b889ff33218b0f93d99700b372d05158db47f81bd65aad62b0924ed66583460b11ce4e260cac187614c7caab47e5ba244e33bea58eee80e50e121a74cde79a06c888257bed42963)
System: Chrome 106.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/tools/data-validator/145e758d-c546-451f-9df3-82cf7878160e
Window size: width 767 - height 712
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-18T01:34:18.688Z',to:'2022-10-18T01:40:18.688Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-18T01:34:18.688Z',to:'2022-10-18T01:40:18.688Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment] 2022-10-18 04:51
likely duplicate of https://github.com/gbif/portal-feedback/issues/4353

**Closed as completed by MortenHofft** 2022-10-18 04:51 UTC
Labels: bug, Under review
