### ISSUE TITLE
Deleted datasets show up in google searches

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5423] opened 2024-08-13 18:56 UTC
**Deleted datasets show up in google searches**

There are 2 IRMNG datasets showing up in google searches, one of them this deleted dataset since 2016.

The page already contains:
<meta name="robots" content="noindex nofollow">

Maybe there is sth else that can be done to prevent google from indexing deleted dataset pages?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/1bcdb6c1dcaa9bf18a78263275f636da:b01897ebb86c9681c644c7b80adf0e5ed0da3e7dac6a79981884c796830ca6376e2226f7a439cc5afccbaf56fb0cfa239e3d8c7956c1dcd4bb08337f11006c9f6f2d25467a737a5dfdb2475fd17f61365d71284897d7dc49f823449922f366180ea4892a323e75b54893b3bef32afd5eca79545c62adac1d97f756f4325eb3a6) - [Send email](https://www.gbif.org/api/feedback/user/mailto/1bcdb6c1dcaa9bf18a78263275f636da:b01897ebb86c9681c644c7b80adf0e5ed0da3e7dac6a79981884c796830ca6376e2226f7a439cc5afccbaf56fb0cfa239e3d8c7956c1dcd4bb08337f11006c9f6f2d25467a737a5dfdb2475fd17f61365d71284897d7dc49f823449922f366180ea4892a323e75b54893b3bef32afd5eca79545c62adac1d97f756f4325eb3a6)
System: Safari 17.5.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/05b2f719-f3df-4e60-9e69-3060d9f5f950
Window size: width 1759 - height 540
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-08-13T18:51:11.257Z',to:'2024-08-13T18:57:11.257Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-08-13T18:51:11.257Z',to:'2024-08-13T18:57:11.257Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by mdoering** [comment] 2024-08-13 18:58
try searching for [IRMNG and GBIF](https://www.google.com/search?q=irmng+gbif)

**Comment by ahahn-gbif** [comment] 2024-08-14 13:39
@mdoering, this is not a bug as such: the page does exist, as we do delete the data, but not the metadata of deleted datasets. This is by design, so that existing links do not just go out of scope. We would need to inform search indexes to omit specific pages, but have not looked into this so far

**Comment by mdoering** [comment] 2024-08-14 14:14
Yes, I didn't want to challenge the logical deletion and keeping tombstones.
It is just that these deleted datasets show up in google searches and have confused users - we should tell google not to do so.

**Comment by mdoering** [comment] 2024-08-19 07:17
@MortenHofft @thomasstjerne could we easily return a HTTP 410 Gone response in the response of the deleted pages?

**Comment by MortenHofft** [comment] 2024-08-19 07:44
We return a no index no follow. `<meta name="robots" content="noindex nofollow">` If google index it then they aren't playing nicely. Asking google and others to not even look at it will, according to their documentation, mean that the page WILL show up in search results, because they might know of its existence from other pages linking to it. So they will just show a link with no description. But since they aren't allowed to look at it, then they won't read the noindex tag. 

Perhaps they have changed guidelines. Or perhaps they just do what they want.

The sitemap is generated using our search API so it shouldn't be their either since that does not include deleted datasets

**Comment by MortenHofft** [comment] 2024-08-19 07:56
Reading above comment I see it. There is a typo!! 😱  there is a space instead of a comma. Obviously that is unreadable by anyone. That is probably the reason.
It should be `<meta name="robots" content="noindex,nofollow">`

I'm deploying and asking google to reindex the page

**Closed as completed** 2024-08-19 08:00 UTC
Labels: bug, Under review

**Comment by MortenHofft** [comment] 2024-08-19 08:01
It is correct now, but it might take a while for Google to notice. I've tested that one page and it behaves as expected in the search console
