### ISSUE TITLE
Link out to BOLD

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1827] opened 2019-03-07 16:08 UTC
**Link out to BOLD**

Look how links out to BOLD work for GBIF Finland `https://laji.fi/taxon/MX.10/taxonomy?showTree=true.` I would see addition of a BOLD button to See also section a very nice improvement, before the BINs are added to the backbone and BOLD occurrences are linked dynamically

-----

User provided contact info: @dschigel
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/7692a8ce41fc0e7b83c5afb714484c66:9d96bdd3c78ce6a583230d13f079aec7d246cfc53ccc19e3d346a185422bbb289d97bd5f6aef09e33a303dacd731f0bac72f082c1c971b7ef3d87a544f3b3f2b)
Referer: https://www.gbif.org/species/1424038
Window size: width 2048 - height 1025
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-07T16:03:39.752Z',mode:absolute,to:'2019-03-07T16:09:39.752Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-07T16:03:39.752Z',mode:absolute,to:'2019-03-07T16:09:39.752Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MortenHofft** [comment] 2019-08-23 07:32
This seem to be a duplicate of this closed issue https://github.com/gbif/portal-feedback/issues/1968 - else please reopen

**Comment by thomasstjerne** [comment] 2019-08-23 07:34
I am afraid BOLD IDs are not in wikidata. 
This should probably be done based on the BOLD checklist / occurrence dataset

**Comment by MortenHofft** [comment] 2019-08-23 08:14
In that case I assume this shouldn't be closed either https://github.com/gbif/portal-feedback/issues/1968

**Comment by thomasstjerne** [comment] 2022-03-17 12:31
Superseded by BOLD data in GBIF and BOLD identifiers in wikidata (identifiers section at the bottom of species pages)

**Closed by thomasstjerne** 2022-03-17 12:31 UTC
Labels: idea, portal
