### ISSUE TITLE
Wrong classification for family Agaricomycetidae

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5211] opened 2024-02-28 16:58 UTC
**Wrong classification for family Agaricomycetidae**

Agaricomycetidae is listed as a children taxon for phylum Bryophyta (kingdom Plantae), correct classification is as follows: https://taxref.mnhn.fr/taxref-web/taxa/522910

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ea026b1616a3b95df53c38e24a7994e4:3a7a6a2dd36642246d023f2b12af4679d56d98cd8ca2441a7b277c02bb27ee443fa4f84e3bc3b4f5c68d91fd530eae3287eb84f424de0fc9018532444f2513a8440ed7b90f62919a0f065501d631e03eedc025707dea13e3041a7e58026f712f1a9483110b88f6de632f80532b3c82fbce520b6f4e0f99036be9261c8a342f3621972d708612e6422dea2a7f80482c01) - [Send email](https://www.gbif.org/api/feedback/user/mailto/ea026b1616a3b95df53c38e24a7994e4:3a7a6a2dd36642246d023f2b12af4679d56d98cd8ca2441a7b277c02bb27ee443fa4f84e3bc3b4f5c68d91fd530eae3287eb84f424de0fc9018532444f2513a8440ed7b90f62919a0f065501d631e03eedc025707dea13e3041a7e58026f712f1a9483110b88f6de632f80532b3c82fbce520b6f4e0f99036be9261c8a342f3621972d708612e6422dea2a7f80482c01)
System: Firefox 115.0.0 / Windows 8.1.0.0
Referer: https://www.gbif.org/species/11120794
Window size: width 1280 - height 598
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-28T16:53:11.415Z',to:'2024-02-28T16:59:11.415Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-28T16:53:11.415Z',to:'2024-02-28T16:59:11.415Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment] 2024-02-29 14:22
This seems to be an issue for at least one other name: https://www.gbif.org/species/11172900

I cannot find the source for either Agaricomycetidae nor Dothideomycetes in the backbone. @mdoering any idea where the taxonomy we have for those come from? And how we could fix it in the next backbone release?

**Comment by mdoering** [comment] 2024-02-29 15:56
Duplicate of https://github.com/gbif/backbone-feedback/issues/173

**Closed as completed by mdoering** 2024-02-29 15:56 UTC
Labels: duplicate, data content, backbone
