### ISSUE TITLE
Sort occurrences in chronological order

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#539] opened 2017-10-06 07:18 UTC
**Sort occurrences in chronological order**

Hi,
I think it would be better if the latest records were shown first in the lists of occurrences. Now it is sorted first by year then month which means that you have to click next again and again to see the most recent occurrences. It is more logical to have the most recent occurrences on top.

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
User provided contact info: veronika.johansson@nrm.se
System: Firefox 56.0.0 / Windows 7 0.0.0
Referer: https://www.gbif.org/occurrence/search?country=SE&dataset_key=50c9509d-22c7-4a22-a47d-8c48425ef4a7
Window size: width 1344 - height 710
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-06T07:13:08.230Z',mode:absolute,to:'2017-10-06T07:19:08.230Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-06T07:13:08.230Z',mode:absolute,to:'2017-10-06T07:19:08.230Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment] 2017-10-09 12:42
duplicate of https://github.com/gbif/portal-feedback/issues/224

**Closed by MortenHofft** 2017-10-09 12:42 UTC
Labels: idea, Under review
