### ISSUE TITLE
Mention restriction of maximum offset in seach requests

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#703] opened 2017-12-07 08:07 UTC
**Mention restriction of maximum offset in seach requests**

-----
fbitem-f0bca0774a9c8eaecc8788650664fc5d3e0b6ba1

System: Chrome 62.0.3202 / Mac OS X 10.12.6
Referer: https://www.gbif.org/developer/summary
Window size: width 1680 - height 879
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-07T08:02:50.705Z',mode:absolute,to:'2017-12-07T08:08:50.705Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-07T08:02:50.705Z',mode:absolute,to:'2017-12-07T08:08:50.705Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment] 2017-12-07 08:18
duplicate of https://github.com/gbif/portal-feedback/issues/534

**Closed by MortenHofft** 2017-12-07 08:18 UTC
Labels: content, DE, Under review
