### ISSUE TITLE
accepted scientific names missing from searchable list

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#249] opened 2017-07-13 09:15 UTC
**accepted scientific names missing from searchable list**

Sometimes when I try to search for ScientificNames to filter occurrences of a certain dataset, I try to use a higher rank taxon, usually the Genus.

Usually the Genus shows up among the first options to choice when you begin to type a Scientific Name.
For example, if I type &quot;Quercus&quot;, I immediately see &quot;Quercus L.&quot; at the top of the list, so I can select it.
https://demo.gbif.org/species/2877951

But many other times no genus name are offered to select. And there is no way to type it: whatever you type is changed to the closest matching option .

So, for example, when I type &quot;Plantago&quot; I have no way to select &quot;Plantago L.&quot; 
But I think it is a Scientific name accepted in the backbone:
https://demo.gbif.org/species/3189695

Why does this happen?
It also occurs in the Species page search box.

-----
fbitem-90ca04c707cd953f778e8789ed7ec98e67b20053
Reported by: sant.herbarium@gmail.com
System: Chrome 49.0.2623 / Windows XP 0.0.0
Referer: https://demo.gbif.org/occurrence/gallery?publishing_org=def87a70-0837-11d9-acb2-b8a03c50a862&taxon_key=9221899&taxon_key=3189760&taxon_key=4156127
Window size: width 1008 - height 550
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-13T09:10:39.670Z',mode:absolute,to:'2017-07-13T09:16:39.670Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-13T09:10:39.670Z',mode:absolute,to:'2017-07-13T09:16:39.670Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment] 2017-07-13 10:11
I cannot reproduce this. When typing "Plantag" or "Plantago" Plantago L. comes up at the top in the scientific name filter of the occurrence search.


The species search indeed shows the genus not in the first page:
https://demo.gbif.org/species/search?q=plantago

But its not a dead end as you can request the rank genus explicitly:
https://demo.gbif.org/species/search?q=plantago&rank=GENUS

Well, you should. @MortenHofft, the portal appears to be case sensitive. This does return results
https://demo.gbif.org/species/search?q=Plantago&rank=GENUS

The API does return the genus correctly also given with small letters:
https://api.gbif.org/v1/species/search?datasetKey=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c&q=plantago&rank=GENUS

**Comment by MortenHofft** [comment] 2017-07-19 09:28
To me this looks like an API thing and not a case issue.
Searching for the exact name doesn't return it in suggest. Neither does searching for other cases, stubs etc. 
https://api.gbif.org/v1/species/suggest?datasetKey=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c&limit=10&q=Plantago+L.

```
[
{
"key": 4156127,
"kingdom": "Plantae",
"phylum": "Tracheophyta",
"order": "Lamiales",
"family": "Plantaginaceae",
"genus": "Plantago",
"species": "Plantago lagocephala",
"kingdomKey": 6,
"phylumKey": 7707728,
"classKey": 220,
"orderKey": 408,
"familyKey": 2420,
"genusKey": 3189695,
"speciesKey": 4156127,
"parent": "Plantago",
"parentKey": 3189695,
"nubKey": 4156127,
"scientificName": "Plantago lagocephala Bunge",
"canonicalName": "Plantago lagocephala",
"rank": "SPECIES",
"status": "ACCEPTED",
"higherClassificationMap": {
"6": "Plantae",
"220": "Magnoliopsida",
"408": "Lamiales",
"2420": "Plantaginaceae",
"3189695": "Plantago",
"7707728": "Tracheophyta"
},
"synonym": false,
"class": "Magnoliopsida"
},
{
"key": 8022932,
"kingdom": "Plantae",
"phylum": "Tracheophyta",
"order": "Lamiales",
"family": "Plantaginaceae",
"genus": "Plantago",
"species": "Plantago lagopus",
"kingdomKey": 6,
"phylumKey": 7707728,
"classKey": 220,
"orderKey": 408,
"familyKey": 2420,
"genusKey": 3189695,
"speciesKey": 8022932,
"parent": "Plantago",
"parentKey": 3189695,
"scientificName": "Plantago lagopus L.",
"canonicalName": "Plantago lagopus",
"rank": "SPECIES",
"status": "ACCEPTED",
"higherClassificationMap": {
"6": "Plantae",
"220": "Magnoliopsida",
"408": "Lamiales",
"2420": "Plantaginaceae",
"3189695": "Plantago",
"7707728": "Tracheophyta"
},
"synonym": false,
"class": "Magnoliopsida"
},
{
"key": 8138525,
"kingdom": "Plantae",
"phylum": "Tracheophyta",
"order": "Lamiales",
"family": "Plantaginaceae",
"genus": "Plantago",
"species": "Plantago lasiothrix",
"kingdomKey": 6,
"phylumKey": 7707728,
"classKey": 220,
"orderKey": 408,
"familyKey": 2420,
"genusKey": 3189695,
"speciesKey": 8138525,
"parent": "Plantago",
"parentKey": 3189695,
"scientificName": "Plantago lasiothrix Kunze",
"canonicalName": "Plantago lasiothrix",
"rank": "SPECIES",
"status": "ACCEPTED",
"higherClassificationMap": {
"6": "Plantae",
"220": "Magnoliopsida",
"408": "Lamiales",
"2420": "Plantaginaceae",
"3189695": "Plantago",
"7707728": "Tracheophyta"
},
"synonym": false,
"class": "Magnoliopsida"
},
{
"key": 4155827,
"kingdom": "Plantae",
"phylum": "Tracheophyta",
"order": "Lamiales",
"family": "Plantaginaceae",
"genus": "Plantago",
"species": "Plantago libyca",
"kingdomKey": 6,
"phylumKey": 7707728,
"classKey": 220,
"orderKey": 408,
"familyKey": 2420,
"genusKey": 3189695,
"speciesKey": 4155827,
"parent": "Plantago",
"parentKey": 3189695,
"nubKey": 4155827,
"scientificName": "Plantago libyca Beguinot & Vacc.",
"canonicalName": "Plantago libyca",
"rank": "SPECIES",
"status": "ACCEPTED",
"higherClassificationMap": {
"6": "Plantae",
"220": "Magnoliopsida",
"408": "Lamiales",
"2420": "Plantaginaceae",
"3189695": "Plantago",
"7707728": "Tracheophyta"
},
"synonym": false,
"class": "Magnoliopsida"
},
{
"key": 4155569,
"kingdom": "Plantae",
"phylum": "Tracheophyta",
"order": "Lamiales",
"family": "Plantaginaceae",
"genus": "Plantago",
"species": "Plantago longissima",
"kingdomKey": 6,
"phylumKey": 7707728,
"classKey": 220,
"orderKey": 408,
"familyKey": 2420,
"genusKey": 3189695,
"speciesKey": 4155569,
"parent": "Plantago",
"parentKey": 3189695,
"nubKey": 4155569,
"scientificName": "Plantago longissima Decne.",
"canonicalName": "Plantago longissima",
"rank": "SPECIES",
"status": "ACCEPTED",
"higherClassificationMap": {
"6": "Plantae",
"220": "Magnoliopsida",
"408": "Lamiales",
"2420": "Plantaginaceae",
"3189695": "Plantago",
"7707728": "Tracheophyta"
},
"synonym": false,
"class": "Magnoliopsida"
},
{
"key": 4155836,
"kingdom": "Plantae",
"phylum": "Tracheophyta",
"order": "Lamiales",
"family": "Plantaginaceae",
"genus": "Plantago",
"species": "Plantago leucophylla",
"kingdomKey": 6,
"phylumKey": 7707728,
"classKey": 220,
"orderKey": 408,
"familyKey": 2420,
"genusKey": 3189695,
"speciesKey": 4155836,
"parent": "Plantago",
"parentKey": 3189695,
"nubKey": 4155836,
"scientificName": "Plantago leucophylla Decne.",
"canonicalName": "Plantago leucophylla",
"rank": "SPECIES",
"status": "ACCEPTED",
"higherClassificationMap": {
"6": "Plantae",
"220": "Magnoliopsida",
"408": "Lamiales",
"2420": "Plantaginaceae",
"3189695": "Plantago",
"7707728": "Tracheophyta"
},
"synonym": false,
"class": "Magnoliopsida"
},
{
"key": 4155498,
"kingdom": "Plantae",
"phylum": "Tracheophyta",
"order": "Lamiales",
"family": "Plantaginaceae",
"genus": "Plantago",
"species": "Plantago lundborgii",
"kingdomKey": 6,
"phylumKey": 7707728,
"classKey": 220,
"orderKey": 408,
"familyKey": 2420,
"genusKey": 3189695,
"speciesKey": 4155498,
"parent": "Plantago",
"parentKey": 3189695,
"nubKey": 4155498,
"scientificName": "Plantago lundborgii Sparre",
"canonicalName": "Plantago lundborgii",
"rank": "SPECIES",
"status": "ACCEPTED",
"higherClassificationMap": {
"6": "Plantae",
"220": "Magnoliopsida",
"408": "Lamiales",
"2420": "Plantaginaceae",
"3189695": "Plantago",
"7707728": "Tracheophyta"
},
"synonym": false,
"class": "Magnoliopsida"
},
{
"key": 7582097,
"kingdom": "Plantae",
"phylum": "Tracheophyta",
"order": "Lamiales",
"family": "Plantaginaceae",
"genus": "Plantago",
"species": "Plantago latifolia",
"kingdomKey": 6,
"phylumKey": 7707728,
"classKey": 220,
"orderKey": 408,
"familyKey": 2420,
"genusKey": 3189695,
"speciesKey": 7582097,
"parent": "Plantago",
"parentKey": 3189695,
"scientificName": "Plantago latifolia L.",
"canonicalName": "Plantago latifolia",
"rank": "SPECIES",
"status": "ACCEPTED",
"higherClassificationMap": {
"6": "Plantae",
"220": "Magnoliopsida",
"408": "Lamiales",
"2420": "Plantaginaceae",
"3189695": "Plantago",
"7707728": "Tracheophyta"
},
"synonym": false,
"class": "Magnoliopsida"
},
{
"key": 7684568,
"kingdom": "Plantae",
"phylum": "Tracheophyta",
"order": "Lamiales",
"family": "Plantaginaceae",
"genus": "Plantago",
"species": "Plantago linearis",
"kingdomKey": 6,
"phylumKey": 7707728,
"classKey": 220,
"orderKey": 408,
"familyKey": 2420,
"genusKey": 3189695,
"speciesKey": 7684568,
"parent": "Plantago",
"parentKey": 3189695,
"scientificName": "Plantago linearis Kunth",
"canonicalName": "Plantago linearis",
"rank": "SPECIES",
"status": "ACCEPTED",
"higherClassificationMap": {
"6": "Plantae",
"220": "Magnoliopsida",
"408": "Lamiales",
"2420": "Plantaginaceae",
"3189695": "Plantago",
"7707728": "Tracheophyta"
},
"synonym": false,
"class": "Magnoliopsida"
},
{
"key": 4155937,
"kingdom": "Plantae",
"phylum": "Tracheophyta",
"order": "Lamiales",
"family": "Plantaginaceae",
"genus": "Plantago",
"species": "Plantago lanuginosa",
"kingdomKey": 6,
"phylumKey": 7707728,
"classKey": 220,
"orderKey": 408,
"familyKey": 2420,
"genusKey": 3189695,
"speciesKey": 4155937,
"parent": "Plantago",
"parentKey": 3189695,
"nubKey": 4155937,
"scientificName": "Plantago lanuginosa DC.",
"canonicalName": "Plantago lanuginosa",
"rank": "SPECIES",
"status": "ACCEPTED",
"higherClassificationMap": {
"6": "Plantae",
"220": "Magnoliopsida",
"408": "Lamiales",
"2420": "Plantaginaceae",
"3189695": "Plantago",
"7707728": "Tracheophyta"
},
"synonym": false,
"class": "Magnoliopsida"
}
]
```

**Comment by MortenHofft** [comment] 2017-07-19 09:31
@mdoering I've labeled this as an API issue, let me know if you believe this is a case issue.

**Comment by MortenHofft** [comment] 2017-07-19 09:34
> The API does return the genus correctly also given with small letters:
https://api.gbif.org/v1/species/search?datasetKey=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c&q=plantago&rank=GENUS

Doesn't do so now. It returns this in both API and interface.

![screen shot 2017-07-19 at 11 33 46](https://user-images.githubusercontent.com/6759267/28360589-34756868-6c76-11e7-9cc9-f2f1cf004375.png)

**Comment by MortenHofft** [comment] 2017-07-24 10:26
closed as duplicate of https://github.com/gbif/portal-feedback/issues/219

**Closed by MortenHofft** 2017-07-24 10:26 UTC
Labels: api, bug
