### ISSUE TITLE
Filter dataset downloads (activity) by dates

### ISSUE THREAD

**Issue by PacoPando** [gbif/portal-feedback#1592] opened 2018-10-26 11:18 UTC
As it is now in order to count how many downloads a dataset gets in a time period you need to scroll down and keep the tally manually. This is very cumbersome and prone to error.   

This  is something routinely required, for instance, for collection and institutional annual reports.

**Comment by MortenHofft** [comment] 2018-10-26 11:30
Thanks - I'm closing this as a duplicate of https://github.com/gbif/occurrence/issues/46 and https://github.com/gbif/portal16/issues/761
If you have more to add, please do so on those issues.

**Closed by MortenHofft** 2018-10-26 11:30 UTC
