### ISSUE TITLE
User not informed if they have too many simultaneous downloads

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1825] opened 2019-03-07 11:56 UTC
**Wont let me download any occurrence data via csv. files**

-----

System: Chrome 65.0.3325 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/193058010a93d482bc674b649501feb3:ad82fa22650e611c868e438a1609512ab558086884834f7a3b4f9fe5f54e7668abcb672a9350c5849f6b99f114c482407c7eb16b275a04788184ffb92bebd1b5)
Referer: https://www.gbif.org/occurrence/download?taxon_key=2947295
Window size: width 1920 - height 974
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-07T11:51:46.930Z',mode:absolute,to:'2019-03-07T11:57:46.930Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-07T11:51:46.930Z',mode:absolute,to:'2019-03-07T11:57:46.930Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MattBlissett** [comment] 2019-03-07 12:56
The portal is showing a generic error message when there are too many downloads (usually when a use tries to make a fourth download). The HTTP 420 response should be detected and the user told to wait a while.

**Comment by MortenHofft** [comment] 2019-03-11 09:03
closed as duplicate of https://github.com/gbif/portal16/issues/609

**Closed by MortenHofft** 2019-03-11 09:03 UTC
Labels: bug, portal
