### ISSUE TITLE
image size on pages

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2809] opened 2020-06-07 13:21 UTC
**image size on pages**

Apparently the images on our pages are automatically enlarged by approx. 60% and subsequently create a somewhat blurry appearance.  Could you please leave the original size of the images unchanged?

Thanks
Frans Slieker
Natural History Museum Rotterdam

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/14b91dda413d2d01af3e449e388675ef:fd83d0d4e40900ccb2081144b63c1b8c9b8e0eb9f2d470021e6c645c2ca5b4d225ef4121d173c912181c37bbeb363ea5aabb3fe422ecf723dde2070228188a96)
System: Firefox 77.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/gallery?dataset_key=a307e4d7-1de2-4adc-95d5-a0a8d5f57236&taxon_key=4362739
Window size: width 1920 - height 938
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-07T13:16:28.129Z',mode:absolute,to:'2020-06-07T13:22:28.129Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-07T13:16:28.129Z',mode:absolute,to:'2020-06-07T13:22:28.129Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment] 2020-06-08 09:33
**Why does it behave like this**
We do not know anything about image sizes. We just receive a url. Some images are very high resolution and many mb. Others like these are very low resolution. To avoid downloading huge images in the browser, we scale all images to a fixed size.

**How could we do it differently**
* If images could be published with sizes we could adapt the layout
* If we downloaded them during indexing, then we would know the size.
* Perhaps Thumbor have an option to only scale down?

**Comment by MattBlissett** [comment] 2020-06-08 12:30
The image URLs we get are 425px tall, e.g. http://www.nmr-pics.nl/PICTURES/NMR993000032150A.jpg and look a bit fuzzy. 

On the occurrence page https://www.gbif.org/occurrence/2570106162 they have been stretched horizontally, but the gallery view is fine.

Thumbor will report the size of the original image with `/meta`, but if the image isn't yet downloaded it will (of course) have to download it first: http://api.gbif.org/v1/image/_GWMhiZ5zXHfejaFJIbfwfhVDCY=/meta/http%3A%2F%2Fwww.nmr-pics.nl%2FPICTURES%2FNMR993000032225A.jpg

**Comment by ahahn-gbif** [comment] 2020-07-31 12:18
Could we pick this conversation up again when everybody is back from leave, please?
Following a phone call with Frans today, the situation is that
- we would like to keep image records from the NHM Rotterdam available via GBIF.org
- the legal owner of the images is unhappy with the empty magnification and resulting presentation that the upscaling of image records on GBIF occurrence pages causes
- higher resolution versions are not readily available; they would need to be generated from the original files, including image editing (not a feasible option, given the number of images)
- GBIF's gallery view is not an issue; it is only the enlargement on the occurrence pages that raises concern
- the main site these images are optimized for is WoRMS (e.g. https://www.marinespecies.org/photogallery.php?album=702&pic=73317) - in this page, the image size is static
- reducing the size of the occurrence page images across _all_ datasets would be meaningful if most images would profit from it; however, this is not the case, the majority of images come with a higher resolution
- as GBIF does not download images but accesses the image URLs, information on the image size is not available when the occurrence page is populated
- downloading of images during indexing (or at pages access to occurrence pages) for the purpose of identifying the image size may cause other issues, including performance/lag time (images taking longer to load) and copyright/legal concerns

The simple multimedia extension (http://rs.gbif.org/extension/gbif/1.0/multimedia.xml) does not provide an element for file size specification. The Audubon media description (http://rs.gbif.org/extension/ac/audubon.xml) allows to specify "PixelXDimension" and "PixelYDimension" (see http://rs.gbif.org/extension/ac/audubon.xml and https://terms.tdwg.org/wiki/Audubon_Core_Term_List#exif:PixelXDimension); however, this standard is presently only partially supported by GBIF.

Question: if images were published with sizes, mapping to the Audubon extension @MortenHofft: is that information available to us from indexing, and is it feasible (and desirable) to display such images in exactly that size in occurrence pages, as long as they are _smaller_ than the default? Assuming that we will always want to shrink images that are larger, and that this does not cause any distress to image publishers. Is it meaningful to explore this direction?

**Comment by MattBlissett** [comment] 2020-07-31 12:46
http://www.marinespecies.org/aphia.php?p=image&tid=146905&pic=69395 is the view corresponding to https://www.gbif.org/occurrence/2570106162

Adding `/fit-in` to the URL seems to avoid magnifying the image, but the Portal would need to be changed to cope with that layout: https://api.gbif.org/v1/image/unsafe/fit-in/500x/http%3A%2F%2Fwww.nmr-pics.nl%2FPICTURES%2FNMR993000032225A.jpg

Only 22 datasets have a `PixelXDimension` or `PixelYDimension` field, and not all of those fill it in.  The value wouldn't be available on the occurrence record, but it would be available in the verbatim occurrence record: https://api.gbif.org/v1/occurrence/1324036260/verbatim . It might be simpler to add an exception for just this dataset.

The difficulty for Morten will be also coping with images that are slow to appear (it can take several seconds the first time they are requested), and images that don't appear at all (published URL is not valid).

**Comment by slieker** [comment] 2020-08-01 07:11
The problem obviously lies in the fact that GBIF is not able to ascentain our JPG-file sizes, as we only provide them with a link to the directory on our server where the images are hosted. Wouldn't it be an idea to add a little extra information in the link? This might be be the filesize in kB. When this size is too small, something like "if image size >150kb not scale up to frame size". Sorry, I'm not a programmer, but something like that could do the trick I suppose......  Audubon extension, including additional info like file sizes,  could be the answer, provided this will offer enough possibilities to fix the problem.....
Frans Slieker
Natural History Museum Rotterdam

**Comment by langeveldNMR** [comment] 2020-08-04 15:36
Dear all,

Thank you for your messages and ideas. We would greatly appreciate it if the issue is fixed by 1 October of this year and are happy to cooperate in all ways necessary for a smooth and quick fix.

Sincerely,

Bram Langeveld
curator Natural History Museum Rotterdam

**Closed** 2020-08-17 10:59 UTC
Labels: NL, api, idea, portal

**Comment by MortenHofft** [comment] 2020-08-17 11:01
fit-in should do the trick. Thanks @MattBlissett

**Comment by slieker** [comment] 2020-08-17 11:13
I think it did! Thanks a lot!!

 

Van: Morten Høfft <notifications@github.com> 
Verzonden: maandag 17 augustus 2020 13:02
Aan: gbif/portal-feedback <portal-feedback@noreply.github.com>
CC: slieker <fjas@caiway.net>; Comment <comment@noreply.github.com>
Onderwerp: Re: [gbif/portal-feedback] image size on pages (#2809)

 

fit-in should do the trick. Thanks @MattBlissett <https://github.com/MattBlissett>
