### ISSUE TITLE
Hello, I have downloaded occurences for some invertebrates for the Mediterranean Seaa

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4465] opened 2022-12-11 12:56 UTC
**Hello, I have downloaded occurences for some invertebrates for the Mediterranean Seaa**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d1fb3f7f3a011263983d52a48ea12404:9292146da8334dbc2df9666dd2bd61f1f4bf9d67f973c500f865339fa9bbd7611b0a5f6fd343e7800672c7dce9695330ad291eca530752c850822451918ec1d58428192c24eaa652107b0976b173d28c96507daa106124479e36e433aa0dbd7d) - [Send email](https://www.gbif.org/api/feedback/user/mailto/d1fb3f7f3a011263983d52a48ea12404:9292146da8334dbc2df9666dd2bd61f1f4bf9d67f973c500f865339fa9bbd7611b0a5f6fd343e7800672c7dce9695330ad291eca530752c850822451918ec1d58428192c24eaa652107b0976b173d28c96507daa106124479e36e433aa0dbd7d)
System: Chrome 108.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search
Window size: width 1366 - height 625
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-11T12:51:02.986Z',to:'2022-12-11T12:57:02.986Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-11T12:51:02.986Z',to:'2022-12-11T12:57:02.986Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment] 2022-12-12 07:43
Duplicate of https://github.com/gbif/portal-feedback/issues/4466

**Closed as completed by ManonGros** 2022-12-12 07:43 UTC
Labels: Under review, data content
