### ISSUE TITLE
Can you help me in making me understand what each column name  and its meaning stands for in

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5022] opened 2023-10-27 02:08 UTC
**Can you help me in making me understand what each column name and its meaning stands for in**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d58473e9f108941bfe8422b3f5c55096:4fd5c5bb289aefd2758c572554764c736979aed0e0d199ea625f29c8c19374eb3aa81cffa0e2f7ceb59523ced0371028d387d78d0fbff03d495cd2dcaaa041313fc1bb0934ce465e0e0ee28c1f83df045b7ee1d9ad65bad69a4997025e12eb552928ee7369d7bde5f8943212bd2aa485) - [Send email](https://www.gbif.org/api/feedback/user/mailto/d58473e9f108941bfe8422b3f5c55096:4fd5c5bb289aefd2758c572554764c736979aed0e0d199ea625f29c8c19374eb3aa81cffa0e2f7ceb59523ced0371028d387d78d0fbff03d495cd2dcaaa041313fc1bb0934ce465e0e0ee28c1f83df045b7ee1d9ad65bad69a4997025e12eb552928ee7369d7bde5f8943212bd2aa485)
System: Chrome 118.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?country=IN&dataset_key=4fa7b334-ce0d-4e88-aaae-2e0c138d049e&publishing_country=IN&advanced=1&iucn_red_list_category=CR
Window size: width 1536 - height 707
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-27T02:03:53.398Z',to:'2023-10-27T02:09:53.398Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-27T02:03:53.398Z',to:'2023-10-27T02:09:53.398Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ktotsum** [comment] 2023-10-27 07:13
duplicate of https://github.com/gbif/portal-feedback/issues/5023

**Closed as completed** 2023-10-27 07:14 UTC
Labels: question
