### ISSUE TITLE
Hi. i don't find a legend for the map, like ones with dark grey bacground and purple small squares...why some are more pink and some more purple? thanks a lot

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2451] opened 2020-02-27 09:39 UTC
**Hi. i don&#39;t find a legend for the map, like ones with dark grey bacground and purple small squares...why some are more pink and some more purple? thanks a lot**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b4ddb891a07247f135d8134def469a7e:318bb3a6412667f4a7ae134627f5144858e29cd589e136800ecb2bf92c4067eb242b798ee5d854627d7e9449034f587e268e77cc9514bc990d59abd72cb9b62a)
System: Chrome 80.0.3987 / Windows 10.0.0
Referer: https://www.gbif.org/search?q=legend
Window size: width 1536 - height 722
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-27T09:34:16.880Z',mode:absolute,to:'2020-02-27T09:40:16.880Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-27T09:34:16.880Z',mode:absolute,to:'2020-02-27T09:40:16.880Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment] 2020-02-28 08:43
Replied by email.

**Comment by MortenHofft** [comment] 2020-02-28 08:44
A very reasonable request. 

Neither the current nor the previous portal have had this. That said it has only been mentioned once before - I think that is an indication that the majority of users can read the map. 

Ideally this would be part of the API as the frontend do not know the color schemes and threshold that are used by the backend. We could make hardcoded copies in the frontend, but those will likely grow stale over time.

**Comment by MortenHofft** [comment] 2021-03-02 05:15
duplicate of https://github.com/gbif/portal-feedback/issues/563

**Closed by MortenHofft** 2021-03-02 05:15 UTC
Labels: NL, api, portal, question
