### ISSUE TITLE
species population map isn't working in ie11

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#6] opened 2016-12-20 14:54 UTC
**species population map isn&#39;t working in ie11**

the map isn&#39;t interactive in ie11

-----
fbitem-f0b1d8e8c6811b830ef2f932fb5cf1be7ba9cf0a

System: Chrome 54.0.2840 / Mac OS X 10.11.6
Referer: http://localhost:7000/tools/species-population
Window size: width 1331 - height 1076

**Comment by MortenHofft** [comment] 2016-12-20 20:56
duplicate of https://github.com/gbif/portal-feedback/issues/7

**Closed by MortenHofft** 2016-12-20 20:56 UTC
