### ISSUE TITLE
wrong location

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2089] opened 2019-07-11 13:50 UTC
**wrong location**

The following pages contain wrong country information. "France" is indicated as the location, but actually the location as written on the object slide is '1 km SSW of Grasz, near Regensburg (Germany)'.

-----

System: Chrome 75.0.3770 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/95081f2a16924c69ad0dd395329fe37c:f568b326bd275b8b571ffaab4ffd79592c65037edc69489a703d9c5fa7be2f2017ba33bcc9f873c5da7518b5637eae707bb07f18e83b77262cca898b7f000a1f)
Referer: https://www.gbif.org/occurrence/1227540967
Window size: width 1920 - height 937
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-11T13:45:51.947Z',mode:absolute,to:'2019-07-11T13:51:51.947Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-11T13:45:51.947Z',mode:absolute,to:'2019-07-11T13:51:51.947Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment] 2019-07-23 08:44
https://github.com/gbif/portal-feedback/issues/2089
https://github.com/gbif/portal-feedback/issues/2090
https://github.com/gbif/portal-feedback/issues/2091
https://github.com/gbif/portal-feedback/issues/2092

**Comment by ManonGros** [comment] 2019-07-23 09:03
duplicate of https://github.com/gbif/portal-feedback/issues/2090

**Closed by ManonGros** 2019-07-23 09:03 UTC
Labels: NL, data content
