### ISSUE TITLE
API use for excluding records with particular issues

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#610] opened 2017-10-29 17:09 UTC
**API use for excluding records with particular issues**

How should this work?

https://www.gbif.org/occurrence/download/0002342-171025204727650

I wanted to get all records which do not show the given issues - I am not sure that "equals" is the correct way to specify the individual issue checks

-----
fbitem-ca43062074ba35d14c8883ac6c6a10098be083bc
User provided contact info: dhobern@gbif.org
System: Chrome 61.0.3163 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/download/0002342-171025204727650
Window size: width 1300 - height 901
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-29T17:04:25.118Z',mode:absolute,to:'2017-10-29T17:10:25.118Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-29T17:04:25.118Z',mode:absolute,to:'2017-10-29T17:10:25.118Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment] 2019-08-08 13:01
I can't reproduce this.

Roughly your filter (taxon + none of (several issues)): https://www.gbif-uat.org/occurrence/download/0000068-190802075855554 — 75,695 records

The opposite, (taxon + one or more of (several issues)): https://www.gbif-uat.org/occurrence/download/0000069-190802075855554 — 17,601 records

Just the taxon https://www.gbif-uat.org/occurrence/download/0000070-190802075855554 — 93,296 as expected.

Maybe we fixed it without remembering to close the issue.

**Closed by MattBlissett** 2019-08-08 13:01 UTC
Labels: api, bug

**Comment by MattBlissett** [comment] 2019-08-08 13:43
In fact, this shows the same problems as https://github.com/gbif/occurrence/issues/12, but I'll leave this closed as that issue is in the appropriate repository.
