### ISSUE TITLE
occurrence-id filter not working?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#235] opened 2017-07-04 12:33 UTC
**occurrence-id filter not working?**

I was browsing this dataset:
https://demo.gbif.org/occurrence/search?dataset_key=10734a60-7ed1-11df-8c4a-0800200c9a66&amp;advanced=1

I want to find this particular occurrence:
https://demo.gbif.org/occurrence/225941757
As you can see, it contains this info:
Catalogue Number	8850-A
Occurrence ID	SANT:SANT-Lich:8850-A

When I browse the whole dataset and use the catalognumber filter for &quot;8850-A&quot;, I find the specimen.

But if I try to find the specimen using the occurrenceID filter with &quot;SANT:SANT-Lich:8850-A&quot;, I get no results.

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482

System: Chrome 49.0.2623 / Windows XP 0.0.0
Referer: https://demo.gbif.org/occurrence/search?catalog_number=8850-a&dataset_key=10734a60-7ed1-11df-8c4a-0800200c9a66&advanced=1
Window size: width 1024 - height 707
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-04T12:28:37.278Z',mode:absolute,to:'2017-07-04T12:34:37.278Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-04T12:28:37.278Z',mode:absolute,to:'2017-07-04T12:34:37.278Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment] 2017-07-04 12:53
No contact info for the user
duplicate of https://github.com/gbif/portal-feedback/issues/200

**Closed by MortenHofft** 2017-07-04 12:53 UTC
Labels: bug, Under review

**Comment by dgasl** [comment] 2017-07-04 17:27
Sorry. 
For some reason my login info was not reported 
(perhaps I started writing the issue before was I logged).

But I have to say the behaviour is not exactly the same as in issue [#200](https://github.com/gbif/portal-feedback/issues/200) 

In my case, the API works well (it returns information):
http://api.gbif.org/v1/occurrence/search?occurrence_id=SANT:SANT-Lich:8850-A

**Comment by MortenHofft** [comment] 2017-07-04 18:01
It is completely ok to leave anonymous feedback. Just difficult to respond to :)

And you are right. The user login is not carried to feedback. I chose not to but haven't implanted the option to do so. That would be useful. Especially for those users that take the effort to provide feedback on a regular basis.

I will look into it. It sounds like there is several issues then. Thanks.

**Comment by dgasl** [comment] 2017-07-05 08:06
OK, I got some more interesting observations.
I think this is definitely not related to API, but a bug in the way portal process forms:

The **API link** above (which works OK, since it returns data) had occurrenceID letters in original case.
It is like that because I constructed the link by hand.

But the link which is constructed by the **new demo portal** when I search an occurrenceID is always in lowercase. Like this:
occurrenceID I put in search inputbox: **SANT:SANT-Lich:8850-A**
URL constructed by the portal: https://demo.gbif.org/occurrence/search?dataset_key=10734a60-7ed1-11df-8c4a-0800200c9a66&occurrence_id=sant:sant-lich:8850-a&advanced=1

So, the new demo portal does both convert my search concept to lowercase, and constructs a URL in lowercase. 

If I construct the same URL by hand without changing occurrenceID original case, then it returns results!!
https://demo.gbif.org/occurrence/search?dataset_key=10734a60-7ed1-11df-8c4a-0800200c9a66&occurrence_id=SANT:SANT-Lich:8850-A&advanced=1

The **"old" portal** does preserve the original case I type when searching for an occurrenceID. So the constructed links do also work, like this:
http://www.gbif.org/occurrence/search?OCCURRENCE_ID=SANT%3ASANT-Lich%3A8850-A&DATASET_KEY=10734a60-7ed1-11df-8c4a-0800200c9a66

I had actually reported this odd behaviour of GBIF changing cases before:
http://dev.gbif.org/issues/browse/PF-2758
API **returned wrong results** (faceted scientific name where wrong because genus and authors were converted to lowercase, or something like that).

It is quite annoying to see people or plant names in lowercase, but I think this is the first time I detect it affects results **NOT being returned**. 

It worths the pain to look carefully into other possible errors caused by this "I don't mind case" policy  ;)

**Comment by MortenHofft** [comment] 2017-07-05 09:04
As mentioned in the issue that remained open it is case and is fixed.

**Comment by dgasl** [comment] 2017-07-05 09:12
OK.  Looks like I was already typing the above stuff when you commented it in the other issue.

Thanks a lot

**Comment by MortenHofft** [comment] 2017-07-05 09:22
It is now also deployed: https://demo.gbif.org/occurrence/search?occurrence_id=SANT:SANT-Lich:8850-A&advanced=1
