### ISSUE TITLE
Hi!I'm collecting data for my thesis, but when I go to download a text appears that says:

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5322] opened 2024-05-09 08:25 UTC
**Hi!I&#39;m collecting data for my thesis, but when I go to download a text appears that says:**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/af78e42e40b84e2bba61254ec9d8bbd3:9619417a38544d584e7efcb30bcafe9a90a3c8fd7b9f11deafe2fd396cbb672eb85b8a135926ffc6e3cd0bb6a497910e849c324ff4d4a36e8e33d21620bb0a18a79134b9992903008029c7d20d0d8a5abf43c7e028225fde555c9b524cf555fc6eb02f3d7a9714b3a1b555289d210b92) - [Send email](https://www.gbif.org/api/feedback/user/mailto/af78e42e40b84e2bba61254ec9d8bbd3:9619417a38544d584e7efcb30bcafe9a90a3c8fd7b9f11deafe2fd396cbb672eb85b8a135926ffc6e3cd0bb6a497910e849c324ff4d4a36e8e33d21620bb0a18a79134b9992903008029c7d20d0d8a5abf43c7e028225fde555c9b524cf555fc6eb02f3d7a9714b3a1b555289d210b92)
System: Chrome 124.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download?q=Morphocarabus%20aemginosus&occurrence_status=present
Window size: width 1536 - height 730
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-05-09T08:20:25.720Z',to:'2024-05-09T08:26:25.720Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-05-09T08:20:25.720Z',to:'2024-05-09T08:26:25.720Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by CecSve** [comment] 2024-05-10 18:22
duplicate of https://github.com/gbif/portal-feedback/issues/5323 and therefore closing

**Closed as completed by CecSve** 2024-05-10 18:22 UTC
Labels: bug, Under review
