### ISSUE TITLE
Wrong superior taxonomy

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1324] opened 2018-04-24 16:45 UTC
**Wrong superior taxonomy**

This species is a Bird but the superior taxonomy indicates is a Reptile O.o. Which is very problematic when using the species matching or API tools.

-----

User provided contact info: @camiplata
System: Chrome 65.0.3325 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/84c1be3a7cc4a014e606030e6c35be6b:2a6ca55bf7dbbc88da0537b42dbcd0c06a62da69c5cec54460b83c604c1b1b01ba11647faa0f97a49f2101b9f2221d4cf29a2bd8d7a6515f116f0881a6dc026d)
Referer: https://www.gbif.org/species/2477560
Window size: width 1440 - height 834
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-24T16:40:16.053Z',mode:absolute,to:'2018-04-24T16:46:16.053Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-24T16:40:16.053Z',mode:absolute,to:'2018-04-24T16:46:16.053Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by thomasstjerne** [comment] 2018-04-25 06:30
Closing as duplicate of #1213

**Closed by thomasstjerne** 2018-04-25 06:30 UTC
Labels: Under review, data content
