### ISSUE TITLE
add API call to get MAP legend?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3291] opened 2021-03-03 08:47 UTC
**add API call to get MAP legend?**

Just an idea to help libraries produce accurate legend:
Have an API call per map style that returns a JSON of the legend.

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/38bb9df5cbdc441e5fe912148c9a97ff:2a24fb983617b03d0e2b0b36bc91d6ea6ab1fae38d0835d5d3c3c4ba9875e8d98028afbff9764c1937fa233bcf4fb3829addcd5b1d052d8d82c61a1d7965abc4)
System: Safari 14.0.3 / Mac OS X 10.15.6
Referer: https://www.gbif.org/developer/maps
Window size: width 1492 - height 794
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-03T08:42:46.766Z',to:'2021-03-03T08:48:46.766Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-03T08:42:46.766Z',to:'2021-03-03T08:48:46.766Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment] 2021-03-04 06:49
Duplicate of https://github.com/gbif/portal-feedback/issues/563#issuecomment-337570041 ?

**Comment by ManonGros** [comment] 2021-03-04 07:07
yes! closing

**Closed as completed by ManonGros** 2021-03-04 07:07 UTC
Labels: idea, Under review
