### ISSUE TITLE
Occurrences Map Key

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3283] opened 2021-03-01 20:51 UTC
**Occurrences Map Key**

Maps of occurrences have yellow and orange spots, what is the difference between them? Thank you!

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e33cdef9fc3050949464a69bc26c5fc3:9f2eabfdec67f9c020c6f357f55e3b70f8ee6bafbfe24d856760c4139d9ecd54fe44da9b47d4bbbe7fa1d2eb192b555b6df25ffcfc45b697e98f7d91367ef8d5)
System: Chrome 88.0.4324 / Mac OS X 11.2.1
Referer: https://www.gbif.org/occurrence/map?basis_of_record=HUMAN_OBSERVATION&has_coordinate=true&has_geospatial_issue=false&taxon_key=5870368&year=2010,2021&advanced=1&occurrence_status=present
Window size: width 1440 - height 821
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-01T20:46:03.708Z',to:'2021-03-01T20:52:03.708Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-01T20:46:03.708Z',to:'2021-03-01T20:52:03.708Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment] 2021-03-02 05:16
duplicate of https://github.com/gbif/portal-feedback/issues/563

**Comment by jlegind** [comment] 2021-03-02 07:48
I replied to the user:

I regret that this is not well documented.
However, the color intensity follows this schema (the ‘dot-fill’ being hexadecimal color values):

[total <=    10] { dot-fill: #FFFF00;  }
           [total >    10][total <=   100] { dot-fill: #FFCC00;  }
           [total >   100][total <=  1000] { dot-fill: #FF9900;  }
           [total >  1000][total <= 10000] { dot-fill: #FF6600;  }
           [total > 10000]                 { dot-fill: #D60A00;  }

**Closed as completed by jlegind** 2021-03-02 07:48 UTC
Labels: question, SG
