### ISSUE TITLE
Link to a page knowing only its TSN (taxonomic serial number) ?

### ISSUE THREAD

**Issue by WPCleaner** [gbif/portal-feedback#3978] opened 2022-03-16 15:21 UTC
With the previous site, it was possible to access a page knowing only the TSN : for example, http://www.cbif.gc.ca/acp/fra/siti/regarder?tsn=180092 would point to _Homo sapiens_ Linnaeus, 1758, the equivalent of https://www.gbif.org/fr/species/2436436

I couldn't find a way to do the same with the new site : is it possible ? if not, is it possible to add this feature ?

Use case: on French Wikipedia, there's an [ITIS template](https://fr.wikipedia.org/wiki/Mod%C3%A8le:ITIS), that was providing a link to the page on CBIF based on it's TSN. It's not working anymore of course... The current options we have : 
* Have a way to reference a page on GBIF using a TSN
* Modify the template to have only the link to ITIS (in English), instead of both a link to French page and English page
* More complex options requiring going through each use of the template to provide GBIF identifiers (but how do we find them from the TSN...)

Any idea ? Thanks in advance

**Comment by MortenHofft** [comment] 2022-03-17 05:09
> Just to clarify: gbif.org isn't a new site to replace CBIF.gc.ca. It has existed all along and might not have the same functionalities as CBIF.

It sounds like a duplicate of this issue/feature request
https://github.com/gbif/portal16/issues/1453

We have an undocumented similar feature:
https://www.gbif.org/species/first?sourceId=180092&datasetKey=9ca92552-f23a-41a8-a140-01abaa31c931

The datasetKey is the ITIS dataset. And the sourceID is whatever the ITIS dataset use as their ID. If there are multiple results then it will show the search results, if there is only one result it will [go straight to that page](https://www.gbif.org/species/102119417). 

It **will not redirect** you to the GBIF backbone page for that species (the url https://www.gbif.org/species/2436436 you pasted above). It will show you the ITIS view of that taxon. It might or might not also exist in the GBIF backbone. In this case it does and can be accessed by clicking the `View in GBIF backbone`-button.

I guess this relates to this comment https://github.com/gbif/portal16/issues/1453#issuecomment-746176339

**Closed as completed** 2022-03-17 05:22 UTC

**Comment by MortenHofft** [comment] 2022-03-17 08:09
I've added a target parameter. It will redirect to the backbone version of the taxon if it has a mapping. Else it will show the version from the ITIS dataset
https://www.gbif.org/species/first?sourceId=180092&datasetKey=9ca92552-f23a-41a8-a140-01abaa31c931&target=backbone

It should be available online in about 5 minutes

**Comment by WPCleaner** [comment] 2022-03-21 08:39
Thanks a lot @MortenHofft  ! We'll see how we can use it on French Wikipedia !
