### ISSUE TITLE
Cheers; my name is Renzo Seminario, author of the publication Collembola of the Campanet cave (Mallorca, Balearic Islands), with descriptions of new species of Pseudosinella (Entomobryidae) and Oncopodura (Oncopoduridae); I would like to clarify that in my scientific names my last name is being misquoted by placing "CORDOBA" being the real name "CORDOVA". I would appreciate correcting that mistake.  thank you very much.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2303] opened 2019-11-21 06:56 UTC
**Cheers; my name is Renzo Seminario, author of the publication Collembola of the Campanet cave (Mallorca, Balearic Islands), with descriptions of new species of Pseudosinella (Entomobryidae) and Oncopodura (Oncopoduridae); I would like to clarify that in my scientific names my last name is being misquoted by placing &quot;CORDOBA&quot; being the real name &quot;CORDOVA&quot;. I would appreciate correcting that mistake. thank you very much.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4d0a28f4d7bb5f1faf68cda473266beb:d79bfb77533c1996a6cd80221be8af713152114e42b4ec69c153ba3957883d02b1bc7520d1c5daa1eb57a6664023e57decb91b943642e5f009c2c42b9c8b7ac2)
System: Chrome 78.0.3904 / Windows 10.0.0
Referer: https://www.gbif.org/es/user/profile
Window size: width 1366 - height 657
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-21T06:51:30.068Z',mode:absolute,to:'2019-11-21T06:57:30.068Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-21T06:51:30.068Z',mode:absolute,to:'2019-11-21T06:57:30.068Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment] 2019-11-25 09:23
closed as duplicate of https://github.com/gbif/portal-feedback/issues/2304

**Closed by MortenHofft** 2019-11-25 09:23 UTC
Labels: Under review, data content
