### ISSUE TITLE
Hey,

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4175] opened 2022-07-13 10:06 UTC
**Hey,**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d066388ce0599a199a4a82ec00db03f8:66a729e44da0bb6b5842f613cbf7b9a023a3f2d2875fde2b0af24610f2de016c317347bbefb1a2b1009b0f6892c99b43e9c653046698e791f696204815be021c4fece0c9b170cc3bf134d84cdc2444a3a2e18e5eaa604bbe29321213099e2a8746eeb457b1feaa026c4bccb5a54632623299e300f02c3bb00a7ca8cfdbb3bdc18e59668c02531d335271ac3378bac7d3) - [Send email](https://www.gbif.org/api/feedback/user/mailto/d066388ce0599a199a4a82ec00db03f8:66a729e44da0bb6b5842f613cbf7b9a023a3f2d2875fde2b0af24610f2de016c317347bbefb1a2b1009b0f6892c99b43e9c653046698e791f696204815be021c4fece0c9b170cc3bf134d84cdc2444a3a2e18e5eaa604bbe29321213099e2a8746eeb457b1feaa026c4bccb5a54632623299e300f02c3bb00a7ca8cfdbb3bdc18e59668c02531d335271ac3378bac7d3)
System: Chrome 103.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/derived-dataset/about
Window size: width 1680 - height 850
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-07-13T10:01:55.202Z',to:'2022-07-13T10:07:55.202Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-07-13T10:01:55.202Z',to:'2022-07-13T10:07:55.202Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment] 2022-07-13 10:26
duplicate of https://github.com/gbif/portal-feedback/issues/4176

**Closed as completed by ManonGros** 2022-07-13 10:26 UTC
Labels: question, Under review
