### ISSUE TITLE
Login not possilbe

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#172] opened 2017-04-14 17:46 UTC
**Login not possilbe**

-----
fbitem-67cbf865735ab20856e1e6649eab1c4073bc341e

System: Chrome 57.0.2987 / Windows 7 0.0.0
Referer: https://demo.gbif.org/
Window size: width 1366 - height 634
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-14T17:41:22.407Z',mode:absolute,to:'2017-04-14T17:47:22.407Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-14T17:41:22.407Z',mode:absolute,to:'2017-04-14T17:47:22.407Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by timrobertson100** [comment] 2017-04-14 18:01
I'm very sorry about this.

Login is possible using your username (not email address) if you have created an account on www.gbif.org.  Accounts are synchronised every 15 minutes, so it might take some minutes before log in is possible.

These issues will of course be corrected before the demo site is released.

**Comment by MattBlissett** [comment] 2017-04-27 16:20
Duplicate of #180.

**Closed by MattBlissett** 2017-04-27 16:20 UTC
Labels: bug, Under review
