### ISSUE TITLE
Replace/delete dataset and link to new dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4450] opened 2022-11-30 22:27 UTC
**Replace/delete dataset and link to new dataset**

Hello, 
I'd like to request help linking an old, now defunct dataset to a replacement dataset while retaining citations, metrics, etc. of the old dataset. In previous contact with GBIF Helpdesk, this dataset was provided as an example of what I'd like to do: https://www.gbif.org/dataset/fc003253-5eee-414e-84c8-817e12bdb708

The old dataset is:
https://www.gbif.org/dataset/7e36d9b6-f762-11e1-a439-00145eb45e9a

The new dataset is:
https://www.gbif.org/dataset/defb9a47-c1a7-4fb2-9a0b-2da7c5260cad

Thanks for your help!
Jason

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6b21d5302083776524882dfb7f8b04a6:f9db70c5f0bba33dcf072bb11ceb610bdeb484da6dae25a7f4c3bd23c7f836c0c765db5cf2d2c1a62837fdee823a6b5c7a768d36a05891eb102fa6a119a424c8736ef45bede4062ac28411d0b0f3f2afeb2a08a18f23a3a625e50e745b101f54e51ca9cbea3aacb11d0c5344da1bbb3a75a45ee82650a50977c13925808055bf) - [Send email](https://www.gbif.org/api/feedback/user/mailto/6b21d5302083776524882dfb7f8b04a6:f9db70c5f0bba33dcf072bb11ceb610bdeb484da6dae25a7f4c3bd23c7f836c0c765db5cf2d2c1a62837fdee823a6b5c7a768d36a05891eb102fa6a119a424c8736ef45bede4062ac28411d0b0f3f2afeb2a08a18f23a3a625e50e745b101f54e51ca9cbea3aacb11d0c5344da1bbb3a75a45ee82650a50977c13925808055bf)
System: Firefox 107.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/contact-us
Window size: width 1440 - height 762
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-30T22:22:55.726Z',to:'2022-11-30T22:28:55.726Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-30T22:22:55.726Z',to:'2022-11-30T22:28:55.726Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment] 2022-12-01 12:34
The old dataset has been registered as a duplicate of the new one, and the old dataset has been deleted.

**Closed as completed by CecSve** 2022-12-01 12:34 UTC
Labels: question, registry
