### ISSUE TITLE
Please add the species Foa fo Jordan & Seale, 1905 to your taxonomic backbone. See https://www.catalogueoflife.org/data/taxon/6JBY8

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5308] opened 2024-04-30 10:04 UTC
**Please add the species Foa fo Jordan &amp; Seale, 1905 to your taxonomic backbone. See `https://www.catalogueoflife.org/data/taxon/6JBY8`**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a4f232df0a5d059cd5359becc46e042d:9500c86162395257f75994f5ede6ac4e9d614a0b9449bef57bedf727fbae1c6e5f8913285aa698e8b6cfc12b1dc5a313568d5fbf8cd60e302cb5aac93602e550492ab006ea9a1a50e5c9112944559651443cd604a93611e8042f1c081b5c19f00937ddab537c25f7af706d3842b8d4e3af21523682cdb825a38fa762f34d7fb5afd6bc1ff22e123df2e14a25064a41f7) - [Send email](https://www.gbif.org/api/feedback/user/mailto/a4f232df0a5d059cd5359becc46e042d:9500c86162395257f75994f5ede6ac4e9d614a0b9449bef57bedf727fbae1c6e5f8913285aa698e8b6cfc12b1dc5a313568d5fbf8cd60e302cb5aac93602e550492ab006ea9a1a50e5c9112944559651443cd604a93611e8042f1c081b5c19f00937ddab537c25f7af706d3842b8d4e3af21523682cdb825a38fa762f34d7fb5afd6bc1ff22e123df2e14a25064a41f7)
System: Chrome 123.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/1230435610
Window size: width 1920 - height 919
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-04-30T09:59:15.167Z',to:'2024-04-30T10:05:15.167Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-04-30T09:59:15.167Z',to:'2024-04-30T10:05:15.167Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING
datasetKey: 1aaec653-c71c-4695-9b6e-0e26214dd817
publishingOrgKey: cecc196e-f262-4986-a88a-6adf035dca0e

**Comment by CecSve** [comment] 2024-05-10 18:26
Duplicate of https://github.com/gbif/portal-feedback/issues/5326 and will close

**Closed as completed by CecSve** 2024-05-10 18:26 UTC
Labels: data content, backbone, ZA
