### ISSUE TITLE
Download events per year

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#807] opened 2018-02-01 14:47 UTC
**Download events per year**

For our yearly KPI's / statistics, it would be very useful if we could filter the download events of an occurrence dataset per year. I notice the dates of download events are stored, so in theory this would be possible to implement. Are there plans already to do this and if not, would this be possible?

Thanks in advance,
Sander Pieterse (Naturalis Biodiversity Center)

-----
fbitem-dataset889c91a3-614f-4355-8df8-b6d0260a118c

System: Chrome 63.0.3239 / Windows 7 0.0.0
Referer: https://www.gbif.org/dataset/889c91a3-614f-4355-8df8-b6d0260a118c/activity
Window size: width 1920 - height 949
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-01T14:42:40.734Z',mode:absolute,to:'2018-02-01T14:48:40.734Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-01T14:42:40.734Z',mode:absolute,to:'2018-02-01T14:48:40.734Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment] 2018-02-01 15:13
This isn't possible at present.

If you are able to use the APIs, the data is available at `http://api.gbif.org/v1/occurrence/download/dataset/889c91a3-614f-4355-8df8-b6d0260a118c` (add `?limit=1000&offset=1000` to the end get more records, then increase offset). It's a bit slow.

Alternatively, you can contact helpdesk@gbif.org for a report.

**Comment by MortenHofft** [comment] 2018-02-05 13:56
See also issue https://github.com/gbif/portal16/issues/563 for the feature request

**Comment by MortenHofft** [comment] 2018-02-05 13:57
closing as duplicate of gbif/portal16#563

**Closed by MortenHofft** 2018-02-05 13:57 UTC
Labels: api, idea
