### ISSUE TITLE
Add filter by taxon list function to portal for downloads

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#747] opened 2018-01-03 09:27 UTC
**Add filter by taxon list function to portal for downloads**

As discussed with Matt and Jan, this is probably one of the commonest helpdesk request.

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
User provided contact info: @dschigel
System: Firefox 52.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/search
Window size: width 1920 - height 1077
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-03T09:22:43.643Z',mode:absolute,to:'2018-01-03T09:28:43.643Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-03T09:22:43.643Z',mode:absolute,to:'2018-01-03T09:28:43.643Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment] 2018-01-03 12:14
Thanks. How do you envision it should work and what would be the requirements based on your experience from helpdesk?

**Comment by MortenHofft** [comment] 2018-01-03 12:16
duplicate of https://github.com/gbif/portal16/issues/143

**Closed by MortenHofft** 2018-01-03 12:16 UTC
Labels: idea, Needs clarification, portal
