### ISSUE TITLE
Consistency issue with the number of occurrences within a dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1430] opened 2018-06-27 15:24 UTC
**Consistency issue with the number of occurrences within a dataset**

Hi all,

We noticed a problem with the number of occurrences displayed in the activity tab of this dataset: `https://www.gbif.org/dataset/54bae6ef-8b4e-4ad3-8729-c4296299e5c7/activity` ; the dataset contains a total of 49,999 occurrences, but some download events (e.g. 10.15468/dl.slsqfk)  display 99,997 occurrences downloaded from this dataset (it seems to be the case for all donwloads when someone downloads all of the datasets at once, with no filters used)

-----

User provided contact info: pamerlon@gbif.fr
System: Chrome 67.0.3396 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/621a6b7fb0f3004526293747fef8cc6f:4e699865f0111a23769bc9cb1a8092a630f9759d781684c1b541f88e1bb3bc26f539004de6cecc6ad997bf6e3716f8fa5b3e48df4ff8ef75d95fdfe5b18e64fb)
Referer: https://www.gbif.org/dataset/54bae6ef-8b4e-4ad3-8729-c4296299e5c7/activity
Window size: width 1440 - height 794
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-27T15:19:26.970Z',mode:absolute,to:'2018-06-27T15:25:26.970Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-27T15:19:26.970Z',mode:absolute,to:'2018-06-27T15:25:26.970Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment] 2018-11-22 12:38
Duplicate of https://github.com/gbif/portal-feedback/issues/1600, essentially.

**Closed by MattBlissett** 2018-11-22 12:38 UTC
Labels: api, bug
