### ISSUE TITLE
How many records per dataset type?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#699] opened 2017-12-05 13:03 UTC
**How many records per dataset type?**

I often need to check how many records are there published as sampling event data - apparently, there is no easy no-download way to know that? Same would be neat to have for the checklists - how many names are there?

Or if there is a way to see those stats, it is not easy to find it. My preferred display would be "NNN,NNN records in 142 [dataset type] datasets".

-----
fbitem-0059f96b33a12ae38a9a2449c0865b3a3cdfe76c
User provided contact info: @dschigel
System: Firefox 52.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/dataset/search?type=SAMPLING_EVENT
Window size: width 1920 - height 1077
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-05T12:58:35.404Z',mode:absolute,to:'2017-12-05T13:04:35.404Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-05T12:58:35.404Z',mode:absolute,to:'2017-12-05T13:04:35.404Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment] 2018-01-09 15:06
@dschigel closing as duplicate of [your new issue](https://github.com/gbif/portal-feedback/issues/699) about what - as far as I can see is- is the exact same issue ?

**Closed by MortenHofft** 2018-01-09 15:06 UTC
Labels: api, idea

**Comment by dschigel** [comment] 2018-01-09 16:31
Correct, I keep dreaming about this :)
