### ISSUE TITLE
The plant in the photo is a Jasminum a

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2914] opened 2020-07-27 19:50 UTC
**The plant in the photo is a Jasminum a**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d2441df7bfd8d427128365a63b33926b:da4da90f6f135f276b650017bf6c5de02d98348d7b3ec779f3ad5a9dcb5b108063af412b0615304e7cbb3e9e500ea19ee29747367deeb57fdf670bf766bbb632)
System: Firefox 52.0.0 / Windows XP.0.0
Referer: https://www.gbif.org/occurrence/2644965648
Window size: width 1280 - height 643
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-27T19:45:19.200Z',mode:absolute,to:'2020-07-27T19:51:19.200Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-27T19:45:19.200Z',mode:absolute,to:'2020-07-27T19:51:19.200Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 7a3679ef-5582-4aaa-81f0-8c2545cafc81
publishingOrgKey: da86174a-a605-43a4-a5e8-53d484152cd3

**Comment by ManonGros** [comment] 2020-10-06 08:45
Duplicate of https://github.com/gbif/portal-feedback/issues/2915

**Closed by ManonGros** 2020-10-06 08:45 UTC
Labels: data content
