### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4652] opened 2023-03-29 12:41 UTC
**Hello,**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2d4db63fc48a5587ee61ddbd0ced62a3:bfab0dcfc8691ce99fdb512ec9510c6bdb0c31e9a0d8ccefe6db5d351ea05723e3f7f109c7ed0a7cb4cbf34f0512e0f96e1cdcfd53fa7ba6e614ceb1e7fab75ee41cb7ef5e091239c8a22dc54fa041f1853d5be675d4e338a218f272319458590cdaf19a85e9a4acaa5a26760cfa1160) - [Send email](https://www.gbif.org/api/feedback/user/mailto/2d4db63fc48a5587ee61ddbd0ced62a3:bfab0dcfc8691ce99fdb512ec9510c6bdb0c31e9a0d8ccefe6db5d351ea05723e3f7f109c7ed0a7cb4cbf34f0512e0f96e1cdcfd53fa7ba6e614ceb1e7fab75ee41cb7ef5e091239c8a22dc54fa041f1853d5be675d4e338a218f272319458590cdaf19a85e9a4acaa5a26760cfa1160)
System: Chrome 111.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/3843064790
Window size: width 1536 - height 688
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-29T12:36:34.063Z',to:'2023-03-29T12:42:34.063Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-29T12:36:34.063Z',to:'2023-03-29T12:42:34.063Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 12f7588e-f812-4da0-85e9-05f655fa538a
publishingOrgKey: 1928bdf0-f5d2-11dc-8c12-b8a03c50a862

**Comment by ManonGros** [comment] 2023-03-30 08:38
Duplicate of https://github.com/gbif/portal-feedback/issues/4653

**Closed as completed by ManonGros** 2023-03-30 08:38 UTC
Labels: Under review, data content, FR
