### ISSUE TITLE
Area selector for Location does not seem to work

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1185] opened 2018-02-20 23:25 UTC
**Area selector for Location does not seem to work**

Selecting a polygon in the Location map during search for occurrences yields unpredictable results. In most cases, occurrences are selected outside the boundaries of the polygon. For example, if I draw a rectangle inside Spain it returns records with coordinates corresponding to France or Italy. Drawing a rectangle inside Italy includes records from coordinates inside France, Cfroatia, Spain, Montenegro...

-----

User provided contact info: artarip@unav.es
System: Chrome 63.0.3239 / Windows 10 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/4bf6dfca20ba4176497047d3c5cea822:1504d1a3c829bfeb5c6ee5048e7fca5fa16dbbfbf01a0d9f5133063592e09daba9823f5866171c68c66eab6a22438ed95cbfad83fb5a1f542e434e95fccbf557)
Referer: https://www.gbif.org/occurrence/search?has_coordinate=true&taxon_key=1708251&advanced=1&geometry=POLYGON%20((-349.29931640625%2042.50450285299051,%20-349.29931640625%2044.449467536006935,%20-347.84912109375%2044.449467536006935,%20-347.84912109375%2042.50450285299051,%20-349.29931640625%2042.50450285299051))
Window size: width 1920 - height 949
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-20T23:20:42.176Z',mode:absolute,to:'2018-02-20T23:26:42.176Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-20T23:20:42.176Z',mode:absolute,to:'2018-02-20T23:26:42.176Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment] 2018-02-21 05:42
duplicate of https://github.com/gbif/portal-feedback/issues/1177

**Comment by MattBlissett** [comment] 2018-02-22 08:54
Fixed by https://github.com/gbif/occurrence/commit/50f2da36c40c567dbad8d3164eeb05eef98995e8

**Closed by MattBlissett** 2018-02-22 08:54 UTC
Labels: api, bug
