### ISSUE TITLE
Breeding waterbirds data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5482] opened 2024-09-19 11:27 UTC
**Breeding waterbirds data**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c6ede7c024be40391385fcbb0103a28d:cbcb38696e22e10984792472046110f70b79ec27c6ea1f58c5c60935694642c13d46a98a6e1956835d4d529817cf4f2b8b22c463da870f10692d177a4ca532552a8f2d8f3a062b7bed022024bbe579daad68cadfccff4b85e59eae8be86fd474fff2492a1d185a964c5e096af84f8ccf) - [Send email](https://www.gbif.org/api/feedback/user/mailto/c6ede7c024be40391385fcbb0103a28d:cbcb38696e22e10984792472046110f70b79ec27c6ea1f58c5c60935694642c13d46a98a6e1956835d4d529817cf4f2b8b22c463da870f10692d177a4ca532552a8f2d8f3a062b7bed022024bbe579daad68cadfccff4b85e59eae8be86fd474fff2492a1d185a964c5e096af84f8ccf)
System: Chrome 128.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1280 - height 593
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-09-19T11:22:27.164Z',to:'2024-09-19T11:28:27.164Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-09-19T11:22:27.164Z',to:'2024-09-19T11:28:27.164Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by Arturron** [comment] 2024-09-19 11:27
maybe this will help
https://bit.ly/4gwC82r
I put the necessary dlls in the archive

**Comment by ManonGros** [comment] 2024-09-24 12:38
duplicate of https://github.com/gbif/portal-feedback/issues/5483

**Closed as completed by ManonGros** 2024-09-24 12:38 UTC
Labels: question, Under review
