### ISSUE TITLE
GBIF Backbone Taxonomy "Last Modified"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#542] opened 2017-10-07 21:49 UTC
**GBIF Backbone Taxonomy &quot;Last Modified&quot;**

The 'checklist dataset' page for the GBIF Backbone Taxonomy 
 at https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c says it was 'Last modified 26 August 2016' yet the GBIF Blog post from Feb 2017 at http://gbif.blogspot.com/2017/02/gbif-backbone-february-2017-update.html says there is a new backbone.  

I'm not sure if this is a page error or if perhaps the new backbone has not actually gone live, or what else might be the case.  Still unclear as to what to cite about the currently used backbone on GBIF.

-----
fbitem-datasetd7dddbf4-2cf0-4f39-9b2a-bb099caae36c
User provided contact info: mandrewj
System: Chrome 61.0.3163 / Mac OS X 10.12.6
Referer: https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c
Window size: width 1399 - height 819
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-07T21:44:27.211Z',mode:absolute,to:'2017-10-07T21:50:27.211Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-07T21:44:27.211Z',mode:absolute,to:'2017-10-07T21:50:27.211Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment] 2017-10-09 07:40
duplicate of #480. The correct date should be the one from the blog post, this is the version that is live currently. Unfortunately it is not possible to modify the date in the registry console and it has to be set via EML. Also the last modified timestamp in GBIF datasets refer to the metadata only which is unfortunate and misleading in many cases. It might be worth reviewing how modified dates are used for datasets.

**Closed** 2017-10-09 07:40 UTC
Labels: content, Under review, US
