### ISSUE TITLE
Wrong superior taxonomy

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1318] opened 2018-04-24 16:32 UTC
**Wrong superior taxonomy**

This species is a Bird but the superior taxonomy indicates is a Reptile O.o. Which is very problematic when using the species matching or API tools.

-----

User provided contact info: @camiplata
System: Chrome 65.0.3325 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/4f1fab0f235181b031838586830292e2:a72d5fef059ccc0ec216a9773ff80b3c1bc93284a1a78d94c71d647b87b2c52acd4d7a736af6ed1127333d3dfb7aab5391bda4edf9fa36c326c1f579716ddfb0)
Referer: https://www.gbif.org/species/2480320
Window size: width 1440 - height 834
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-24T16:27:53.380Z',mode:absolute,to:'2018-04-24T16:33:53.380Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-24T16:27:53.380Z',mode:absolute,to:'2018-04-24T16:33:53.380Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by thomasstjerne** [comment] 2018-04-25 06:32
Closing as duplicate of #1213

**Closed by thomasstjerne** 2018-04-25 06:32 UTC
Labels: Under review, data content
