### ISSUE TITLE
Can't download selected occurrence records.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#331] opened 2017-08-17 10:44 UTC
**Can&#39;t download selected occurrence records.**

I could select occurrence records of my interest and could see the list of records in webpage but can&#39;t download them as csv.

-----
fbitem-8b16037cf12b5f958bf6d374db1c1429764c1b51

System: Chrome 60.0.3112 / Windows 7 0.0.0
Referer: https://www.gbif.org/occurrence/download?taxon_key=6&geometry=POLYGON((78.007%2024.543,78.007%2032.251,90.232%2032.251,90.232%2024.543,78.007%2024.543))
Window size: width 1366 - height 638
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-17T10:39:42.945Z',mode:absolute,to:'2017-08-17T10:45:42.945Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-17T10:39:42.945Z',mode:absolute,to:'2017-08-17T10:45:42.945Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment] 2017-08-17 11:27
duplicate of https://github.com/gbif/occurrence/issues/8

**Closed** 2017-09-27 08:39 UTC
Labels: api, bug
