### ISSUE TITLE
I'm in doubt, I used GBIF for naming correction with the match tool, how do I mention this use?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3453] opened 2021-06-08 14:16 UTC
**I&#39;m in doubt, I used GBIF for naming correction with the match tool, how do I mention this use?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/cd6e3e5f7e5f63f5dae66b92150d7ad2:0fb54ea2faed5d4ba6c4f9d34012e016d2888b37584ceb514a5a83c6d679875a51de263fa147d238c30ccf7a4ee463f6a241b7fde58a76a059bb890a7fe89367)
System: Chrome 91.0.4472 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1366 - height 657
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-08T14:11:48.698Z',to:'2021-06-08T14:17:48.698Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-08T14:11:48.698Z',to:'2021-06-08T14:17:48.698Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment] 2021-06-10 11:03
closed as duplicate of https://github.com/gbif/portal-feedback/issues/3452

**Closed as completed by MortenHofft** 2021-06-10 11:03 UTC
Labels: question, Under review, data content
