### ISSUE TITLE
how to download data?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#47] opened 2017-01-23 05:04 UTC
**how to download data?**

I hope to use GBIFs occurrences data but I cannot download the data. So I hope you can help me. Thank you!

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
Reported by: imwx-q@163.com
System: Edge 14.14393.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/occurrence/search?taxon_key=5960744
Window size: width 1384 - height 616
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-23T04:59:27.560Z',mode:absolute,to:'2017-01-23T05:05:27.560Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-23T04:59:27.560Z',mode:absolute,to:'2017-01-23T05:05:27.560Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment] 2017-01-23 06:55
Hi - thank you for reporting this.

The site you reported this on is still under development and the download functionality isn't there yet. It will be soon though. For now you can use our existing production site at http://www.gbif.org/occurrence/search?taxon_key=5960744 (note the missing demo. in the beginning).
Hope that helps you. Thank you for your interest.

duplicate of https://github.com/gbif/portal16/issues/63

**Closed by MortenHofft** 2017-01-23 06:55 UTC
Labels: portal
