### ISSUE TITLE
Country or area and Country code fields no longer automatically filled in for most of our records

### ISSUE THREAD

**Issue by mnhn-paul** [gbif/portal-feedback#3099] opened 2020-11-17 07:31 UTC
I recently discovered that on the country "home page" of Luxembourg it only shows 120k occurrences for Luxembourg:
https://www.gbif.org/country/LU/summary 

![image](https://user-images.githubusercontent.com/26623703/99358506-e9173e80-28ad-11eb-9b38-d51749b95d5a.png)

there are however definitely more records, in the order of 2.6mio, for the country, the records are shown when using "administrative area" search: https://www.gbif.org/occurrence/search?gadm_gid=LUX

There seems to be an issue with our main dataset: https://www.gbif.org/dataset/962f59bc-f762-11e1-a439-00145eb45e9a
we currently do not fill in the "country" field, however most records have coordinates. Previously (as far as I understand) these coordinates were used to fill in the country field while ingesting the dataset ("Country derived from coordinates"). Apparently this is no longer happening for most of our records.
I found some recodes where it is apparently still dome (https://www.gbif.org/occurrence/2641968541), but most not, even if coordinates are clearly in Luxembourg (https://www.gbif.org/occurrence/2641969932).

Hope someone can help us, or point us in the right direction, if there are maybe issues we need to fix in our dataset.

Thanks
Paul

**Comment by timrobertson100** [comment] 2020-11-30 16:14
The cause of this has been found. Rooted in https://github.com/gbif/geocode/issues/17

**Comment by timrobertson100** [comment] 2020-12-01 08:22
Fixed with [this commit](https://github.com/gbif/pipelines/commit/29d9d7aac1be89d058553700815c9a3f9d3af2f7) and will be reprocessed this week

**Closed by timrobertson100** 2020-12-01 08:22 UTC
