### ISSUE TITLE
Incorrect clustering of records

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3973] opened 2022-03-10 12:50 UTC
**Cluster, an experimental feature**

We encountered an interesting new clustering feature in one of the Dutch databases. Two occurrences are clustered, but probably because one occurrence from Germany lacks data on date & location. See https://www.gbif.org/occurrence/3128544409/cluster
Why are these specimens clustered, and where can I found more information about this feature?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c5c8200bd75610e28f426e3539e977b9:504424c32bef8eccc661c8d835228b387206f3a0554407ea88bcb237080d34a071c4b1623e823c4bcb3328607f8a5f857c8191351a9d35b965aafa7e1620442b)
System: Chrome 99.0.4844 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/3128544409/cluster
Window size: width 1536 - height 722
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-10T12:45:16.992Z',to:'2022-03-10T12:51:16.992Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-10T12:45:16.992Z',to:'2022-03-10T12:51:16.992Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment] 2022-03-10 12:57
The process is described here

https://www.gbif.org/news/4U1dz8LygQvqIywiRIRpAU/new-data-clustering-feature-aims-to-improve-data-quality-and-reveal-cross-dataset-connections

https://data-blog.gbif.org/post/clustering-occurrences/

join the discussion here https://discourse.gbif.org/t/identifying-potentially-related-records-how-does-the-gbif-data-clustring-feature-work-gbif-data-blog/3083

> sent per email

**Comment by ManonGros** [comment] 2022-03-10 13:21
In this case, it is because the catalogue number of [the SMF record](https://www.gbif.org/occurrence/207994187) (746) overlaps with the "other catalogue numbers" of the [NMR record](https://www.gbif.org/occurrence/3128544409) and the lack of country, date and coordinates in the SMF record makes it non-conflicting.

@timrobertson100 is there a way to specify that two records shouldn't be clustered?
Should the algorithm take into account the collection and institution codes/identifiers when provided? Or would it be an issue to detect herbarium duplicates across institutions?

**Comment by timrobertson100** [comment] 2022-03-10 14:02
Thanks @ManonGros 

It's tricky with sparsely populated records like this. 

There's no current way to identify a specific record pair to ignore, but we could tighten the rules a bit - e.g. making it such that you need a match for either a date or location and not `non_conflicting` in both. That would mean to remove [this rule](https://github.com/gbif/pipelines/blob/dev/sdks/core/src/main/java/org/gbif/pipelines/core/parsers/clustering/OccurrenceRelationships.java#L57).

What do you think?

**Comment by ManonGros** [comment] 2022-03-10 14:12
thanks @timrobertson100, yes it might be a good idea to removed the non-conflicting date and location rule. Now that I see this example, I think this rule doesn't enough give evidence to infer the cluster.
Let me know if/when you remove it (I will update the blogpost accordingly).

**Comment by timrobertson100** [comment] 2022-03-11 09:02
This has now been run in production and the records no longer cluster. This shows on the detail pages for the occurrences now, but it will take a little time before they disappear from the "is in cluster" search option. I've initiated a recrawl/reprocess for the two datasets involved, and that needs to complete for the search option to disappear.

Thanks for offering to update the blogpost @ManonGros -  can you please do that and then close this issue?
I'm not sure if we'd want to state within the text that it's changed today, but if so, we could refer to [this release note](https://www.gbif.org/release-notes#11mar22)?

**Comment by ManonGros** [comment] 2022-03-11 09:10
Thanks Tim! I updated the blogpost (I originally put the link to this issue but I just changed it to point to the release note)

**Comment by abubelinha** [comment] 2022-09-01 19:10
Hi. I wonder if you prefer us to re-use this issue title for other incorrect clustering of records we found, or you prefer separated posts for this. I am posting them here for now (please mention me if you open a new issue, so I can track it).

- Plant occurrence [180425491](https://www.gbif.org/occurrence/180425491/cluster) is matched to an animal ([api link](https://api.gbif.org/v1/occurrence/180425491/experimental/related)).
For some reason, cluster info says "same accepted species".

- Occurrence [2821298442](https://www.gbif.org/occurrence/2821298442), contains `"isInCluster":true` (in the [api link](https://api.gbif.org/v1/occurrence/2821298442))
But for some reason, I see nothing in the related occurrences [web](https://www.gbif.org/occurrence/2821298442/cluster) and [api](https://api.gbif.org/v1/occurrence/2821298442/experimental/related) pages.

If those are expected behaviours I would like to understand the reasons.

Thanks a lot
@abubelinha

**Comment by ManonGros** [comment] 2022-09-02 08:06
@timrobertson100 could you take a look?
I cannot explain why the occurrence [180425491](https://www.gbif.org/occurrence/180425491/cluster) is in this cluster.

For the other issue mentioned above, perhaps it is time to run an update?

**Comment by timrobertson100** [comment] 2022-09-02 10:21
Mmmm, this is an unusual bug

The API call for that page is this:
https://api.gbif.org/v1/occurrence/180425491/experimental/related 

On there you can see the current record has a `"gbifId": 1804254910`. For some reason this is showing the cluster of 1804254910 and not 180425491 (extra 0 at the end).

**Comment by timrobertson100** [comment] 2022-09-02 12:29
This is all fixed in code now.

> Plant occurrence [180425491](https://www.gbif.org/occurrence/180425491/cluster) is matched to an animal ([api link](https://api.gbif.org/v1/occurrence/180425491/experimental/related)).

[That record](https://www.gbif.org/occurrence/180425491) no longer shows a cluster (it showed the cluster for `1804254910` not `180425491`)

> Occurrence [2821298442](https://www.gbif.org/occurrence/2821298442), contains `"isInCluster":true` (in the [api link](https://api.gbif.org/v1/occurrence/2821298442))

This is fixed in code, and being released and deployed in production data pipelines now. After which we'll reprocess the dataset to clear the mistake in the search index. It was the same bug as the one above but applied to how we build the search index.

@abubelinha - thank you for raising this. Due to the way we hash records it would only appear occasionally, so went unnoticed before.

I'll close this knowing it's addressed in code and that the data will shortly be updated.

**Closed as completed by timrobertson100** 2022-09-02 12:29 UTC
Labels: bug, Under review

**Comment by abubelinha** [comment] 2022-09-02 20:04
Thank you @ManonGros and @timrobertson100 !

> > Occurrence [2821298442](https://www.gbif.org/occurrence/2821298442), contains "isInCluster":true (in the [api link](https://api.gbif.org/v1/occurrence/2821298442))
> 
> This is fixed in code, and being released and deployed in production data pipelines now. After which we'll reprocess the dataset to clear the mistake in the search index. _**It was the same bug as the one above**_ but applied to how we build the search index.
> 

I understand the [_bug above_](https://github.com/gbif/portal-feedback/issues/3973#issuecomment-1064052565) was the "other catalogue numbers" overlap + "lack of data in certain other fields". Correct?
And as you have fixed the clustering algorithm, that's the reason for occurrence [2821298442](https://www.gbif.org/occurrence/2821298442) not longer being in that cluster. Correct?

So I couldn't actually see the original cluster ... but I searched for the taxon+location+date combination and I am pretty sure this was it: [Occurrence 29606717 cluster](https://www.gbif.org/occurrence/29606717/cluster) (which still contains 8 occurrences).

I can confirm _it is a good cluster_ (I know these all are copies of the same herbarium specimen, shared in exchange to several institutions).  
But **_the cluster was better before_**: I mean it was also correct having occurrence [2821298442](https://www.gbif.org/occurrence/2821298442) into that cluster, as it was before the fix.
So, I would like to dive a little bit more into this:

1. What makes [2821298442](https://www.gbif.org/occurrence/2821298442) now different to the other occurrences, for not being kept in that cluster anymore? I mean, what dwc info is missing which data provider should add to make it matching again.
I don't think that `dwc:otherCatalogNumbers` had played any role here, because that field was not provided in [2821298442](https://www.gbif.org/occurrence/2821298442) at any time.

2. After your fix ... are `dwc:otherCatalogNumbers` still somehow useful to match records from different datasets?
It would be great if you provide guidelines on how to do that, so it takes priority over other dwc fields.

I am particularly interested in this situation:
Figure out a clustered occurrence is revised, and its `dwc:scientificName` no longer matches with the other occurrences in that original cluster.
Is there any way data curators may use [`dwc:otherCatalogNumbers`](https://dwc.tdwg.org/list/#dwc_otherCatalogNumbers) to keep the occurrence in that cluster? (i.e., pointing it to one or more of the other occurrences in the cluster). 
This would help a lot to propagate taxonomic revisions between datasets (as long as their curators take care of tracking gbif clusters).

Thanks a lot for this useful feature anyway!

**Comment by timrobertson100** [comment] 2022-09-05 13:29
This thread is getting a little difficult to read, but I will do my best to answer.

The bug spotted didn't need a change in the clustering algorithm (how we detect related records) or e.g. the use of  `otherCatalogNumbers` as I think you note. It was simply how we used the output of the clustering where we were misreading the IDs and 1) incorrectly showing a different cluster on the record in a few cases, and 2) incorrectly setting the "isInCluster" flag (same bug) in the search index. That is now fixed, but we haven't changed any of the actual clusters.

The [SANT:SANT:44553-A record](https://www.gbif.org/occurrence/2821298442) was never in this cluster which I can confirm by looking at the backend database that holds the links. So, let's understand why that is...

The [blog post](https://data-blog.gbif.org/post/clustering-occurrences/) has this table that summarises the conditions that can trigger a detection:
![image](https://user-images.githubusercontent.com/237221/188457896-90bdf82a-799e-4256-b6f1-540f14c1e0a4.png)

Looking at [the Sant record](https://www.gbif.org/occurrence/2821298442) and [the cluster](https://www.gbif.org/occurrence/29606717/cluster) we can see they have the same accepted species, date, but coordinates that are [875m apart](https://www.omnicalculator.com/other/latitude-longitude-distance?c=DKK&v=coordAngle:0,dmsLat1M:0,dmsLat1S:0,pHLongA:0,dmsLong1M:0,dmsLong1S:0,dmsLat2M:0,dmsLat2S:0,pHLongB:0,dmsLong2M:0,dmsLong2S:0,distPh:0,dLat1:42.166736!deg,dLong1:2.485503!deg,dLat2:42.16!deg,dLong2:2.48!deg) and differently formatted collector names which could be improved as [logged here](https://github.com/gbif/pipelines/issues/777).

In this case, if the collector name were made identical `M. Campos` instead of `M.Campos` you can see that the second last column would be satisfied (within 2km, same recorder, same species and the dates being equal). 

Please remember we currently run clustering frequently, but not automatically, so any publication would require us to rerun clustering before it appeared.

> I am particularly interested in this situation:
> Figure out a clustered occurrence is revised, and its dwc:scientificName no longer matches with the other occurrences in that original cluster.
> Is there any way data curators may use [dwc:otherCatalogNumbers](https://dwc.tdwg.org/list/#dwc_otherCatalogNumbers) to keep the occurrence in that cluster? (i.e., pointing it to one or more of the other occurrences in the cluster).
> This would help a lot to propagate taxonomic revisions between datasets (as long as their curators take care of tracking gbif clusters).
> 

I think we would need to define new rules for that. Currently, unless they are related to type specimens they all rely on the same accepted species, so reidentifications are not captured. I think we'd need quite a tight ruleset including identifiers overlap, collector overlap and similar date/location, and perhaps some higher order taxon to avoid too many false positives.

Does this help with understanding what you have observed please, @abubelinha? Thanks again for the feedback

**Comment by abubelinha** [comment] 2022-09-07 09:11
Thanks @timrobertson100 for your clear explanation.

As that observation had been in a cluster, and removed from it ... I was blindly assumming it had to be _that_ cluster because it was the good one.  My bad.

As for the coordinates difference, I am afraid all occurrences in the cluster have been rounded to 0.01 Lat/Lon degrees precision. The cluster-excluded observation hasn't been rounded, which explains the discrepance.

I agree that normalizing some characters and removing spaces could improve clusters a lot. 

Regarding my suggestion of using `dwc:otherCatalogNumbers` based clusters, I am not quite so sure you understood me: I was suggesting a rule based on that field _alone_, like the first two assertions on top of the table.

But as you say this thread is getting difficult to read, I opened [a new issue](https://github.com/gbif/pipelines/issues/781) about this.

**Comment by timrobertson100** [comment] 2022-09-07 09:32
> As for the coordinates difference, I am afraid all occurrences in the cluster have been rounded to 0.01 Lat/Lon degrees precision. The cluster-excluded observation hasn't been rounded, which explains the discrepance.

Thanks - I had suspected something like that had happened and your record actually had the more accurate georeference. I chose the limits of 200m and 2km to accommodate 3 and 4 decimal place rounding globally, but here we are at 2 decimal places.

I think we've arrived at a good point in understanding how things work and fixed the bug identified (i.e. that it wasn't working as expected). Let's continue the discussion on improving the normalisation of collector names and improvements relating to otherCatalogNumbers on those threads.

Thanks for your interest in this!

**Comment by abubelinha** [comment] 2022-09-25 10:09
I found this pair of occurrences which I can't figure out why not in a cluster.

I think they should be for a number of reasons (same taxon, typification relationship, same coordinates, location, collector and date). 
But I can't see the "cluster" link at the top:

https://www.gbif.org/occurrence/1936346601
https://www.gbif.org/occurrence/1936158404

**Comment by timrobertson100** [comment] 2022-09-25 11:06
> I found this pair of occurrences which I can't figure out why not in a cluster.

They are in the same dataset. We only look for links between records across datasets to help e.g. transfer knowledge between institutions.

It's also the case that there are many datasets that would just cluster everything (e.g. gut analysis) that brought a technical consideration with cardinalities, and our feasibility of actually calculating these in a timely manner.

**Comment by abubelinha** [comment] 2022-09-25 15:13
Ah OK. You mean there are datasets which contain lots of repetitive occurrences, don't you?

I should have figured this out. Thanks
