### ISSUE TITLE
Contact information not showing on participant pages.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#683] opened 2017-11-28 16:22 UTC
**Contact information not showing on participant pages.**

Roles on participation tabs of country pages and associate pages not coming through. - link to directory broken?

-----
fbitem-b5341652f6a9ca82873ea4fe3b78b58167391fb3
User provided contact info: @timhirsch
System: Safari 11.0.1 / Mac OS X 10.13.1
Referer: https://www.gbif.org/participant/375
Window size: width 1920 - height 1032
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-28T16:17:11.395Z',mode:absolute,to:'2017-11-28T16:23:11.395Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-28T16:17:11.395Z',mode:absolute,to:'2017-11-28T16:23:11.395Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment] 2017-11-28 22:32
Fixed in https://github.com/gbif/portal16/commit/f61e8e7cc6418deca2420232c06a01a61f14ac8f
Ironic that it was the updated test library that broke it - I will deploy tomorrow

**Comment by MortenHofft** [comment] 2017-11-29 07:49
duplicate of https://github.com/gbif/portal-feedback/issues/685

**Closed by MortenHofft** 2017-11-29 07:49 UTC
Labels: bug, portal
