### ISSUE TITLE
Broken link referencing this page from the IPT

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2037] opened 2019-06-11 10:49 UTC
**Broken link referencing this page from the IPT**

A user reports that the IPT links to `https://www.gbif.org/terms/licences/data-sharing,` resulting in a 404 error. Could this link be redirected to an existing page? `https://www.gbif.org/terms` may be the most appropriate replacement.

-----

User provided contact info: @ahahn-gbif
System: Firefox 67.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/11cc555b99dc498ccbae2788b9f87c8e:cebd9ef0f4e5e098cfc0dc8eb7b6c8cb0c8c231c5177f1765df92d43eb11b47166f057fd9af9e18c8fe6d32a83315c1492092ef23948d1b3cfefee6282b94bc4)
Referer: https://www.gbif.org/terms/licences/data-sharing
Window size: width 1006 - height 591
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-11T10:44:27.284Z',mode:absolute,to:'2019-06-11T10:50:27.284Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-11T10:44:27.284Z',mode:absolute,to:'2019-06-11T10:50:27.284Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment] 2019-06-11 11:00
closing as duplicate of #2030

**Closed by ahahn-gbif** 2019-06-11 11:00 UTC
Labels: Under review, content
