### ISSUE TITLE
500 on directory of contacts

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#250] opened 2017-07-13 10:27 UTC
**500 on directory of contacts**

Something about nunjucks issues...

-----
fbitem-84217f172baf095b2730fb63e737992a5a526541
Reported by: @timrobertson100
System: Chrome 58.0.3029 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/directory/contact-us
Window size: width 1389 - height 799
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-13T10:22:59.226Z',mode:absolute,to:'2017-07-13T10:28:59.226Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-13T10:22:59.226Z',mode:absolute,to:'2017-07-13T10:28:59.226Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment] 2017-07-19 09:11
Duplicate of https://github.com/gbif/portal16/issues/335

I have removed that page from the menu long ago for that very reason. How did you end up there? I guess there is lingering links to it. Anyhow it should of course be fixed. I talked to Daniel and Kyle last month about what they wanted from those pages as the comments had been that no one was too happy with how they worked. I haven't changed anything on that page since Burke implemented them, but the APIs have changed and hence it doesn't work. 
Thanks

**Closed by MortenHofft** 2017-07-19 09:11 UTC
Labels: bug, Under review
