### ISSUE TITLE
Download with dataset = "Flora of Worcestershire" includes records from all occurrence dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1600] opened 2018-10-29 12:48 UTC
**Download with dataset = &quot;Flora of Worcestershire&quot; includes records from all occurrence dataset**

At least that is what is shown on the download page and on the activity page of the concerned datasets.

This is not the only download this this issue (see for example [this one](https://www.gbif.org/occurrence/download/0007357-181003121212138)).

I already sent an email about it but just in case I am putting it in here too.

-----

User provided contact info: @manonGros
System: Safari 12.0.0 / Mac OS X 10.13.6
User: [See in registry](https://www.gbif.org/api/feedback/user/befca77cac40e28f116af64c574140d1:1d35f5a59d5687ff920ef075b8d9b591c968779c939cf526761eaf40c558c28b63cfd18b0d36e5cbdeb54f763cbe30b7f4dce82e33dc9c54c8abc85653da6b9a)
Referer: https://www.gbif.org/occurrence/download/0007396-181003121212138
Window size: width 1405 - height 1001
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-29T12:43:44.613Z',mode:absolute,to:'2018-10-29T12:49:44.613Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-29T12:43:44.613Z',mode:absolute,to:'2018-10-29T12:49:44.613Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment] 2018-11-21 16:45
I think this will have been fixed by https://github.com/gbif/occurrence/issues/28

```sql
select od.key, filter, created, count(*) from occurrence_download od, dataset_occurrence_download dod 
where filter like '{"type":"equals","key":"DATASET_KEY","value":"________-____-____-____-____________"}'
and dod.download_key = od.key and created > '2018-10-25' group by od.key, filter;
```

Looks good to me, but there are a few cases for older downloads.

**Closed by MattBlissett** 2018-11-21 16:45 UTC
Labels: api, bug

**Comment by ManonGros** [comment] 2018-11-22 09:00
It looks like the download pages still display the 21,581 datasets which supposedly contributed to this download.
Does it mean that the issue is still there or is it just a matter of updating the pages?
