### ISSUE TITLE
https://www.gbif.org/es/occurrence/3949830212

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4897] opened 2023-08-08 14:10 UTC
**`https://www.gbif.org/es/occurrence/3949830212`**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/17cd35930660eae3945dee704512eb05:51ee7c409f836bec17fdb0a68c00a31e0e6e2ea2e0feb6c06bfb4c9cfc326302489b7be7b13d6e47158f97203d4c3cf94461d98c8f4fe7f4c7851eaeb4ba1f0b56c464623aefa091db23f18fb9e30ae27d716468bdf1eb82a4165dd3d85b5054) - [Send email](https://www.gbif.org/api/feedback/user/mailto/17cd35930660eae3945dee704512eb05:51ee7c409f836bec17fdb0a68c00a31e0e6e2ea2e0feb6c06bfb4c9cfc326302489b7be7b13d6e47158f97203d4c3cf94461d98c8f4fe7f4c7851eaeb4ba1f0b56c464623aefa091db23f18fb9e30ae27d716468bdf1eb82a4165dd3d85b5054)
System: Firefox 116.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/es/occurrence/3949830212
Window size: width 1760 - height 783
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-08T14:05:45.103Z',to:'2023-08-08T14:11:45.103Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-08T14:05:45.103Z',to:'2023-08-08T14:11:45.103Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 7a3679ef-5582-4aaa-81f0-8c2545cafc81
publishingOrgKey: da86174a-a605-43a4-a5e8-53d484152cd3

**Comment by ktotsum** [comment] 2023-08-14 12:13
close this issue as duplicate of #4898

**Closed as completed by ktotsum** 2023-08-14 12:13 UTC
Labels: data content, FR
