### ISSUE TITLE
Enable links to search tabs

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#164] opened 2017-04-06 12:50 UTC
**Enable links to search tabs**

It would be nice to change the URL so one can copy-paste a search URL with another than the default table view

-----
fbitem-f55b22d402f0bf9841531850ab0f3ed8d9273208

System: Chrome 56.0.2924 / Mac OS X 10.12.3
Referer: https://demo.gbif.org/occurrence/species?taxon_key=79
Window size: width 1616 - height 797
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-06T12:45:03.719Z',mode:absolute,to:'2017-04-06T12:51:03.719Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-06T12:45:03.719Z',mode:absolute,to:'2017-04-06T12:51:03.719Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment] 2017-05-02 08:58
Thank you for your feedback.
That should be possible already. if not this is a bug. I cannot reproduce.
Closing as user is unknown

**Closed by MortenHofft** 2017-05-02 08:58 UTC
Labels: idea, Under review
