### ISSUE TITLE
Duplicated ukraine datasets

### ISSUE THREAD

**Issue by rukayaj** [gbif/portal-feedback#4492] opened 2022-12-22 09:11 UTC
This dataset https://www.gbif.org/dataset/0c5b3d27-e175-4441-9a14-76d7cdd10446 was somehow removed from the Ukraine IPT. Possibly accidentally deleted, I am not sure what happened. 

The data provider recreated this dataset on the IPT from a backup, published it, and unfortunately now we have a duplicate dataset: https://www.gbif.org/dataset/4a56feac-b26d-4490-b7c6-dd0d7a10382a . I added the old DOI (https://doi.org/10.15468/2qgsta) + old dataset key (0c5b3d27-e175-4441-9a14-76d7cdd10446 ) to the alternative identifiers in the EML in the new recreated dataset. I see on the registry it's possible to specify if one dataset is a duplicate of another, so I did that too. Is there any way they can get merged?

**Comment by CecSve** [comment] 2022-12-22 09:52
It seems the duplicate registration in the registry did not go through. Should I go ahead and try to mark the first one as a duplicate of the new? The datasets would not get merged, but the one that was accidentally deleted on the Ukranian IPT would be registered as 'deleted' + 'duplicate of' the other dataset, the occurrence would be removed and any citations (no citations in this case) would **not** be automatically transferred to the new dataset.

**Comment by rukayaj** [comment] 2022-12-22 10:55
Hi @CecSve yes that sounds good. Thanks :)

**Comment by CecSve** [comment] 2022-12-22 12:15
I duplicated the dataset again and deleted the old dataset, and the dataset now appears as [deleted + duplicated](https://www.gbif.org/dataset/0c5b3d27-e175-4441-9a14-76d7cdd10446) of the GBIF Norway IPT one

**Closed as completed by CecSve** 2022-12-22 12:15 UTC
Labels: question
