### ISSUE TITLE
Combining author and year looks suspicious

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/portal-feedback#730] opened 2017-12-18 07:52 UTC
For some animal names, the Authorship is duplicated after the brackets as combining Author:
Alloxysta citripes (Thomson, 1862) Thomson, 1862 

http://api.gbif.org/v1/species/4497451

Seems to co-occur with the ORIGINAL_NAME_DERIVED issue

**Comment by mdoering** [comment] 2017-12-18 09:08
duplicate of gbif/checklistbank#43 which is fixed now in code (waiting for new backbone to go live)

**Closed by mdoering** 2017-12-18 09:08 UTC
