### ISSUE TITLE
identificação errada

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2941] opened 2020-08-08 09:50 UTC
**identificação errada**

A espécie correnta na foto é Begonia aconitifolia, e não B. maculata.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c97a56225438c5ea4b199feb07642a81:c35108e3d2ebb527ac352ca9e9fd32ccc26cfb82c804d5fc9a41d92d4898f7596534c597560d8c61805cd28ddc731c2ad01ff80d9669b9146162e8d90e8e5731bbc5d81ae7e930b299885f8ba8184f2f)
System: Chrome 84.0.4147 / Windows 10.0.0
Referer: https://www.gbif.org/pt/occurrence/2644227343
Window size: width 1284 - height 797
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-08-08T09:45:14.057Z',mode:absolute,to:'2020-08-08T09:51:14.057Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-08-08T09:45:14.057Z',mode:absolute,to:'2020-08-08T09:51:14.057Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 7a3679ef-5582-4aaa-81f0-8c2545cafc81
publishingOrgKey: da86174a-a605-43a4-a5e8-53d484152cd3

**Comment by ManonGros** [comment] 2020-09-14 09:49
Duplicate of https://github.com/gbif/portal-feedback/issues/2936

**Closed by ManonGros** 2020-09-14 09:49 UTC
Labels: Under review, data content
