### ISSUE TITLE
Species Lookup Tool

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2123] opened 2019-07-25 09:50 UTC
**Species Lookup Tool**

I don't know whether this is a cataloguing issue or a problem with the Species Lookup Tool itself, but I've noticed some records return a "Higher Rank" match in preference to a "Synonym" match. For example, my data includes "Pithecopus azureus". When this data is passed through the Species Lookup Tool, the normalized result returns the genus Pithecopus as an accepted higher rank. However, I expect this record actually refers to "Phyllomedusa azurea" which is an accepted species (and previously classified as Pithecopus azureus).

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/aa637a78c03275f9529fd98e57635828:a0c52a39a3f77cb374fe5a356a02effbd93f82105232671a9862fe465c9b45a8a4ddc1174ef042346b5450c24c7bf62b418a2f99bb9cbaa00d7a2f3bf73bd9cf)
System: Chrome 75.0.3770 / Windows 10.0.0
Referer: https://www.gbif.org/tools/species-lookup
Window size: width 1920 - height 969
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-25T09:45:58.447Z',mode:absolute,to:'2019-07-25T09:51:58.447Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-25T09:45:58.447Z',mode:absolute,to:'2019-07-25T09:51:58.447Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment] 2019-07-25 10:51
The tool is simply intended as an easy way to get started with the APIs. It is really just doing a bunch of calls to our public APIs. In this case the match api documented here https://www.gbif.org/developer/species

http://api.gbif.org/v1/species/match?name=Pithecopus%20azureus&verbose=true

The API is, as you say, returning the  genus Pithecopus. If this is incorrect, then the issue is likely to be our backbone.

**Comment by yroskov** [comment] 2019-11-01 20:25
Irrelevant to CoL.

**Comment by ManonGros** [comment] 2019-11-04 10:56
Does this mean that Pithecopus azureus should be added as a synonym of Phyllomedusa azurea?

**Comment by jhnwllr** [comment] 2021-11-10 12:27
I am closing this issue because it does not really seem actionable. Matching higher rank happens when we don't have the taxa in the backbone.

**Closed by jhnwllr** 2021-11-10 12:27 UTC
Labels: backbone
