### ISSUE TITLE
No years for this dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4235] opened 2022-09-02 10:11 UTC
**No years for this dataset**

The occurrences in this dataset have no years because the date cannot be interpreted. I'm not sure if it is a content issue or an interpretation issue.

example date `01-04-2012/15-06-2016`

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/79cc428ac848a53a65a389bf2bf34fc4:0a41290d2ca67b4d74d0ee8b2e7bb3ffac928e19bc3e3f25e4e581ca39ae87c5ee4f8994ebc143675cd2331903c60999ec826a2c4a751b169629a66dfed14c020873c9bcff2df43500ee00290f77be1c1f14e78490af8e4026f9845be8a371ee4999eed651162b9b6d5c047a3ed524dc8ed33bd8a48d3ea5b5991c16908325da) - [Send email](https://www.gbif.org/api/feedback/user/mailto/79cc428ac848a53a65a389bf2bf34fc4:0a41290d2ca67b4d74d0ee8b2e7bb3ffac928e19bc3e3f25e4e581ca39ae87c5ee4f8994ebc143675cd2331903c60999ec826a2c4a751b169629a66dfed14c020873c9bcff2df43500ee00290f77be1c1f14e78490af8e4026f9845be8a371ee4999eed651162b9b6d5c047a3ed524dc8ed33bd8a48d3ea5b5991c16908325da)
System: Chrome 104.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/2490388606
Window size: width 2624 - height 1555
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-02T10:06:08.700Z',to:'2022-09-02T10:12:08.700Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-02T10:06:08.700Z',to:'2022-09-02T10:12:08.700Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 00199071-3d3d-41c4-9a77-36fe8d84fa2f
publishingOrgKey: 1928bdf0-f5d2-11dc-8c12-b8a03c50a862

**Comment by muttcg** [comment] 2022-09-02 11:14
Fixed. I set default date machine tag as DMY in the registry
This is because there is no other fields such as year, month and day, so parser split date into 01-04-2012 and 15-06-2016, and after can choose use DMY or MDY to parse first date and fails. It could return at least year.

**Comment by CecSve** [comment] 2022-09-09 11:07
It looks like the issue is fixed, so I will close it.

**Closed as completed by CecSve** 2022-09-09 11:07 UTC
Labels: data content, FR
