### ISSUE TITLE
Incorrectly labeled as country coordinate mismatch

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#202] opened 2017-06-06 21:23 UTC
**Incorrectly labeled as country coordinate mismatch**

This is flagged as a mismatch, but that seems incorrect looking at the map.  The point is on (coastal) Iceland and the country is stated as Iceland.

-----
fbitem-occurrence142728753
Reported by: @timrobertson100
System: Chrome 58.0.3029 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/occurrence/142728753
Window size: width 1344 - height 755
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-06T21:18:40.219Z',mode:absolute,to:'2017-06-06T21:24:40.219Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-06T21:18:40.219Z',mode:absolute,to:'2017-06-06T21:24:40.219Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: 83422c44-f762-11e1-a439-00145eb45e9a
publishingOrgKey: 12308e00-4b80-11da-8809-b8a03c50a862

**Comment by MortenHofft** [comment] 2017-06-09 12:19
Thanks
There seem to be a bug in the parsing then: http://api.gbif.org/v1/occurrence/142728753

**Comment by timrobertson100** [comment] 2017-06-09 12:22
Looks like the issue is probably in the geocoder:
  http://api.gbif.org/v1/geocode/reverse?lat=64.389&lng=-21.887

**Comment by MattBlissett** [comment] 2017-06-09 12:24
This is the one I mentioned about the gaps between land and coast. There's an old JIRA about it somewhere.

It's clear if you display the polygons in the eez database.

**Comment by MattBlissett** [comment] 2017-09-21 20:09
Fixed with the improvements to the geocoder.

I've reinterpreted the bad records in the Icelandic dataset, and no longer do any have a country mismatch issue.  I also reinterpreted all records with the coordinate mismatch issue, about 1.75 million (30%!) now match.

**Closed** 2017-09-21 20:09 UTC
Labels: api, bug
