### ISSUE TITLE
Known issues filter in download dialog: allow to exclude records with specific issues

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#195] opened 2017-05-29 09:36 UTC
**Known issues filter in download dialog: allow to exclude records with specific issues**

It is very helpful to see the list of issues that concern records in a download I am about to request. Knowing these issues exist makes me want to exclude some of the records, e.g. all those where the coordinates are out of range. 

Currently, I see no option to easily achieve this: using the facets on the left, I can select those records, but I cannot exclude them. The known issues section on the main page lists the issues and counts, but does not support any action. It would be really useful being able not only to understand potential issues, but also to fine-tune my search at this point, e.g. by clicking on the colored issue label in order to exclude the concerned records from my search result set, or refine some other way.

-----
fbitem-8b16037cf12b5f958bf6d374db1c1429764c1b51
Reported by: @ahahn-gbif
System: Firefox 53.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/occurrence/download?taxon_key=2888195&advanced=1
Window size: width 1264 - height 710
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-05-29T09:31:44.359Z',mode:absolute,to:'2017-05-29T09:37:44.359Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-05-29T09:31:44.359Z',mode:absolute,to:'2017-05-29T09:37:44.359Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment] 2017-06-01 10:10
Duplicate of https://github.com/gbif/portal-feedback/issues/49

No our API don't support that unfortunately. But it seems very useful. For know, the best we can do at the website is to draw attention to the fact that they are flagged and you can filter after download.

**Closed by MortenHofft** 2017-06-01 10:10 UTC
Labels: api, idea
