### ISSUE TITLE
Data validator

### ISSUE THREAD

**Issue by jeroencreuwels** [gbif/portal-feedback#1232] opened 2018-03-06 12:52 UTC
I encountered problems when validating Excel files in the new Data validator, even if they are standard IPT templates. I checked again and used for example the file "occurrence_ipt_template_v2_example_data.xlsx", which I took from Github: https://github.com/gbif/ipt/wiki/occurrenceData#templates

Even while validating this data set it gives the message: "The system is currently not able to process your request. Try to refresh the page and please report the issue if it continues."

What could be the problem?

Jeroen

**Comment by MortenHofft** [comment] 2018-03-06 13:49
closed as duplicate of https://github.com/gbif/portal-feedback/issues/1233

**Closed by MortenHofft** 2018-03-06 13:49 UTC
