### ISSUE TITLE
Citation generation omitting an "originating author"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2853] opened 2020-06-26 06:22 UTC
**Citation generation omitting an &quot;originating author&quot;**

The MZB Indonesian bat call library dataset (https://www.gbif.org/dataset/271b9b36-b060-4f97-b438-81edb970a1a0) has three persons listed as "Originator" in their IPT metadata. Only two of these names, though, get added to the auto-generated citation. The omitted name is "Maharadatunkamsi" (surname only, no given name, email supplied, see https://cloud.gbif.org/bifa/eml.do?r=bifa04-24-20). In other places on the web page the name is displayed correctly.

Wild guess: could the fact that there is no given name cause the name to be dropped in the citation generation?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4da08bd431cd3cb5d055955c538711ba:9e525a41914bbcb25ab0f80d691abf3a3f92f6cbd056e99c77f76704233ec7f60a9bd513b5ac4ffe13dcd4d0039ac4ff8f6e6890d599b9f8946d9321bea19c00)
System: Firefox 77.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/271b9b36-b060-4f97-b438-81edb970a1a0
Window size: width 1408 - height 565
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-26T06:17:57.232Z',mode:absolute,to:'2020-06-26T06:23:57.232Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-26T06:17:57.232Z',mode:absolute,to:'2020-06-26T06:23:57.232Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MattBlissett** [comment] 2020-06-26 07:34
That's exactly the problem:

https://github.com/gbif/registry/blob/1fb13e0388d17da2190f515618e3ac46c2f98387/registry-metadata/src/main/java/org/gbif/registry/metadata/CitationGenerator.java#L226-L230

Also https://en.wikipedia.org/wiki/Mononymous_person

**Comment by MattBlissett** [comment] 2020-06-26 07:43
https://github.com/gbif/registry/blob/master/registry-metadata/src/main/java/org/gbif/registry/metadata/CitationGenerator.java#L237

We seem to have code to handle a surname alone, which is what the EML provides.

**Comment by ahahn-gbif** [comment] 2020-07-08 10:25
The GBIF annotated EML stores the snippet in question as (notice the givenName element is missing altogether):

    <creator>
      <individualName>
        <surName>Maharadatunkamsi</surName>
      </individualName>
      <organizationName>Museum Zoologicum Bogoriense, Indonesian Institute of Sciences (LIPI)
      </organizationName>
      <positionName>Senior Researcher</positionName>
      <address>
        <country>INDONESIA</country>
      </address>
      <electronicMailAddress>datun_mzb@yahoo.com</electronicMailAddress>
    </creator>

(EML from https://api.gbif.org/v1/dataset/271b9b36-b060-4f97-b438-81edb970a1a0/document)

At source (IPT eml), the given name presently carries a whitespace character, i.e. is not null: 

    <creator>
      <individualName>
        <givenName> </givenName>
        <surName>Maharadatunkamsi</surName>
      </individualName>
      <organizationName>Museum Zoologicum Bogoriense, Indonesian Institute of Sciences (LIPI)
      </organizationName>
      <positionName>Senior Researcher</positionName>
      <address>
        <country>ID</country>
      </address>
      <electronicMailAddress>datun_mzb@yahoo.com</electronicMailAddress>
    </creator>
(https://cloud.gbif.org/bifa/eml.do?r=bifa04-24-20)

The resulting citation omits the name altogether (https://www.gbif.org/dataset/271b9b36-b060-4f97-b438-81edb970a1a0).

Contacting the publisher to remove the whitespace.

**Comment by ahahn-gbif** [comment] 2020-07-08 10:37
Is this a case we may want to catch in the code though?

**Comment by MattBlissett** [comment] 2020-07-08 10:52
It looks like it's already handled in code to me (`Strings.trimToNull` should change ` ` to `null`). @mike-podolskiy90, is this something you can test easily? (I've forgotten what tests we have around this.)

**Comment by mike-podolskiy90** [comment] 2020-07-08 21:14
@MattBlissett Yes we can test that by `CitationGeneratorTest`. The problem is in `CitationGenerator#getAuthors`, contacts without first or last names are excluded from the list of 'unique' contacts
https://github.com/gbif/registry/blob/master/registry-metadata/src/main/java/org/gbif/registry/metadata/CitationGenerator.java#L141

**Comment by mike-podolskiy90** [comment] 2020-07-08 21:18
Should a contact without a last name (only a name) also be displayed?

**Comment by mike-podolskiy90** [comment] 2020-07-08 21:39
https://github.com/gbif/registry/pull/210

**Comment by ahahn-gbif** [comment] 2020-07-09 07:01
The surname/given name pattern is not universal - mononyms do occur (e.g. Java). 
I would assume that including surname-only can be used to cover most of these cases, though strictly speaking, those would indeed be given name only cases.

**Comment by ahahn-gbif** [comment] 2020-07-16 12:56
Confirmed fixed - user notified and closing

**Closed by ahahn-gbif** 2020-07-16 12:56 UTC
Labels: bug, registry
