### ISSUE TITLE
Project not sortable by country

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1272] opened 2018-03-17 20:10 UTC
**Project not sortable by country**

This list of funded projects is extremely useful and much appreciated, but a significant shortcoming is the lack of information about which country the project covers. A common use case is that for example we want to see quickly which projects we have operating in Cameroon - or indeed quickly see the list of countries in which we have funded projects. It would seem pretty straightforward to add this attribute. Admittedly there are some projects covering multiple countries, but in this case we could just include the country of the lead partner.

-----

User provided contact info: @timhirsch
System: Chrome 64.0.3282 / Mac OS X 10.13.2
User: [See in registry](https://www.gbif.org/api/feedback/user/2d10f177ca9b02bd62c538d23bb2a284:8cbbe02ba4c17257f92fbaba1a0269c77653b6db965395b2ec56b3117870c6b3ee621f87709f54ee500f740c4a98c6450c02f6f15ad24d65df8e51cb4c40a94c)
Referer: https://www.gbif.org/programme/82243/bid-biodiversity-information-for-development
Window size: width 1024 - height 687
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-17T20:05:16.584Z',mode:absolute,to:'2018-03-17T20:11:16.584Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-17T20:05:16.584Z',mode:absolute,to:'2018-03-17T20:11:16.584Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment] 2018-03-19 11:25
Duplicate of https://github.com/gbif/portal-feedback/issues/483

**Comment by dnoesgaard** [comment] 2018-03-20 11:15
Indeed duplicate, will continue tracking this in #483

**Closed by dnoesgaard** 2018-03-20 11:15 UTC
Labels: content, idea
