### ISSUE TITLE
Wrong superior taxonomy

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1323] opened 2018-04-24 16:43 UTC
**Wrong superior taxonomy**

This species is a Bird but the superior taxonomy indicates is a Reptile O.o. Which is very problematic when using the species matching or API tools.

-----

User provided contact info: @camiplata
System: Chrome 65.0.3325 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/4baff9a522abeaf2fe45780358c43791:10196ac7ccd1ac919d578ecfbfdf82979e6f36481c67a9dc8b8b44a9d22f3373983015f0d470d8be2e7941ba498cf0a2f1b81e18a4392ace6a4490af08be8036)
Referer: https://www.gbif.org/species/2482001
Window size: width 1440 - height 834
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-24T16:38:12.859Z',mode:absolute,to:'2018-04-24T16:44:12.859Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-24T16:38:12.859Z',mode:absolute,to:'2018-04-24T16:44:12.859Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by thomasstjerne** [comment] 2018-04-25 06:30
closing as duplicate of #1213

**Closed by thomasstjerne** 2018-04-25 06:30 UTC
Labels: Under review, data content
