### ISSUE TITLE
Could not validate the file by using "drop here"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4050] opened 2022-04-27 13:33 UTC
**Could not validate the file by using &quot;drop here&quot;**

I tried to drop the file to validator immediately but it said "The file could not be processed, or it may be missing if you provided a URL.".   And it works if I try the way "select file" instead.

-----

Github user: @melissa0520
User: [See in registry](https://www.gbif.org/api/feedback/user/7cff4304de37d0f1cadadec3253c5080:f9c4ba7b17b85b083b88e063816af6893f6329b273064decfda8ea07087ef433b7b8825b5e0162aa7633a95c682f8b7263e1b36e8398208a667661c33848296a06f245d4c0520fe6af7f666482eef541bd6cb39332787b17a776bfd5e59909c44d8238cd4d6ad87f6023358fd1492735335699dd9f1169ce8a42ea826388a696b10ad1e655e27373d53e1f37240efa77) - [Send email](https://www.gbif.org/api/feedback/user/mailto/7cff4304de37d0f1cadadec3253c5080:f9c4ba7b17b85b083b88e063816af6893f6329b273064decfda8ea07087ef433b7b8825b5e0162aa7633a95c682f8b7263e1b36e8398208a667661c33848296a06f245d4c0520fe6af7f666482eef541bd6cb39332787b17a776bfd5e59909c44d8238cd4d6ad87f6023358fd1492735335699dd9f1169ce8a42ea826388a696b10ad1e655e27373d53e1f37240efa77)
System: Chrome 100.0.4896 / Mac OS X 10.15.7
Referer: https://www.gbif.org/tools/data-validator
Window size: width 1536 - height 775
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-27T13:28:54.852Z',to:'2022-04-27T13:34:54.852Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-27T13:28:54.852Z',to:'2022-04-27T13:34:54.852Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by thomasstjerne** [comment] 2022-05-09 07:27
Closing, duplicate of https://github.com/gbif/portal-feedback/issues/4032

**Closed as completed by thomasstjerne** 2022-05-09 07:27 UTC
Labels: bug, data validator
