### ISSUE TITLE
error in definition In reality, it is Astragalus kustanaicus M.Pop.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4856] opened 2023-07-09 15:06 UTC
**error in definition In reality, it is Astragalus kustanaicus M.Pop.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/795707cd91e95ccd44d89ea32a5b0460:f2a43d3f8ef089a68141e5ee70d2513391da780a2579f6fa98f5b5accb31c5ac6bd5f6d4296466b8dc39075aa64871b2b1955fb8ad3eea20483413226d1793261ab8c0c79ecada7e2e5179dc23c585601733739142cf892b703b890edda9d5a2) - [Send email](https://www.gbif.org/api/feedback/user/mailto/795707cd91e95ccd44d89ea32a5b0460:f2a43d3f8ef089a68141e5ee70d2513391da780a2579f6fa98f5b5accb31c5ac6bd5f6d4296466b8dc39075aa64871b2b1955fb8ad3eea20483413226d1793261ab8c0c79ecada7e2e5179dc23c585601733739142cf892b703b890edda9d5a2)
System: Chrome 114.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/ru/occurrence/2650664975
Window size: width 1378 - height 914
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-09T15:01:44.887Z',to:'2023-07-09T15:07:44.887Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-09T15:01:44.887Z',to:'2023-07-09T15:07:44.887Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 85f9137e-8aec-4e0b-9ed6-0af4dbe491e8
publishingOrgKey: 8f6232c3-5523-44ad-825c-e066fc6b15ad

**Comment by ahahn-gbif** [comment] 2023-07-10 09:59
(closing as duplicate of #4857)

**Closed as completed by ahahn-gbif** 2023-07-10 09:59 UTC
Labels: Under review, data content, RU
