### ISSUE TITLE
I am getting an error saying that the "the validation job ID was not found" What is it? Please assist.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3551] opened 2021-08-24 05:52 UTC
**I am getting an error saying that the &quot;the validation job ID was not found&quot; What is it? Please assist.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/9b7a46a8627555e46aff7f2ba4ff7d8f:16a33a00df1842e61f4ce3f0f7499437bd4106cae3792c9d5e2855e2e52f7aa0fbbb412251aeb8a9d8d491bad43821487d19c0992a4eaf99625caaa90c70c65d)
System: Chrome 92.0.4515 / Windows 8.1.0.0
Referer: https://www.gbif.org/tools/data-validator/1622015287762
Window size: width 1785 - height 921
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-24T05:47:03.645Z',to:'2021-08-24T05:53:03.645Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-24T05:47:03.645Z',to:'2021-08-24T05:53:03.645Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by daniel** [comment] 2021-08-24 08:36
I've been getting this error too today. Now the validation has started, but it's been running for more than an hour.

**Comment by ahahn-gbif** [comment] 2021-08-24 08:42
Checking the reported referrer URL (https://www.gbif.org/tools/data-validator/1622015287762), I cannot reproduce the issue right now, the report shows as expected. Depending on the size of the dataset and general load, validation lag time is not unusual, but we will monitor this issue.

**Comment by daniel** [comment] 2021-08-24 08:49
Here's the link to my validation: https://www.gbif.org/tools/data-validator/1622015287774. It's still running.

**Comment by ahahn-gbif** [comment] 2021-08-24 09:09
On checking, validation  https://www.gbif.org/tools/data-validator/1622015287774 is still running. Please check back again later. Feedback from IT colleagues suggests that the taxonomic lookup may be particularly challenging / slow in this case.

**Comment by ahahn-gbif** [comment] 2021-08-24 09:14
original submitter notified via email through helpdesk

**Comment by daniel** [comment] 2021-08-25 08:11
I just checked the validation again, it has finished now.

**Comment by ahahn-gbif** [comment] 2021-08-25 09:43
both validations finished, though with a delay - closing

**Closed as completed by ahahn-gbif** 2021-08-25 09:43 UTC
Labels: data validator
