### ISSUE TITLE
nubKey or taxonKey?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#673] opened 2017-11-21 14:48 UTC
**nubKey or taxonKey?**

I notice there are two ways to refer to "A taxon key from the GBIF backbone", the `nubKey` and the `taxonKey`: https://www.gbif.org/developer/occurrence

* taxonKey is used as a search parameter for occurrences
* nubKey I could only find in responses of the species API

Are there plans to deprecate one for the other?

-----
fbitem-b1018fb447ec8b1aa84ee420b36825314783d5a9
User provided contact info: peterdesmet
System: Chrome 62.0.3202 / Mac OS X 10.12.6
Referer: https://www.gbif.org/developer/occurrence
Window size: width 1336 - height 736
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-21T14:43:33.669Z',mode:absolute,to:'2017-11-21T14:49:33.669Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-21T14:43:33.669Z',mode:absolute,to:'2017-11-21T14:49:33.669Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment] 2017-11-22 07:56
duplicate of https://github.com/gbif/portal-feedback/issues/672

I wonder why it created two identical. seem like a portal bug, but we haven't seen it before

**Closed by MortenHofft** 2017-11-22 07:56 UTC
Labels: bug, Under review
