### ISSUE TITLE
Wrong superior taxonomy

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1317] opened 2018-04-24 15:58 UTC
**Wrong superior taxonomy**

This species is a Bird but  the superior taxonomy indicates is a Reptile O.o. Which is very problemetic when using the species matching or API tools.

-----

User provided contact info: @camisilver
System: Chrome 65.0.3325 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/94ba3cc57ace990c130beff67b3e3398:340d09a70152617a77927b2a11c4a520e7fd5d0161a709662350311787f99d2ecf7dec8ba2a752122fc2d3aee22943a61b2192fbdd1dc32276d0fc00c54e7f8e)
Referer: https://www.gbif.org/species/2480295
Window size: width 1440 - height 834
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-24T15:53:41.407Z',mode:absolute,to:'2018-04-24T15:59:41.407Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-24T15:53:41.407Z',mode:absolute,to:'2018-04-24T15:59:41.407Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by thomasstjerne** [comment] 2018-04-25 06:29
Closing as duplicate of #1213

**Closed by thomasstjerne** 2018-04-25 06:29 UTC
Labels: Under review, data content
