### ISSUE TITLE
How to download data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#54] opened 2017-01-30 19:25 UTC
**How to download data**

How could I download a table of results as a CSV dat file? Thanks!

-----
fbitem-632937989213bf4e43cb42556216fa1047383e29
Reported by: annaw84@gmail.com
System: Safari 10.0.3 / Mac OS X 10.10.5
Referer: https://demo.gbif.org/occurrence/map?taxon_key=3190474
Window size: width 1280 - height 738
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-30T19:20:48.987Z',mode:absolute,to:'2017-01-30T19:26:48.987Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-30T19:20:48.987Z',mode:absolute,to:'2017-01-30T19:26:48.987Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment] 2017-01-31 09:13
Hi Anne
We are still en development mode, and downloads are not available on the new site yet, but will be soon. For now you can use the existing site at http://www.gbif.org/occurrence/search?taxonKey=3190474

Thank you for your interest!

> user emailed

closed as duplicate of https://github.com/gbif/portal16/issues/63

**Closed by MortenHofft** 2017-01-31 09:13 UTC
Labels: Under review
