### ISSUE TITLE
Failing images from Kew

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2183] opened 2019-08-28 08:49 UTC
**Failing images from Kew**

`https://api.gbif.org/v1/occurrence/912568109/fragment`
It looks like the publisher states that there is an image even when there is no identifier. 
Looking at their website it seems that there is in fact no image associated. So looks like a mapping error. 

We could also improve by removing the invalid items during processing and flag the occurrence as having an issue

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/aa3bb95fa134641bedffd4391745b156:d659757994657950c04cb12db7162a7cf359e322b8c31841f0fe85d6d7cefc2d290efcf2b62b09fcc284c0804cfce6cfff69edb0aba4b4fcd3c09ca1b080d63f)
System: Chrome 76.0.3809 / Mac OS X 10.14.5
Referer: https://www.gbif.org/occurrence/gallery?dataset_key=cd6e21c8-9e8a-493a-8a76-fbf7862069e5
Window size: width 2228 - height 1306
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-28T08:44:21.560Z',mode:absolute,to:'2019-08-28T08:50:21.560Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-28T08:44:21.560Z',mode:absolute,to:'2019-08-28T08:50:21.560Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment] 2019-08-28 09:00
Duplicate of #1598.

A reference without an identifier is valid, if the image is only available on the publisher's site. Such cases might not belong on the gallery view, but they probably do belong in a search for occurrences with images.

**Comment by MortenHofft** [comment] 2019-08-29 08:18
> A reference without an identifier is valid, if the image is only available on the publisher's site.

Makes sense. This isn't the case for the occurrences I have looked at.

**Closed** 2019-08-29 08:19 UTC
Labels: api, data content
