### ISSUE TITLE
not allowing me to sign up.  not allowing me to download data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#176] opened 2017-04-23 22:06 UTC
**not allowing me to sign up. not allowing me to download data**

-----
fbitem-8b16037cf12b5f958bf6d374db1c1429764c1b51

System: Chrome 57.0.2987 / Windows 7 0.0.0
Referer: https://demo.gbif.org/occurrence/download?dataset_key=8c04889e-a0ad-4f39-8623-06aa9cf0131d&has_geospatial_issue=false&year=1995,*&geometry=-117.64%2043.29,-117.64%2046.39,-110.75%2046.39,-110.75%2043.29,-117.64%2043.29
Window size: width 1536 - height 736
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-23T22:01:45.005Z',mode:absolute,to:'2017-04-23T22:07:45.005Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-23T22:01:45.005Z',mode:absolute,to:'2017-04-23T22:07:45.005Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment] 2017-04-27 16:23
Duplicate of #180.

**Closed by MattBlissett** 2017-04-27 16:23 UTC
Labels: bug, Under review
