### ISSUE TITLE
Trypoxylus davidis

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3570] opened 2021-08-30 09:09 UTC
**Trypoxylus davidis**

Trypoxylus davidis There is no data for this species

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/945fee81cac0c3cc6d7903a22209fb78:3996c444b772d5a94f8709cd4d68155336671653c3c4ea22d60a641c79ba9e4b6831e17007ceddfc5a0bb05cd86aba9c30e4286e33bad0c66f10d1585849f2a8)
System: Chrome 92.0.4515 / Mac OS X 10.15.7
Referer: https://www.gbif.org/zh/search?q=Trypoxylus%20davidis
Window size: width 1880 - height 759
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-30T09:04:27.261Z',to:'2021-08-30T09:10:27.261Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-30T09:04:27.261Z',to:'2021-08-30T09:10:27.261Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment] 2021-08-31 09:39
Duplicate of: https://github.com/gbif/backbone-feedback/issues/374

**Closed as completed by ManonGros** 2021-08-31 09:39 UTC
Labels: Under review, data content
