### ISSUE TITLE
The coordinates attributed to this specimen are not correct. The label says "Minas Gerais state" and the coordinates are from Mato Grosso State. Several other records from F have the same issue. Thank you

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3542] opened 2021-08-13 19:48 UTC
**The coordinates attributed to this specimen are not correct. The label says &quot;Minas Gerais state&quot; and the coordinates are from Mato Grosso State. Several other records from F have the same issue. Thank you**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/78b61ba9db0e1e6a741e60648eb36714:2942ac00f72fa0f420d87ca64e0b1a7555c683b3056e4e75c36bc7a0294bb7c615b8d20436d2036e7f6fe237d7c4fd10ccf2fd2fb1e44c944d932fd94c2ac34b)
System: Chrome 92.0.4515 / Mac OS X 10.14.6
Referer: https://www.gbif.org/occurrence/1500184114
Window size: width 1440 - height 766
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-13T19:43:33.568Z',to:'2021-08-13T19:49:33.568Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-13T19:43:33.568Z',to:'2021-08-13T19:49:33.568Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 9f747cff-839f-4485-83a1-f10317a92a82
publishingOrgKey: 7b8aff00-a9f8-11d8-944b-b8a03c50a862

Node handles: @albenson-usgs

**Comment by jhnwllr** [comment] 2021-08-16 07:37
record appears to be a country centroid of Brazil. This might also be the case with the other records you notice as well.

**Comment by AbbyBenson** [comment] 2021-11-01 16:37
Confirmed with The Field Museum that this is a country centroid. georeferenceProtocol states "TGN - Centroid".

**Comment by jhnwllr** [comment] 2021-12-01 14:09
Since centroids are a known issue, I am going to close this.

**Closed as completed by jhnwllr** 2021-12-01 14:09 UTC
Labels: Under review, data content, US
