### ISSUE TITLE
Number of records returned by the "occurrences" API

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1265] opened 2018-03-15 13:33 UTC
**Number of records returned by the &quot;occurrences&quot; API**

Hi,
I use your occurrences API to find the Plant species present in a area ( ex: `http://api.gbif.org/v1/occurrence/search?taxonKey=6&limit=300&geometry=POLYGON((2.98770334797575` 43.00899320194335, 3.0122966520242502 43.00899320194335, 3.0122966520242502 42.99100679805666, 2.98770334797575 42.99100679805666, 2.98770334797575 43.00899320194335))&offset=0 ).
Previously, I was getting a list of a few hundred occurrences, but now, I get a list of several thousand occurrences.
In the results, I see occurrences that are outside the polygon of my query ("decimalLongitude": -78.702012, "decimalLatitude": 43.003936,).
Best regards,
Antoine

-----

System: Firefox 58.0.0 / Ubuntu 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/b8c63e69b69a589a789fbe7164359c65:24b448b9e0105b347ee3702875c499b99f9ba49c2686ec1f2ba9a486611eee58c3dc3db173073b4bb9281e8f8cb5a3258e4a1832a04f93380b61f555c3ce2a3e)
Referer: https://www.gbif.org/developer/occurrence
Window size: width 1920 - height 868
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-15T13:28:41.646Z',mode:absolute,to:'2018-03-15T13:34:41.646Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-15T13:28:41.646Z',mode:absolute,to:'2018-03-15T13:34:41.646Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment] 2018-03-15 14:10
@fmendezh, another repeat of #1177 and https://github.com/gbif/occurrence/issues/36

**Comment by MattBlissett** [comment] 2018-11-26 10:04
Easier to see what's happening with a website link: https://www.gbif.org/occurrence/map?taxon_key=6&geometry=POLYGON((2.98770334797575%2043.00899320194335,%203.0122966520242502%2043.00899320194335,%203.0122966520242502%2042.99100679805666,%202.98770334797575%2042.99100679805666,%202.98770334797575%2043.00899320194335))

This is a duplicate of the polygon winding order issue.

**Closed** 2018-11-26 10:07 UTC
Labels: api, bug
