### ISSUE TITLE
When I download data as a .csv I get a tab-delimited file that clearly has one comma in it that separates the file into two "chunks" of data that I then have to clean and parse separately, and they don't always parse perfectly.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2103] opened 2019-07-15 19:31 UTC
**When I download data as a .csv I get a tab-delimited file that clearly has one comma in it that separates the file into two &quot;chunks&quot; of data that I then have to clean and parse separately, and they don&#39;t always parse perfectly.**

-----

System: Chrome 75.0.3770 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/65ea7ee79e0b60cddf7e1099f27da172:c44f343746392fb6f074a15d6e0c1d55d23e906860e46ff94a482ba6a8ff5891606cef188db901cbabf9acd7ef0c3996582b89e29c4a548fd3b3c36a05bcd904)
Referer: https://www.gbif.org/occurrence/search?offset=120&has_coordinate=true&has_geospatial_issue=false&taxon_key=1895138
Window size: width 1920 - height 946
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-15T19:26:39.816Z',mode:absolute,to:'2019-07-15T19:32:39.816Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-15T19:26:39.816Z',mode:absolute,to:'2019-07-15T19:32:39.816Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment] 2019-07-16 08:31
Suggested fix https://github.com/gbif/occurrence/issues/100
closing as duplicate of https://github.com/gbif/portal-feedback/issues/2102

**Closed by MortenHofft** 2019-07-16 08:31 UTC
Labels: Under review, bug
