### ISSUE TITLE
Need to add content types to homepage hotlinks

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1945] opened 2019-05-13 10:21 UTC
**Need to add content types to homepage hotlinks**

I have raised this many times, but the introduction of the new (very welcome) taxonomic treatment example on the homepage emphasizes the need to have a simple 1-2 word signpost on each of the homepage boxes to give users a clue about what they refer to, e.g. news, event, data use, blog, taxonomic treatment

-----

User provided contact info: @timhirsch
System: Chrome 74.0.3729 / Mac OS X 10.14.4
User: [See in registry](https://www.gbif.org/api/feedback/user/7c6c32815bb068014c6d80003ba903ae:9f55d0b3771fd22626365dd21e8efa74e51fad7a112a4a712a72abce09c7f6751fd9c4d133b2be0c0d549c2edecb6da352ad6bffcf87b56218a2f5403083371c)
Referer: https://www.gbif.org/
Window size: width 1734 - height 929
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-13T10:16:23.524Z',mode:absolute,to:'2019-05-13T10:22:23.524Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-13T10:16:23.524Z',mode:absolute,to:'2019-05-13T10:22:23.524Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment] 2019-05-13 11:52
@dnoesgaard I have changed the model on your end for features to enable this. It is a fixed enum as I deemed it required least work when filling the data. Given that these can link to anything whatsoever including other sites it is a bit tricky to find a exhaustive vocab, bui I have added what I deemed the most frequent. If you need more you need to let me know so we can add them to the translation file.

> I have raised this many times
I'm unable to locate the many other issues that this is a duplicate of, but feel free to close them as duplicates of this?

**Comment by dnoesgaard** [comment] 2019-05-13 12:38
Thanks. I'm quite happy with this–but I would suggest a more neutral background color, e.g.

`background: rgba(0, 0, 0, 0.33);`

Also, the event card shown as number 3 doesn't have the tags, but maybe that's intentional?

**Comment by dnoesgaard** [comment] 2019-05-14 08:20
I would like to add an option to the enum: Guidance

Thanks!

**Comment by MortenHofft** [comment] 2019-05-14 08:37
@dnoesgaard would you rather have this as free text instead of an enum?

**Comment by MortenHofft** [comment] 2019-05-14 08:39
I can add it to events as well, just didn't see the need to as it was distinct already. I can change the colour as well 😆

**Comment by dnoesgaard** [comment] 2019-05-14 08:45
Free text would be more flexible but then I would have to manage translations in Contentful, right?

**Comment by MortenHofft** [comment] 2019-05-14 08:46
yes you would

**Comment by dnoesgaard** [comment] 2019-05-14 08:49
I guess I can live with that as there aren't that many. Would it be ok if I kept it as a drop-down in Contentful, but you treated it as free text?

**Comment by dnoesgaard** [comment] 2019-05-14 09:02
For the sake of transparency, reiterating what we agreed to

- keep the enum with Crowdin translations
- add tag to events
- add 'guidance' to enum
- change color to transparent black

**Comment by MortenHofft** [comment] 2019-05-14 09:07
If more ideas issues come up in relation to this please open a new issue :)

**Closed** 2019-05-14 09:06 UTC
Labels: idea, portal
